### ISSUE TITLE
requirements/dev.txt

### ISSUE THREAD

**Issue by kavinvalli** [django/djangoproject.com#1008]
### Please read this first:

This is the issue tracker for the website at djangoproject.com, **not** for Django itself.

If you are looking for help or support with using Django, please follow the links in [our documentation](https://docs.djangoproject.com/en/stable/faq/help/).

If you want to submit a bug report or a feature request to Django (including [documentation](https://docs.djangoproject.com)), you can find instructions [here](https://docs.djangoproject.com/en/stable/internals/contributing/bugs-and-features/).

If you want to [report a bug on translations](https://docs.djangoproject.com/en/stable/internals/contributing/localizing/#translations) in Django or djangoproject.com, please use [Transifex](https://www.transifex.com/django/django/dashboard/).

**A lot of requirements in requirements/dev.txt are outdated and are not working with the versions of codes you are using. It is requested to update the requirements regularly**

**Comment by kavin25** [comment]
It is causing lot of problems

**Comment by felixxm** [comment]
3rd party packages have been updated.
