### ISSUE TITLE
Add GitHub Sponsors to website

### ISSUE THREAD

**Issue by jefftriplett** [django/djangoproject.com#1016]
This is a follow up from issue #994. The Django Project has a GitHub Sponsors page (https://github.com/sponsors/django), which is not mentioned on the website. 

My pitch was to mention it in the "Other ways to give" section so that people who use GitHub would know that they have that option vs. using a third-party option. 

Where is the best place to mention this link?

**Comment by carltongibson** [comment]
Link added in #1015

**Comment by jefftriplett** [comment]
@carltongibson thank you

![](https://media.giphy.com/media/5ArJanyCfxgiY/giphy.gif)

**Comment by carltongibson** [comment]
It's thanks to you and @marksweb, but thanks. 😊
