### ISSUE TITLE
Pin version of documentation

### ISSUE THREAD

**Issue by pbelskiy** [django/djangoproject.com#1020]
Hello! It's annoying to select needed Django version in documentation pages when you came from google. I met developers who created custom local JS for auto version selection. 

Could we store on client (cookies, local storage) latest selected documentation version and automatically redirect on it?

I could provide PR for this if you are agree with me and other developers. Thanks!

**Comment by ccurvey** [comment]
I'd add to this the ability to pin the version of Django that I am currently using (I'm often a release or two behind the current version, much less the dev version)

**Comment by timgraham** [comment]
I think this idea came up somewhere before and was rejected. I'm going to say 'wontfix."
