### ISSUE TITLE
Add Corporate Badges

### ISSUE THREAD

**Issue by wsvincent** [django/djangoproject.com#1022]
The DSF Board has commissioned new corporate badges for the 5 tiers of membership: Diamond, Platinum, Gold, Silver, Bronze. They should be added to the https://www.djangoproject.com/foundation/corporate-membership/ page and available for placement on the sites of approved corporate sponsors in the given calendar year.

I've sent the link with sgvs/pngs to @carltongibson.

Can also bump up the Twitter count on bottom of said page, under Benefits, to reflect 125k+ followers now.

**Comment by carltongibson** [comment]
I'll deal with this next week.

**Comment by felixxm** [comment]
> Can also bump up the Twitter count on bottom of said page, under Benefits, to reflect 125k+ followers now.

I updated the number of followers, it's a flatpage.
