### ISSUE TITLE
Error on aggregation example

### ISSUE THREAD

**Issue by xavierlesa** [django/djangoproject.com#1026]
On [this example](https://docs.djangoproject.com/en/3.1/ref/models/expressions/#aggregate-expressions) must to describe an example with `aggregation` rather than  `annotation`.

```python
Company.objects.aggregate(
    managers_required=(Count('num_employees') / 4) + Count('num_managers'))
```

**Comment by felixxm** [comment]
I don't see any issue with using `QuerySet.annotate()`. For the future, this is the issue tracker for the djangoproject.com website. Documentation bugs should be reported on [Trac](https://code.djangoproject.com/) (as described in the issue template).
