### ISSUE TITLE
How to render to specific html div with value from django views?

### ISSUE THREAD

**Issue by sharmila-polamuri** [django/djangoproject.com#1028]
I am trying to deploy a machine learning model using Django. Here I am trying to do is take input from the HTML form, predicting value using a trained model, and sending that result value to the HTML page. Still here working good. But I want to go to a specific division(div tag) of the HTML page based on division(div tag) id. Please help me, anyone; how can I fix this problem.

**HTML code**

**File name :- nlpdocs.html**

```
<div style='background:pink;height:300px;width:600px;left:150px;position:relative' id="spam_try">
    <form action='smsclassifier' method='POST' enctype='multipart/form-data' >
        {% csrf_token %}
        <h2 style='left:80px;position:relative'>SMS Spam Classifier</h2>
        <label>SMS :- </label>
        <textarea id="smstext" name='smstext' rows="4" cols="50" placeholder="Enter SMS here 
        </textarea>
        <button type='submit' > Submit</button>
    </form>  
</div>
<p><h4 style="color: #55CEFF">Input SMS Text :- </h4><h6> {{sms_text}}</h6></p>
<p><h4 style="color: #55CEFF">Entered SMS is :- </h4><h6>{{result}}</h6></p>
```

I create urls file within the django app folder.

**urls.py**

```
urlpatterns = [
    path('',views.home_view,name='home_view'),
    path('index.html',views.home_view,name='home_view'),
    path('nlpdocs.html',views.nlpdocs, name='nlpdocs'),
    path('smsclassifier', views.sms_spam_classification, name='smsclassifier'),
]
```

**views.py**

```
@csrf_exempt
def sms_spam_classification(request):
    """
    Input :- Text 
    Output :- string 
    Return :- classify input text spam or not
    """
    if request.method == 'POST':
        sms_text = request.POST.get('smstext')
        result = predict_new_text(sms_text)
        result_dict = {'result':result, 'sms_text':sms_text}
        return render(request, 'nlpdocs.html#spam_try', result_dict)
```

If I send the only nlpdocs.html to render function, that one works but goes to the top of the page. I want to render the exact division of HTML. When I call template with div id, I got the below error.

```
TemplateDoesNotExist at /smsclassifier
nlpdocs.html#spam_try 
```

Please help me anyone to solve this issue.

**Comment by felixxm** [comment]
This is the issue tracker for the djangoproject.com website. Please see [TicketClosingReasons/UseSupportChannels](https://code.djangoproject.com/wiki/TicketClosingReasons/UseSupportChannels) for ways to get help with Django usage.
