### ISSUE TITLE
Create CSS for Banner styling. 

### ISSUE THREAD

**Issue by carltongibson** [django/djangoproject.com#1035]
For things like the JetBrains promotion, and the #BLM banner, we added HTML looking like this: 

```
    <div id="billboard" style="background: #0C4B33; color: #FFF;">{% block billboard %}
        <div style="text-align:center; padding: 1em 3em; max-width: 60em; margin: 0 auto;">
       ...
```

We should have a CSS declared for such, so we don't have to go looking through the history for the HTML. 

Refs #1004, where @collinanderson suggested the line length limit.

**Comment by dougmellon** [comment]
Do you mind if I take this?

**Comment by carltongibson** [comment]
HI @dougmellon, please do yes. Thanks.

**Comment by sksankarraj** [comment]
Seems like this has been fixed.

**Comment by carltongibson** [comment]
I looked at this for #1227 — I still think this would be a good idea, but I was a bit put-off by the existing CSS (relative to the head-space I had for it this morning.) 

Taking in the rule for limiting the width (as per above here) just needs a bit of double-checking.

**Comment by Maniktherana** [comment]
Can I try this?

**Comment by carltongibson** [comment]
Please do. 

It's a case of translating the inline styles, and defining the HTML (with class) for the banner.

**Comment by Maniktherana** [comment]
Just confirming:
[These are the inline styles](https://github.com/django/djangoproject.com/pull/1004/commits/c45487d3dcddce2e5ea9149b544ee0993be77296) to be implemented right? As currently theres no styles there anymore:
https://github.com/django/djangoproject.com/blob/c83141092375a774fe9a3fd0c26732040ccf2c2a/djangoproject/templates/base.html#L72

**Comment by dassudip2001** [comment]
it is fixed or still pending

**Comment by carltongibson** [comment]
@dassudip2001 I think the PR is just waiting for a last tweak from @Maniktherana (or reviewer) to merge.

**Comment by mks2002** [comment]
I want to work on this issue please assign me this issue.

**Comment by carltongibson** [comment]
There's a PR for this by @Maniktherana in #1302. It's just waiting for some edits from the reviews. You could ask there if they be happy for you to take it over and update, using `Co-authored-by: …` in the commit message if so.

**Comment by kaushal-malpure** [comment]
@carltongibson @pauloxnet  Can I try solving this issue?

**Comment by carltongibson** [comment]
@kaushal-malpure Yes, please do! There's a previous PR to look at. (IIRC it needed adjustments.) 

The task here is to create the CSS selectors, and then make sure the (commented) markup is correct, so that someone can quickly add the banner text. 

Thanks!

**Comment by kaushal-malpure** [comment]
@pauloxnet @carltongibson 
I have worked on the issue and have added the CSS selectors for banner styling. #1422
