### ISSUE TITLE
how to write 3 dependant table join query in Django

### ISSUE THREAD

**Issue by Rajani-salvi** [django/djangoproject.com#1041]
iam new in django , I want to create join query in django, my model is as follow

Model.py

```
Class area_country(models.Model):
    country_id = models.AutoField(primary_key=True)
    country_name = models.CharField(max_length=100, null=True)
    short_name= models.CharField(max_length=20, null=True)
    flag_enable = models.SmallIntegerField()


    class Meta:
        db_table = "area_country"

class area_state(models.Model):
    state_id = models.AutoField(primary_key=True)
    state_name = models.CharField(max_length=100, null=True)
    short_name = models.CharField(max_length=20, null=True)
    country_id = models.ForeignKey(area_country, on_delete=models.CASCADE)
    flag_enable = models.SmallIntegerField()
    
    class Meta:
        db_table = "area_state"


class area_city(models.Model):
    city_id = models.AutoField(primary_key=True)
    city_name = models.CharField(max_length=100, null=True)
    short_name = models.CharField(max_length=20, null=True)
    state_id = models.ForeignKey(area_state, on_delete=models.CASCADE)
    flag_enable = models.SmallIntegerField()


    class Meta:
        db_table = "area_city"
```
i need query like

    SELECT "area_country"."country_id", 
           "area_country"."country_name",
           "area_state"."state_id",
           "area_state"."state_name", 
           "area_city"."city_id",
           "area_city"."city_name" 

   FROM "area_country" 
    LEFT OUTER JOIN "area_state" ON ("area_country"."country_id" = "area_state"."country_id_id") 
    LEFT OUTER JOIN "area_city" ON ("area_state"."state_id" = "area_city"."state_id_id")
** Try by me **

view.py

`result = area_country.objects.all().select_related('area_state').values('country_id', 'country_name', 'area_state__state_id',  'area_state__state_name'`)

when i print it by using query = result.query

```
SELECT "area_country"."country_id", "area_country"."country_name", "area_state"."state_id", "area_state"."state_name" 
FROM "area_country" 
LEFT OUTER JOIN "area_state" ON ("area_country"."country_id" = "area_state"."country_id_id")
this is ok now i try
```

`result = area_country.objects.all().select_related('area_state').select_related('area_city').values('country_id', 'country_name', 'area_state__state_id',  'area_state__state_name','area_city__city_id','area_city__city_name')
`
```
it show me error
Cannot resolve keyword 'area_city' into field. Choices are: area_state, country_id, country_name, flag_enable,  short_name
please help me for django query.
```

**Comment by felixxm** [comment]
This is the issue tracker for the djangoproject.com website. Please see [TicketClosingReasons/UseSupportChannels](https://code.djangoproject.com/wiki/TicketClosingReasons/UseSupportChannels) for ways to get help with Django usage.
