### ISSUE TITLE
Please provide easy-to-download PGP keys for release managers

### ISSUE THREAD

**Issue by mgorny** [django/djangoproject.com#1042]
Could you please consider providing a reliable and easy way of downloading PGP keys of release managers? Since the poisoning attacks, keyservers are quite unreliable and I don't seem to be able to get them off pgp.mit.edu. At least for FE5FB63876A1D718A8C67556E17DF5C82B4F9D00, the server takes awfully long to respond, then says 'no results found'.

Ideally, include them as regular files on the site and include the links to them on the download page. Both separate files for every release manager, or a single combined file with all the keys would work for me.

**Comment by apollo13** [comment]
@mgorny would the suggested approach work for you? Ie ist github reliable enough? :D

**Comment by mgorny** [comment]
Yes, I think it would work just fine. Thanks! That said, you may consider including a 'clickable' URL too.

I didn't know GitHub serves keys like this. This is going to be really helpful in the future, thanks!

**Comment by felixxm** [comment]
I added a clickable link in [the last release notes](https://www.djangoproject.com/weblog/2020/dec/01/django-bugfix-release-314/).

Fixed in https://github.com/django/django/commit/85729545f11257b7790e098fb224637715263616.
