### ISSUE TITLE
Duplicate in Individual members page

### ISSUE THREAD

**Issue by marcorichetta** [django/djangoproject.com#1047]
Hi!

Just came to the foundation's [Individual Members site](https://www.djangoproject.com/foundation/individual-members/) and found **Derrick Kearney** as duplicate.

Not sure where the data is obtained so I couldn't find a way to make a PR.

**Comment by carltongibson** [comment]
Hi @marcorichetta — thanks for the report. AFACS these are in fact separate people. Will verify that though. Thanks.
