### ISSUE TITLE
Google Search Console: submitted zh-hans / Django 3.1 URLs blocked by robots.txt

### ISSUE THREAD

**Issue by tobiasmcnulty** [django/djangoproject.com#1049]
Just started seeing these a few days ago. All 63 URLs are for the `zh-hans` language and Django 3.1. This might be expected (see https://github.com/django/djangoproject.com/commit/9f481df89a8590f8c84341b72b2b51da615315ab), but  wanted to file something for visibility.

![Screen Shot 2020-11-30 at 10 21 29 AM](https://user-images.githubusercontent.com/160132/100628116-dc570980-32f5-11eb-8192-d06641809586.png)

**Comment by carltongibson** [comment]
I think this must have been expected. In later releases we only exclude the the internal and releases sections, which is correct. 

https://github.com/django/djangoproject.com/blob/d71dd4750307743cd0cfdbb6dfa56c3e4802b200/djangoproject/static/robots.docs.txt#L51-L52
