### ISSUE TITLE
Broken link for 2.2 branch

### ISSUE THREAD

**Issue by simkimsia** [django/djangoproject.com#1050]
At https://docs.djangoproject.com/en/2.2/howto/ > [Upgrading Django to a newer version](https://docs.djangoproject.com/en/2.2/howto/upgrade-version/)

It shows 
![image](https://user-images.githubusercontent.com/245021/101236243-9392bc80-370a-11eb-98af-bd4c0fa3948e.png)

**Comment by carltongibson** [comment]
Now resolved.
