### ISSUE TITLE
"Error 503 unable to get local issuer certificate" on https://www.djangoproject.com/

### ISSUE THREAD

**Issue by nadege** [django/djangoproject.com#1051]
Discovered when a CI job couldn't reach https://docs.djangoproject.com/en/dev/_object,
seems to affect the whole website.

**Comment by pauloxnet** [comment]
I confirm the issue in the whole website:
https://www.djangoproject.com

### Error 503 unable to get local issuer certificate
unable to get local issuer certificate
#### Guru Mediation:
Details: cache...
<hr>
Varnish cache server

**Comment by jordyvanraalte** [comment]
I got the same issue.

**Comment by prasenjit476** [comment]
Its resolved now.
