### ISSUE TITLE
Consider adding django-read-only

### ISSUE THREAD

**Issue by carltongibson** [django/djangoproject.com#1059]
I'd quite like to add @adamchainz's https://github.com/adamchainz/django-read-only. 

I need to shell into the production DB for #1058 (to check we can make the `stripe_customer_id` fields unique). 
That'll be fine. I'll not do anything nasty. But frankly I'd rather have software rails in place to make it impossible to alter the DB whilst in there. 

It doesn't have to be turned on by default, but I quite like this (from the README): 

```
$ DJANGO_READ_ONLY=1 python manage.py shell
```

**Comment by adamchainz** [comment]
I'm predictably +1 on this 👍

**Comment by carltongibson** [comment]
😄 

I used a middleware solution Andrew put out some years ago for a long-while. This seems a recurrent need. Wonder if there's be appetite to add such to core...

**Comment by adamchainz** [comment]
Yes it could make sense it core. django-read-only still needs some work though, to be rewritten with a better technique: https://github.com/adamchainz/django-read-only/issues/20

**Comment by carltongibson** [comment]
I think there's value in this, and it would be a good ticket for someone to pick up

**Comment by Maniktherana** [comment]
@carltongibson mind if I work on this?

**Comment by carltongibson** [comment]
Sure. You don't need to ask. 😀
