### ISSUE TITLE
Surface Django blogs (not blog posts) in Community section?

### ISSUE THREAD

**Issue by nemecek-filip** [django/djangoproject.com#1065]
Hello all,

some time ago I created the [DjangoBlogs.com](https://djangoblogs.com) which serves as a directory of Django bloggers. @adamchainz mentioned previously that it could be a good idea to surface these blogs _(not blog posts)_ in the Django Community section.

I have created a small "mock up" how that could look like: Alternatively this could be called "Django blogs" or something similar. Or maybe "Django bloggers" to make it more clear that this does not refer to the aggregated posts.

![Django blogs in Community mockup](https://user-images.githubusercontent.com/49204469/106165821-c8137980-618b-11eb-9d61-216ddc9da10d.png)

DjangoBlogs.com already has an [RSS feed](https://djangoblogs.com/feed) which lists all the blogs on the site, sorted by date added.

I think this could be useful to bring the community more together and provide another "discovery path" for community bloggers to get noticed. 

Thanks for consideration.

**Comment by adamchainz** [comment]
👍 

We have a whole lot of feeds approved and merged into the aggregate feed - 451 at current. I think we'd want to restrict to display sites that have posted in the last year or so.

**Comment by nemecek-filip** [comment]
I am not sure if I described my intention clearly. I was asking about the blogs itself to new section, but I think also aggregating their posts can be nice as well.

451 feeds? Wow that is a lot. I don't suppose it is possible to view them? DjangoBlogs.com currently lists 56 blogs and I have hard time finding new ones.

**Comment by timgraham** [comment]
It's not entirely appropriate in that section because the items that appear are time-based (new blog posts, new job postings, etc.) whereas mew blogs aren't being created each day. Anyway, I think it's best to continue your initiative on your own site rather than add more complexity to djangoproject.com (which has historically lacked consistent maintainers).
