### ISSUE TITLE
is_admin field

### ISSUE THREAD

**Issue by MrEscape54** [django/djangoproject.com#1066]
Hi, just to mention that in the section below (documentation 3.1) the field` is_admin `is mentioned and it is no longer available. Maybe replacing by is_superuser is adviced.
https://docs.djangoproject.com/en/3.1/topics/auth/customizing/#custom-users-and-proxy-models
Thanks for your effort!

**Comment by carltongibson** [comment]
Hi @MrEscape54 — in the example `MyUser` defines the `is_admin` field. Thanks.
