### ISSUE TITLE
Django Custom Admin Actions

### ISSUE THREAD

**Issue by chanduaki** [django/djangoproject.com#1071]
# Summary: 
Django Admin Actions are updating in the django admin panel , but not saving in the Database

# What i need to see?
Update the change in Behavior in the Database 

# What i am seeing?
Updating the change in the admin panel , but not saving in the Database

Steps performed:
1.  written the action in the UserAdmin 
```
def approve_user_by_admin(self, request, queryset):
    queryset.update(is_admin_approved=True)

approve_user_by_admin.short_description = 'Approve Users by Admin'

@admin.register(CustomUser)
class CustomUserAdmin(AbstractUserAdmin):
     actions = [approve_user_by_admin]
```
2. Updated the Users in the admin panel
3. changed the is_admin_approved  to `True` for that bulk users
4. My Logic : ----> is_admin_approved is `True` then is_active have to become `True`
5. But is_active is Still shows -` False`, when is_admin_approved is `True` also
6. when click on the User in the Admin panel, then click on `Save Button`  the state of user is changing is_active = `True`

**Comment by felixxm** [comment]
This is the issue tracker for the djangoproject.com website. Please see [TicketClosingReasons/UseSupportChannels](https://code.djangoproject.com/wiki/TicketClosingReasons/UseSupportChannels) for ways to get help with Django usage.
