### ISSUE TITLE
translation for django permissions

### ISSUE THREAD

**Issue by mh-firouzjaah** [django/djangoproject.com#1074]
hi everybody, I've seen there are some tickets and stackoverflow questions about, `Why django translation doesn't work for Permissions` for example inside the list of permissions for an object of a group or a user instance the list of permissions are not translated, and I found why it is so. also I changed the code to check the result and that was working! so I'm telling the story because I don't know if this answer has side affects or not, and neither where to post a solution so to Django core developing team will see my post and help?
what I did:
edit the `app_labeled_name` function decorated as `property` of this path: `path/to/django/contrib/contenttypes/models.py` of `ContentType` class, to become like this:

    @property
    def app_labeled_name(self):
        model = self.model_class()
        if not model:
            return self.model
        return '%s | %s' % (apps.get_app_config(model._meta.app_label).verbose_name,
                            model._meta.verbose_name)

the trick is to use `apps.get_app_config(model._meta.app_label).verbose_name` instead of `model._meta.app_label`, so it would use the same `verbose_name` as whatever you set for your app in the `AppConfig` subclass of your app.

**Comment by mh-firouzjaah** [comment]
hello again, I come with a much trickier solution!
this would give the same result as my previous post but here I used a `monkeypatch` way,
I added the code below to a `signals.py` file and imported that inside a subclass of `AppConfig.ready()`:

    # signals.py
    from django.contrib.contenttypes.models import ContentType


    def new_app_labeled_name(self):
        model = self.model_class()
        if not model:
            return self.model
        return '%s | %s' % (
            apps.get_app_config(model._meta.app_label).verbose_name, model._meta.verbose_name)


    def class_decorator(cls):
        cls.app_labeled_name = property(new_app_labeled_name)
        return cls


    class_decorator(ContentType)
    
and I forgot to say that for the completion of translation I had to use `django-modeltranslation` to translate the `name` property of `django.contrib.auth.models.Permission` class too!.

    # translation.py
    from django.contrib.auth.models import Permission
    from modeltranslation.translator import TranslationOptions, register


    @register(Permission)
    class PermissionTranslationOptions(TranslationOptions):
        fields = ('name',)

and now in order to be able to complete the modeltranslation job, we have to register `Permissions` on admin panel:

    # admin.py
    from django.contrib.auth.models import Permission
    
    admin.site.register(Permission)

**Comment by felixxm** [comment]
This is the issue tracker for the djangoproject.com website. Please see [TicketClosingReasons/UseSupportChannels](https://code.djangoproject.com/wiki/TicketClosingReasons/UseSupportChannels) for ways to get help with Django usage.

**Comment by erica-lee** [comment]
Thank you for your tip! It works for me!
But I don't get it well.. 
In `translation.py`, auth_permission table need to have `name_XX` fields and I don't add fields. But when I migrate, it automatically performs an additional migration action for add `name_XX` fields.
All I have done is modify `app_labeled_name` property for `ContentType`, so why does that work?
