### ISSUE TITLE
will django stop the mysql version check in the future?  

### ISSUE THREAD

**Issue by minicloudsky** [django/djangoproject.com#1080]
can you stop this fucking check,it is nonsence and so ugly and terrible,I had to comment the checking code everytime.
 File "/usr/local/lib/python3.6/site-packages/django/db/backends/mysql/base.py", line 36, in <module>
  raise ImproperlyConfigured('mysqlclient 1.4.0 or newer is required; you have %s.' % Database.__version__)
django.core.exceptions.ImproperlyConfigured: mysqlclient 1.4.0 or newer is required; you have 0.10.1.

I use pymysql and django,however,this bug seems nonsense and terrible，i had to close the check manualy

**Comment by carltongibson** [comment]
This is not the correct venue for issue reports on Django. This is the repo for the website. 

The minimum version checks are there because Django requires features that are not available in earlier versions. You'd be well served to not ignore the warnings and update.
