### ISSUE TITLE
Documentation for DiscoverRunner not (entirely) correct

### ISSUE THREAD

**Issue by GrazingScientist** [django/djangoproject.com#1085]
The [documentation on the work of the DiscoverRunner](https://docs.djangoproject.com/en/3.1/topics/testing/advanced/#using-different-testing-frameworks) is not entirely correct.

I am specifically refering to bullet point 2:
```
Looking for tests in any file below the current directory whose name matches the pattern test*.py.
```

The documentation somewhere around the given list should also state explicitely that only tests are found that have both an `__init__.py` in the base folder AND an `__init__.py` in the folder with the tests. If not (at least for me) the given tests are not found. This is especially true, if the package folder is not (and is not part of) a registered Django app.

Hope, this is not only me, having this issue.

**Comment by ubernostrum** [comment]
Hi,

This is the issue tracker for the website at djangoproject.com, **not** for Django itself.

If you are looking for help or support with using Django, please follow the links in [our documentation](https://docs.djangoproject.com/en/stable/faq/help/).

If you want to submit a bug report or a feature request to Django (including [documentation](https://docs.djangoproject.com)), you can find instructions [here](https://docs.djangoproject.com/en/stable/internals/contributing/bugs-and-features/).
