### ISSUE TITLE
Documentation's topic guides not available in french for Django 2.2

### ISSUE THREAD

**Issue by Situphen** [django/djangoproject.com#1115]
No topic guide is available in french for Django 2.2 but they all are for Django 2.1 and Django 3.0. Also, the `topics.po` file exists on the `stable/2.2.x` branch of `django-docs-translations`. The rest of the documentation looks fine (only the topic guides are in english on [this page](https://docs.djangoproject.com/fr/2.2/contents/)).

I apologize if you already knew about this or if it's not the right place to report it.

**Comment by carltongibson** [comment]
This seems resolved in later versions.
