### ISSUE TITLE
Different RAW query results from django.db.connection and cx_Oracle

### ISSUE THREAD

**Issue by jam21** [django/djangoproject.com#1117]
I executed the following query from my Django project shell.
`from django.db import connection
balance_query = "some sql query here"
with connection.cursor() as cur:
        cur.execute(balance_query)
        balance_data = cur.fetchall()
        print(balance_date)`

Then I get result after print as (1, 'F', **_77259668_**) (9, 'R', '24153')

The bold value is wrong

**But**
When I execute same query with following code
`import cx_Oracle
dsn_tns = cx_Oracle.makedsn('host', 'post', service_name='name')
conn = cx_Oracle.connect(user=r'user', password='pwd', dsn=dsn_tns)
c = conn.cursor()
c.execute(balance_query)
for r in c:
    print(r)
`
Then it shows correct values which are following

(1, 'F', '**_77244730_**') (9, 'R', '24153')

**Only one value is differentiating which I marked bold and italic Backend**. 
DB is Oracle and I am using same instance with same credentials for both connections.
 It is only happening for one user, for all other users query gives same result with **cx_oracle** and **django.connection.cursor**

**Comment by felixxm** [comment]
This is the issue tracker for the djangoproject.com website. Please see [TicketClosingReasons/UseSupportChannels](https://code.djangoproject.com/wiki/TicketClosingReasons/UseSupportChannels) for ways to get help with Django usage.
