### ISSUE TITLE
Malcolm Tredinnick Memorial Prize listing not updated for 2020

### ISSUE THREAD

**Issue by pauloxnet** [django/djangoproject.com#1121]
https://www.djangoproject.com/foundation/prizes/

We've got Jeff 2019, but not Malcolm 2020.

Announcement post was here https://www.djangoproject.com/weblog/2020/dec/23/2020-malcolm-tredinnick-memorial-prize-awarded-ken/

**Comment by felixxm** [comment]
Added, thanks for the report :+1:
