### ISSUE TITLE
Request data from a table created inside SQL Server

### ISSUE THREAD

**Issue by zakirfarahmand** [django/djangoproject.com#1131]
Hello folks,
I got a question about requesting data from an already built-in database in SQL server management.

With the Django migration, we can migrate data to a database or create a table, then migrate, but what if we want to do it the other way around. Instead of migrating data from Django to the database, we request data from a specific table the is created in the SQL server.

Any idea?

**Comment by felixxm** [comment]
This is the issue tracker for the djangoproject.com website. Please see [TicketClosingReasons/UseSupportChannels](https://code.djangoproject.com/wiki/TicketClosingReasons/UseSupportChannels) for ways to get help with Django usage.
