### ISSUE TITLE
Missing Open Graph meta tags to our website

### ISSUE THREAD

**Issue by pauloxnet** [django/djangoproject.com#1144]
At the moment the previews of the contents of our site on the various social networks do not appear due to the lack of Open Graph meta tags or specific social tags (eg: Twitter, LinkedIn, Facebook, ...)

This is an example of the Django 4.0 release news displayed on Twitter, which is missing the preview container:
![Screenshot 2022-01-21 at 10-59-37 Django ( djangoproject) Twitter](https://user-images.githubusercontent.com/521097/150508698-57b27156-09b8-4c05-b315-615184322baf.png)

I propose to add all the appropriate tags to our site we.

**Comment by JohnPaulGummapu** [comment]
Hey @pauloxnet, I would like to try to fix this issue.

**Comment by carltongibson** [comment]
@JohnPaulGummapu -- please do give it a look! 👍

**Comment by JohnPaulGummapu** [comment]
`
<meta property="og:url" content="https://www.djangoproject.com/weblog/2022/mar/01/bugfix-release/">
<meta property="og:type" content="website">
<meta property="og:title" content="Django bugfix release: 4.0.3 | Weblog | Django">
<meta property="og:description" content="">
<meta property="og:image" content=" //add photo src here//">


<meta name="twitter:card" content="summary_large_image">
<meta property="twitter:domain" content="djangoproject.com">
<meta property="twitter:url" content="https://www.djangoproject.com/weblog/2022/mar/01/bugfix-release/">
<meta name="twitter:title" content="Django bugfix release: 4.0.3 | Weblog | Django">
<meta name="twitter:description" content="">
<meta name="twitter:image" content=" // add photo src here//">
`

> @JohnPaulGummapu -- please do give it a look! 👍

The meta graph sheet is missing from the source code thus the banner isn't previewing. 

This is what I have noticed if there is something more to know, I would be pleased to learn.

**Comment by MaxDragonheart** [comment]
I'm facing in the same problem...

**Comment by pauloxnet** [comment]
I don't think this is stale. We only need a PR to start working on it.
