### ISSUE TITLE
Improve dates for LTS end date

### ISSUE THREAD

**Issue by dougharris** [django/djangoproject.com#1150]
The table of end of support dates on the [download page](https://www.djangoproject.com/download/) shows only month and year for the end of support for future dates. For example, end of extended support for Django 2.2 LTS is listed as "April 2022."

It's not clear if this is the beginning or end of the month (or some other time).

Before being directed to this issue tracker, I mistakenly created [this issue on Django's trac tracker](https://code.djangoproject.com/ticket/33560). A commenter there, said:

>  The exact date isn't determined until the time comes. It's usually been at the beginning of the month when a series of releases are ready (possibly including one last release of the expiring version).

Even this level of detail would improve the clarity of this.

**Comment by carltongibson** [comment]
Sorry but, I agree with the previous sentiment. 

Over a three-year life-span of an LTS I don't see the need to narrow down the EOL date more precisely. LTS versions have over 18months of overlap in which to upgrade — asking which exact day in the very last month is EOL seems to be missing something. 

It also pays to leave a little vagueness. Who's to say that we might not issue one-more release if a serious bug if discovered at the very last moment? There's no saying we would but, it's not something there's any benefit in over-specifying and so self-limiting.
