### ISSUE TITLE
FAQ:Admin contains incorrect information regarding list-filters on ManyToManyFields

### ISSUE THREAD

**Issue by Doomse** [django/djangoproject.com#1159]
The FAQ about the admin page concerning [list filters for ManyToManyFields](https://docs.djangoproject.com/en/dev/faq/admin/#my-list-filter-contains-a-manytomanyfield-but-the-filter-doesn-t-display) states that the filter won't display if there are fewer than two  related objects, since filtering with only a single option would be meaningless.

In reality however, the filter already displays when there is only one related object and adds a `None` option to filter for objects not related to any of the related objects.

The FAQ should probably state that the filter disappers when there are no related objects available, since in that case only the `None` option would remain, which would indeed be a meaningless filter.

**Comment by felixxm** [comment]
This is the issue tracker for the djangoproject.com website. Documentation bugs should be reported on [Trac](https://code.djangoproject.com/).
