### ISSUE TITLE
Webhook listener with csrf

### ISSUE THREAD

**Issue by snehlata08** [django/djangoproject.com#1161]
I want to create a webhook listener for a third party app. But fot this i have to use `@csrf_exempt` .
Without using the above my web app isn't allowing the third party app to send the webhook data. It blocks it and says forbidden. 

My question is if we do it without the csrf token can it cause a security vulnerability? What are the other ways to handle this securely.

**Comment by felixxm** [comment]
This is the issue tracker for the djangoproject.com website. Please see [TicketClosingReasons/UseSupportChannels](https://code.djangoproject.com/wiki/TicketClosingReasons/UseSupportChannels) for ways to get help with Django usage.
