### ISSUE TITLE
Error integrating with MySQL view: "Unknown column in 'field list'"

### ISSUE THREAD

**Issue by ShreyasKolpe** [django/djangoproject.com#1164]
I could not find any reference or issue regarding integrating with _MySQL views_, apart from the setting Meta.managed to `False`. However, since I want my database lifecycle to _always_ be managed outside of Django, I set Meta.managed to `False` for each model corresponding to a table. I also did this for the model corresponding to the MySQL view, and expected things to work fine. However, when I access this model in code, I get the error `Unknown column <mysql_view_name.id> in 'field list'`. Note that I ran both `makemigrations` and `migrate` before `runserver`. On inspecting the migrations file, I see this extra field `id` for that model's migration, defined as ` ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),`. I understand that since it is not serializable, it is needed only in-memory. However, I believe there is something wrong with the way the ORM is behaving, given the above error.

**Comment by felixxm** [comment]
This is the issue tracker for the djangoproject.com website. Please see [TicketClosingReasons/UseSupportChannels](https://code.djangoproject.com/wiki/TicketClosingReasons/UseSupportChannels) for ways to get help with Django usage.
