### ISSUE TITLE
Formatting code with black

### ISSUE THREAD

**Issue by pauloxnet** [django/djangoproject.com#1184]
In the same way as Django's code was formatted with Black in [PR #15387](https://github.com/django/django/pull/15387), I propose to apply it to the code of this repository.

**Comment by HassanShafiq123** [comment]
Hi, I would like to do this. please assign this issue to me.

**Comment by CuriousLearner** [comment]
This looks promising! Let me know if you'd need any help.

**Comment by pauloxnet** [comment]
Please don't ask to work on this issue but propose a PR if you want to work on black formatting.

**Comment by carltongibson** [comment]
Applying the formatting here should assign the django-bot as the commit author, and once merged we should follow up adding the commit to be ignored in git blame. (Cf the matches changes in Django for a guide).
