### ISSUE TITLE
MariaDB does not support unique constraints with conditions. This is not documented in the docs.

### ISSUE THREAD

**Issue by SvenMoenig** [django/djangoproject.com#1191]
Hi,
I have a project, that uses a MariaDB database and tried to add an UniqueConstraint with a condition to my model. Because nothing to the contrary is stated in [the docs](https://docs.djangoproject.com/en/3.2/ref/models/constraints/#uniqueconstraint), I expected that this was supported and was quite surprised by this Warning:
```
( 16:08)$ ./manage.py migrate coredb
System check identified some issues:

WARNINGS:
coredb.Site: (models.W036) MariaDB does not support unique constraints with conditions.
        HINT: A constraint won't be created. Silence this warning if you don't care about it.
Operations to perform:
  Apply all migrations: coredb
Running migrations:
  No migrations to apply.
```
I think, a note about this should be added to the documentation.

**Comment by felixxm** [comment]
We cannot document all caveats. The current warning should be enough.

Moreover, this is the issue tracker for the djangoproject.com website, not for Django itself.
