### ISSUE TITLE
Bad request error 400 by graphql request

### ISSUE THREAD

**Issue by mohamadArdestani** [django/djangoproject.com#1195]
Hello
I setup a django project and use graphene for graphql integration.
the qraphql query work very well in graphql playground but when I try fetch query from react app by js fetch the server return **Bad request 400** .
`export async function fetchDiets() : Promise<Diets|any> {
  

    fetch('http://127.0.0.1:8000/graphql/', {
      method : 'POST',
      mode: 'no-cors',
      credentials: 'include',
      headers: {
        'content-type': 'application/json;charset=UTF-8',
      },
      body: JSON.stringify({
        query: test,
        variables: {
        },
    }),
  }).then(response => response.json())
    .then(json => console.log(json))
    .catch(err=> console.log(err));
  };`

`export const test = `query goodbye {
  goodbye
}`;`

error 
![image](https://user-images.githubusercontent.com/30923651/185239056-69edac8b-341a-4113-82ab-f845af100c76.png)

How can I fix it. ?

**Comment by frankwiles** [comment]
This repository is only for issues related to the djangoproject.com website.  Please find resources for help with Django itself here https://www.djangoproject.com/community/
