### ISSUE TITLE
Document Download Issue (pdf)

### ISSUE THREAD

**Issue by thehassantahir** [django/djangoproject.com#1196]
Hello,

When downloading PDF format of offline django document version 4.1 site redirects on

> https://buildmedia.readthedocs.org/media/pdf/django/4.1.x/django.pdf

and page shows an error
> This XML file does not appear to have any style information associated with it. The document tree is shown below.

`<Error>
<Code>NoSuchKey</Code>
<Message>The specified key does not exist.</Message>
<Key>pdf/django/4.1.x/django.pdf</Key>
<RequestId>NVDVVEC3CZMP1TGT</RequestId>
<HostId>BuJJ5Eqh7v44sfv1NlQRSLU1CXCLRq3o+m5gTge/VX7GM0mODeNwzOuAf9btv1RPaGCjUFohT5g=</HostId>
</Error>`

**Comment by carltongibson** [comment]
Thanks. This will be resolved by https://github.com/readthedocs/readthedocs.org/issues/9525
