### ISSUE TITLE
Categories / tags on blog

### ISSUE THREAD

**Issue by olasitarska** [django/djangoproject.com#120]
New design has tags/categories in blog. I've commented them so far. Do we want to implement them in the future?

**Comment by olasitarska** [comment]
Given that 358 entires that we have so far are not categorized, does it make sense to implement this feature? We would have to categorize them for this to make sense.

**Comment by jezdez** [comment]
@olasitarska yeah, I think it still makes sense, I'm happy to volunteer to do the initial categorization ;)

**Comment by codeadict** [comment]
I can work on this feature and also help categorize

**Comment by timgraham** [comment]
I guess this isn't important.
