### ISSUE TITLE
Upgrade PostgreSQL to version 14

### ISSUE THREAD

**Issue by MarkusH** [django/djangoproject.com#1209]
From the Django Ops team, we'll be upgrade PostgreSQL to version 14. We'll update here when the process is done.

- [ ] https://github.com/django/djangoproject.com/blob/92c7038bd4dceaaa736083ccccf36006e52313c1/docker-compose.yml#L26
- [ ] https://github.com/django/djangoproject.com/blob/92c7038bd4dceaaa736083ccccf36006e52313c1/.github/workflows/tests.yml#L18

**Comment by apollo13** [comment]
Fixed https://github.com/django/djangoproject.com/commit/21147c56df0282eb99e5ee87c53bae1dda4fcbc8
