### ISSUE TITLE
Add Google reCAPTCHA to DSF Contact Form

### ISSUE THREAD

**Issue by zanderle** [django/djangoproject.com#1216]
We get a ton of spam on a daily basis through the [DSF Contact Form](https://www.djangoproject.com/contact/foundation/), which makes it really hard to find actual messages (they get lost in a sea of spam messages). The form uses Akismet to filter out spam, but it doesn't seem to be very effective.

Maybe using something like Google reCAPTCHA could help us to reduce the spam? I'm open to other solutions as well, as long as we can achieve a similar result.

I was going to try doing this myself, but I guess opening an issue and seeing if someone else wants to grab it is a good idea as well.

**Comment by CuriousLearner** [comment]
Carlton [added reCaptcha to fundraising page](https://github.com/django/djangoproject.com/pull/1078/files). I think we can use the same package and add a captcha field in the `DonateForm`.

Let me know what you think.

**Comment by zanderle** [comment]
@CuriousLearner just to clarify, I was talking about [FoundationContactForm](https://github.com/django/djangoproject.com/blob/main/contact/forms.py#L67), but yes, that sounds perfect! 👍

**Comment by CuriousLearner** [comment]
Oh sorry, yeah, I wrote `DonateForm` instead of `FoundationContactForm`. `DonateForm` has this re-captcha added.

Let me give this a try.
