### ISSUE TITLE
Add StaleBot

### ISSUE THREAD

**Issue by pauloxnet** [django/djangoproject.com#1219]
Idea copied from DRF PR [#8423](https://github.com/encode/django-rest-framework/pull/8423)

> Add a StaleBot, configured with the lowest possible run limit.
> The intent here is to help us sweep through the issue and pull request backlog, and review what does and does not need to remain open at this point in time.

**Comment by timgraham** [comment]
Hello Paolo, For what it's worth, I think this is a lame way to handle old issues. The result seems to be Carlton triaging all isses that the bot comments on. You could have asked him to do that without a bot adding noise. Should a useless "issue still valid" comment be required every 180 days? Why not have a human triage each issue now that more people are maintaining this site? Using a bot comes off to me as passive aggressive. Why try to automatically discard years of issues (even if minor)? It's not like the passage of time or lack of activity means the problem went away. A responsible reporter will look through existing issues so they don't report a duplicate and not necessarily leave a comment like "issue still valid." If we close the issue automatically, what did that accomplish? I would think triaging issues would be a good way for new team members to develop their understanding of the site. If you're feeling unknowledgable about an old issue, feel free to ping me for advice. I hope you might reconsider the usefulness of the bot.

p.s. I think it was incorrect to give this the 'trac' label. That references https://code.djangoproject.com/ (an install of Trac) which is actually a separate repo: https://github.com/django/code.djangoproject.com/

**Comment by carltongibson** [comment]
Thanks @timgraham. It's really handy to have you go over and make a quick call on a lot of the older ones! 🎁
