### ISSUE TITLE
Revamp typography (and design?) to account for dark mode changes

### ISSUE THREAD

**Issue by jezdez** [django/djangoproject.com#1238]
There seems to be a confluence around #1003 that this is somehow a good thing to just undo design choices without considering the implications (non I could see in the pull requests) on usability and aesthetic.

Please spend some time to talk to a designer about typography before changing the fonts (#1232) and/or color scheme (#1213) of the site.

**Comment by pauloxnet** [comment]
@jezdez I'm reverting #1232 with the PR #1242 can you take a look ?

**Comment by lcfd** [comment]
Hi! 👋

I don't know if this is the best place to leave some comments but I'll try anyway.

(Disclaimer, those are all my opinions. I don't want to sound arrogant or say it's the absolute truth.)

Dark mode
- The text color in the green buttons should be white. At the moment is black and it's not that readable.
- The links in the documentation (https://docs.djangoproject.com/en/4.1/) should be in a shade of green. At the moment they are red and they seem an error. The color used for the page change looks good.
![CleanShot 2022-10-20 at 12 26 19](https://user-images.githubusercontent.com/9001053/196924532-16d3e0aa-71ad-4e96-b6ea-9a0054eb01c1.png)
- The code snippets use red as the main color, using green can be "more Django"
- The code snippets should use a different shade of gray to be distinguished better

General
- I would appreciate an increase in the `font-size` which at the moment is really small (14px).

These are the first thoughts that came to my mind. I hope I have helped.
I'll stay tuned!

**Comment by RyanWalker277** [comment]
@lcfd I think you should open an issue and mention all the details about your problem , I would like to work on this if the mantainers approve it

> Hi! 👋
> 
> I don't know if this is the best place to leave some comments but I'll try anyway.
> 
> (Disclaimer, those are all my opinions. I don't want to sound arrogant or say it's the absolute truth.)
> 
> Dark mode
> 
> * The text color in the green buttons should be white. At the moment is black and it's not that readable.
> * The links in the documentation (https://docs.djangoproject.com/en/4.1/) should be in a shade of green. At the moment they are red and they seem an error. The color used for the page change looks good.
>   ![CleanShot 2022-10-20 at 12 26 19](https://user-images.githubusercontent.com/9001053/196924532-16d3e0aa-71ad-4e96-b6ea-9a0054eb01c1.png)
> * The code snippets use red as the main color, using green can be "more Django"
> * The code snippets should use a different shade of gray to be distinguished better
> 
> General
> 
> * I would appreciate an increase in the `font-size` which at the moment is really small (14px).
> 
> These are the first thoughts that came to my mind. I hope I have helped. I'll stay tuned!

**Comment by thibaudcolas** [comment]
I see conversation has gone on in #1259, which feels more actionable to me, so I’ll close this issue in favour of the other. On typography, I see we have #286 which already covers serif in dark mode
