### ISSUE TITLE
Add list of Django meetups

### ISSUE THREAD

**Issue by cgl** [django/djangoproject.com#1239]
A list of Django meetups can be featured under community tab.
https://forum.djangoproject.com/t/django-meetups/376

**Comment by JonG0uld** [comment]
[work in progress global list of django meetup groups](https://docs.google.com/spreadsheets/d/18B0qVtjcyVB2gx-UuVgpA78TAcYMOKbGi_hJIInGvdY/edit?usp=sharing)

**Comment by JonG0uld** [comment]
All events on meetup.com now listed.

**Comment by JonG0uld** [comment]
I've changed it now so that the link should work for "view" permissions

**Comment by adamchainz** [comment]
Cheers!

**Comment by Rmaravanyika** [comment]
Ideally where should this be placed and how are we going to maintain it going forward?

**Comment by vibhuti019** [comment]
@cgl can we add the [meetups list](https://forum.djangoproject.com/t/django-meetups/376) above Django RSS Feeds under [Community Tab](https://www.djangoproject.com/community/) ?

**Comment by cgl** [comment]
@vibhuti019 I think that would be a proper place, but I imagine list of events (meetups and conferences) may require its own page. So I am more towards giving a link from community tab to a new page called events (or just meetups to start with) 🤔

**Comment by vibhuti019** [comment]
@cgl  I think we can show feature some upcoming and recent meetups on the community tab and then we can add a link to a page where people can check all the meetups.

**Comment by cgl** [comment]
That needs an active maintenance from us, and commitment from the organisers. It is not feasible I am afraid.

**Comment by vibhuti019** [comment]
So what do you prefer to show on the events page ?

**Comment by Rmaravanyika** [comment]
@vibhuti019 you suggest this should be placed on hold?

**Comment by vibhuti019** [comment]
I don't get any further updates from @cgl, @Rmaravanyika of you can suggest any idea on this I can implement that otherwise we can place this issue on hold.

**Comment by cgl** [comment]
Events page could display, list of events (meetups and conferences). But without explicit dates for meetups.

**Comment by cgl** [comment]
That was my input, sorry for the confusion.

**Comment by rajbhoyar729** [comment]
hi @clg  can we do  here  some  sort  of  webscraping  then we  will not  need  update  the every time the  list

**Comment by vibhuti019** [comment]
@rajbhoyar729 @cgl  do you have any idea from where we can webscrap the data? 
If yes, then will make the development very easy.

**Comment by rajbhoyar729** [comment]
Be can use some popular  web sits like meet up .com etc etc

**Comment by vibhuti019** [comment]
@rajbhoyar729 then there are so many websites. It's just a google search apart. And yes for each time we find a new site we can update our codebase.

**Comment by rajbhoyar729** [comment]
Ya I know it is but  instead  of it we can    just creat a ......  post option instead  of precreated  list so  the organizers of meet-up can   creat a post for this or can register  tere  event to... your website our primary  goal is to show list of meet  ups  right so we can  do it in any way right ...

**Comment by tim-schilling** [comment]
I believe the PSF and DSF offer to cover the Meetup costs for Python/Django user groups. If they store that list of groups in a public fashion, that could be re-used here.

**Comment by cgl** [comment]
I think that type of data can be posted to forum. If we list the groups on the website next to the conferences that should suffice.

**Comment by rajbhoyar729** [comment]
I think we can create an implementation of posting  about the  conference as a good  way to keep the thing updated or  we can create  both  options simultaneously

**Comment by rajbhoyar729** [comment]
if you thing we  can implement this  can i proceed with this

**Comment by cgl** [comment]
I don't think we can accommodate a web scraper under djangoproject.com so if you want to work on such a task I think best way forward is to build a bot for discord or a scraper that you can host elsewhere that posts to forum etc.
The goal here just to list the meetup groups to give them more visibility, there's meetup.com and other platforms to accommodate their monthly events.

**Comment by rajbhoyar729** [comment]
Ok I   want to work on it can you plz.. assigne it to me

**Comment by vibhuti019** [comment]
@rajbhoyar729 If you want you can work on it. But I think we need to get a brief of the solution first. 


@cgl @Rmaravanyika  I have an idea, we can combine github actions and github static pages.
I think we can schedule a daily github action to scrape data and update a static github.io page [Check This Link For Reference ](https://www.swyx.io/github-scraping).
The community page will call this page as an api endpoint and will fetch the scrapped data which will be updated on weekly or daily basis via the github actions?
@Rmaravanyika   @cgl  What do you think as this will not require any other hosting service?

**Comment by vibhuti019** [comment]
The actions can be a seperate repo in that way it will work the best.

**Comment by sabderemane** [comment]
Resolved in #1371
