### ISSUE TITLE
Text rended as red on red (dark mode)

### ISSUE THREAD

**Issue by ewjoachim** [django/djangoproject.com#1255]
Following [this comment](https://github.com/django/djangoproject.com/pull/1246#issuecomment-1284084949).

On dark mode (using Firefox), on outdated versions in the docs (e.g. https://docs.djangoproject.com/en/1.10/ ), the text of the banner appears in red over red, so it's purely impossible to read it without selecting it.

![Screenshot from 2022-10-18 08-52-51](https://user-images.githubusercontent.com/1457576/196357764-35f291bc-5e05-4f4e-9b77-e000d956f1c7.png)
![Screenshot from 2022-10-18 08-53-00](https://user-images.githubusercontent.com/1457576/196357762-27316a1e-b220-4d5a-a683-374d117fe779.png)

**Comment by RyanWalker277** [comment]
Would like to work on this

**Comment by camilonova** [comment]
@RyanWalker277 feel free to work on it. Take this PR as inspiration https://github.com/django/djangoproject.com/pull/1246/files

**Comment by RyanWalker277** [comment]
Thanks @camilonova , I would gladly work on this issue. And thanks for providing the refrence , It's really helpful.

**Comment by RyanWalker277** [comment]
@camilonova I am finding it difficult to load the docs of older versions of Django on localhost , by default , the script only loads the docs of the latest version , I would like to load the docs of all versions of Django on order to solve the issue , can you help me with this?

**Comment by sabderemane** [comment]
Hi @RyanWalker277 , you can add this code in a json file  : 
```
{
  "model": "docs.documentrelease",
  "pk": 37,
  "fields": {
    "lang": "en",
    "release": "1.11",
    "is_default": false
  }
} 
```
and load those data with the loaddata command : `python -m manage loaddata <name of your json file>`. It will load add the 1.11 release documentation in database.

After that, you can update the local documentation to get the 1.11 documentation : `python -m manage update_docs_and_index`. 
Next, you can update directly in database the `release_release` table with the row corresponding to the release 1.11 with the `eol_date` field (2020-04-04 for example) and you should be able to have to documentation 1.11 with red alert.

Hope that helps :)

**Comment by sabderemane** [comment]
@RyanWalker277 you have done this part ?

> After that, you can update the local documentation to get the 1.11 documentation : python -m manage update_docs_and_index.

**Comment by RyanWalker277** [comment]
> @RyanWalker277 you have done this part ?
> 
> > After that, you can update the local documentation to get the 1.11 documentation : python -m manage update_docs_and_index.

Yes I did , ideadlly it should have loaded the `1.11` after this step but it didn't.When I ran the command again , this was the output

![image](https://user-images.githubusercontent.com/32684077/197822973-20886706-26a5-4354-8dc4-1b579d2ea249.png)

**Comment by sabderemane** [comment]
Alright, then try `python -m manage update_docs --force`

**Comment by RyanWalker277** [comment]
> Alright, then try `python -m manage update_docs --force`

Tried that , but facing an error during building of sphinx docs.On googling the error , I found out that `note_versionchanged()` method was depricated in v1.8.0 and removed at v3.0.0 of sphinx.Not sure how to fix this , the only fix seems to change my sphinx version , but not sure how to do it.

![image](https://user-images.githubusercontent.com/32684077/197950356-f64e01f3-e45c-4156-a597-85d959daedde.png)

**Comment by sabderemane** [comment]
FYI: to avoid to have this issue for too long and already discussed with @RyanWalker277, I will handle this issue and make a PR this week ASAP.
