### ISSUE TITLE
Broken dark/light toggle button on Firefox

### ISSUE THREAD

**Issue by pauloxnet** [django/djangoproject.com#1269]
The dark/light toggle button on Firefox is cut in half.

I tested it on Ubuntu 22.10 with Firefox 107.0

![Screenshot djangoproject.com on Firefox 107.0 in Ubuntu 22.10](https://user-images.githubusercontent.com/521097/201725636-9ba83c96-48ea-42e4-add1-67549a12994f.png)

In the same PC with Ubuntu 22.10 the toggle button works on webkit-base browser as Chromium  107.0.5304.87 and Epiphany/Gnome Web 43.0)

**Comment by pauloxnet** [comment]
I've the same issue on Android 13 with Firefox 106.1.0
![DjangoProject on Android 13 with Firefox 106.1.0](https://user-images.githubusercontent.com/521097/201726421-a5007729-36d7-47e3-95ab-af4a679d46cd.png)

**Comment by Yasir761** [comment]
Hello there,
I would love to work on this issue, can you please assign this to me?

**Comment by pauloxnet** [comment]
You can start working on this and comment here after you opened a PR.

**Comment by Yasir761** [comment]
Thank you, very much.
