### ISSUE TITLE
djangoproject.com's rss is generating links to example.com

### ISSUE THREAD

**Issue by diegoug** [django/djangoproject.com#1284]
The rss channel of the djangoproject channel is generating links to example.com
[djangoproject rss community blogs](https://www.djangoproject.com/rss/community/blogs/)

This is a snippet from the rss feed showing the problem
`
This RSS feed is published on
    &lt;a href="https://django-news.com/"&gt;https://django-news.com/&lt;/a&gt;.
    You can also subscribe
    &lt;a href="https://django-news.com/#cta-newsletter"&gt;via email&lt;/a&gt;.
  &lt;/p&gt;</description><dc:creator xmlns:dc="http://purl.org/dc/elements/1.1/">Django News</dc:creator><pubDate>Fri, 09 Dec 2022 11:00:00 -0600</pubDate><guid>https://django-news.com/issues/157</guid></item><item><title>Django Sitemap Tutorial</title><link>https://example.com/tutorials/django-sitemap-tutorial</link><description>A vital part of modern SEO (Search Engine Optimization) is to have a sitemap, an XML file that tells a search engine how often a page is updated and how …</description><dc:creator xmlns:dc="http://purl.org/dc/elements/1.1/">LearnDjango.com</dc:creator><pubDate>Fri, 09 Dec 2022 01:37:10 -0600</pubDate>
`

https://example.com/tutorials/django-sitemap-tutorial

**Comment by vibhuti019** [comment]
Can you please elaborate on the issue?

**Comment by benjaoming** [comment]
I'm not seeing any links to example.com in https://www.djangoproject.com/rss/community/blogs/

Perhaps this issue is fixed? @diegoug can you have a look?

**Comment by diegoug** [comment]
@benjaoming yes, they stopped going wrong a while ago, I had already forgotten
