### ISSUE TITLE
Django Community: New/updated Django packages feed ingestion is broken

### ISSUE THREAD

**Issue by jefftriplett** [django/djangoproject.com#1299]
The latest items from https://www.djangoproject.com/community/packages/ are from October 27, 2017.

The DjangoPackages.org RSS appears to be working, but I'm happy to follow up if something is broken on the website: https://djangopackages.org/feeds/packages/latest/rss/

<img width="935" alt="Xnapper-2023-01-03-14 04 44-46B20C07-BD97-4CF2-93BF-9C5C4CCC12A8" src="https://user-images.githubusercontent.com/50527/210432943-1a7530cf-5c4c-4778-b50f-61e85f8feefd.png">

I'm happy to help if someone can point me to where that should be :) 

related to https://github.com/django/djangoproject.com/issues/1137

**Comment by carltongibson** [comment]
Hey @jefftriplett — yes! I think this is likely related to https://github.com/django/djangoproject.com/issues/1137. 

Everything that follows is **I think**…

The issue is that the `superfeedr` service that we've been using forever is now unmaintained and it slowly rotting. 

We need to replace it with our own. `feedparser` mapping entries into the `FeedItem` model, in a management command, that we can run 6hrly (say). 

This shouldn't be too ops intensive, such we can't do it ourselves. But if it is I'm minded to spin up a mini-instance myself just so we can get passed this. 

The relevant model is in the `aggregator` app. 

If you break ground here, I'm very happy to input as needed. Otherwise I have it down as a possible GSoC idea (but that's still time away)

**Comment by jefftriplett** [comment]
@carltongibson circling back here. Do we have a dump of feed urls by chance to test with? (I have admin access, but so-many-feeds)

**Comment by jefftriplett** [comment]
I'm told this might project getting pulled into Jazzband might be semi-related. https://github.com/brutasse/django-push

**Comment by medmunds** [comment]
Now the new/updated packages feed is showing mostly gambling site spam. The last actual Django package updates listed are from 2017.

Maybe just remove it until it can be repaired?

**Comment by jefftriplett** [comment]
cc @bmispelon since we were both looking into this on Friday. The Django Package feed has newer links, but ingestion isn't picking up on it. I thought we'd removed the other feed that someone must have bought and squatted on.

**Comment by bmispelon** [comment]
I did remove some spam entries on Friday, and I don't see them anymore on the page at https://www.djangoproject.com/community/packages/

@medmunds Where do you see spam entries?

**Comment by medmunds** [comment]
(Just for reference, what I am seeing is in the page at https://www.djangoproject.com/community/)

<img width="388" alt="django-community-projects-feed-spam" src="https://github.com/django/djangoproject.com/assets/639984/262e68c9-8aff-4ca4-b465-96bc18fc5ec1">

**Comment by jefftriplett** [comment]
I see a new update from August 4th, 2024 this year which ~7 years in between updates. I *think* there is a chance this is fixed but I will leave this open until we verify it or see a few more trickle in. https://www.djangoproject.com/community/packages/

**Comment by nanuxbe** [comment]
On Oct 5th, this still seems to be working fine:
![image](https://github.com/user-attachments/assets/d9e6cd17-5d73-450d-b159-5939d8953fc4)

**Comment by carltongibson** [comment]
@nanuxbe the issue here was with adding new feeds. Existing feeds (like Django Packages) have always kept working. 

Not sure if it's still the case or not that new feeds can't be OK'd.

**Comment by jefftriplett** [comment]
@carltongibson I just approved a "pending" feed to test it. Previously, it 500'ed, but it didn't this time. 

If you see Django News Jobs show up the next time the "Django jobs" feeds gets refreshed, then I would call it fixed and close the issue: https://www.djangoproject.com/community/

**Comment by carltongibson** [comment]
@jefftriplett cool. Let's look into it this week. It'll be good if we can add new feeds. (So many new folks posting...)


Still think we need a replacement medium term... 😉

**Comment by jefftriplett** [comment]
I'm seeing Jobs flowing through the community jobs feed which is a positive sign that things are working again: https://www.djangoproject.com/community/jobs/

Thank you everyone for looking!
