### ISSUE TITLE
Drop AmazonSmile from fundraising page

### ISSUE THREAD

**Issue by adamchainz** [django/djangoproject.com#1300]
The program ends February 20: https://www.aboutamazon.com/news/company-news/amazon-closing-amazonsmile-to-focus-its-philanthropic-giving-to-programs-with-greater-impact

I think we can remove before then since any new donations we could acquire fron the link would be minimal.

**Comment by carltongibson** [comment]
Agreed

**Comment by pauloxnet** [comment]
Thanks for reporting it. I totally agree.

**Comment by jezdez** [comment]
Bummer^n https://hachyderm.io/@mrzaius/109719017646579986

**Comment by adamchainz** [comment]
Bummer!
