### ISSUE TITLE
Website root page not accessible

### ISSUE THREAD

**Issue by udit-001** [django/djangoproject.com#1308]
Getting the following error when accessing the root page of the website.

![image](https://user-images.githubusercontent.com/23015406/215744753-214d64e9-5a16-4f6a-ac95-d37be2765d17.png)

The docs however are still accessible.

**Comment by RyanWalker277** [comment]
The website is accessible in my region. Seems to be an issue specefic to your region. Can you share some details?

**Comment by CuriousLearner** [comment]
Thanks for reporting, but the site seems to be working fine.

Maybe it's your DNS config.

<img width="690" alt="Screen Shot 2023-01-31 at 5 22 40 PM" src="https://user-images.githubusercontent.com/8039608/215752689-0cddb087-ba84-4589-842d-4bf5048a9dce.png">


Feel free to re-open in case you've any other details.

**Comment by udit-001** [comment]
The DNS resolution is taking place correctly, it is resolving to the correct IP, I ran a test using ping:
![image](https://user-images.githubusercontent.com/23015406/215757593-d66c789a-d02b-4ef8-9839-1990c7454b39.png)

However, and to be sure that this wasn't a browser issue, I tried using curl as well and this was the response:
![image](https://user-images.githubusercontent.com/23015406/215757758-61feeb23-87df-48da-9d6c-8ce81ae63b31.png)

And I am trying to access it from India/Asia region
