### ISSUE TITLE
pre-commit error installing isort. 

### ISSUE THREAD

**Issue by carltongibson** [django/djangoproject.com#1311]
See: https://results.pre-commit.ci/run/github/690903/1675689377.fjUOpYlpRKykyU9Ou432Jg
On e.g.: https://github.com/django/djangoproject.com/commit/4eba591ffd31356cda3a267c9d438b54408a89c1

`pre-commit` is failing to install isort.

**Comment by browniebroke** [comment]
Was an issue caused by a release of poetry-core ~9 days ago. 

Fixed by https://github.com/django/djangoproject.com/pull/1307

**Comment by CuriousLearner** [comment]
I just merged it. It fixes the issue.

Thanks Bruno :) @browniebroke
