### ISSUE TITLE
3rd party libraries should not be able to change sensitive settings

### ISSUE THREAD

**Issue by mercelino** [django/djangoproject.com#1318]
I've encoutered a certain problem with 3rd party django library recently where it removes the clickjacking middleware from the django settings.

https://github.com/newpanjing/simpleui/blob/master/simpleui/apps.py

The issue is from the library itself since it doesn't mention this in its documentation. I submitted the issue on their github. But i believe there is also an action that should be done on the django library side where it should not allow certain settings to be modified by these libraries.

A quick solution for this is to just set these settings as tuples instead of lists. This is what i have done in my case since they are immutable and can't be changed.

Any other solution or suggestion is welcome as long as we don't let 3rd party libraries have control on the internal project settings.

**Comment by timgraham** [comment]
This is the issue tracker for the djangoproject.com website. For Django itself, see https://code.djangoproject.com/. That said, I don't think this is actionable as 1) there may be legitimate cases for third-party apps modifying settings, 2) there's no easy way to identify third-party apps, and 3) you should audit all third-party apps to confirm they have no malicious behavior. Feel free to post on the [django-developers mailing list](https://groups.google.com/forum/#!forum/django-developers) if you wish to discuss this further.
