### ISSUE TITLE
Django 4.1 support  async，not use for await

### ISSUE THREAD

**Issue by lijiachang** [django/djangoproject.com#1319]
```
class TradeVolume(models.Model):
    address = models.CharField(max_length=100, db_index=True, )
    day_time = models.BigIntegerField()  
    minted = models.BooleanField(default=False, )

TradeVolume.objects.filter(address=address, minted=False).values_list('day_time', flat=True)
```

how can i make it to async ?
there is no method named 'avalues_list',  (a + values_list)

**Comment by felixxm** [comment]
This is the issue tracker for the djangoproject.com website. Please see [TicketClosingReasons/UseSupportChannels](https://code.djangoproject.com/wiki/TicketClosingReasons/UseSupportChannels) for ways to get help with Django usage.
