### ISSUE TITLE
Dark mode on issues page not working

### ISSUE THREAD

**Issue by tangorishi** [django/djangoproject.com#1336]
Not able to switch to Dark Mode in the ISSUE section of the website , attaching the screenshot for the same  do check out.

![Screenshot (236)](https://user-images.githubusercontent.com/110519406/229338948-9490b223-49af-4e7b-826a-8a956e76e678.png)

**Comment by sabderemane** [comment]
This is "normal" since it's only on the djangoproject repo and issue is part of another repo (linked to Trac). The dark mode is currently in progress on this part.

**Comment by tangorishi** [comment]
> This is "normal" since it's only on the djangoproject repo and issue is part of another repo (linked to Trac). The dark mode is currently in progress on this part.

thanks for clearing!!

**Comment by lumenCodes** [comment]
Can we close this issue now. @sabderemane sabd
