### ISSUE TITLE
Sponsor logos are not displayed correctly

### ISSUE THREAD

**Issue by sabderemane** [django/djangoproject.com#1339]
![screenshot_2023-03-22_at_14.54.09.png](https://user-images.githubusercontent.com/17890338/229859162-6f7c97b9-7b87-423a-b9cb-75c40e6abd6a.png)

Sponsor logos are not displayed correctly in dark mode, one option to correct this would be to add a default background for each image in dark mode only.

Make sure it's still display correctly in light and dark mode on the switch of the button.

**Comment by singhshivansh244** [comment]
I can solve this issue by giving white background to all img, Kindly, assign issue to me.

**Comment by singhshivansh244** [comment]
Kindly look my pull request @sabderemane.
