### ISSUE TITLE
Search seems broken ?

### ISSUE THREAD

**Issue by ewjoachim** [django/djangoproject.com#1352]
Hey! It looks like there may be an issue with the search function on the website.

(Using Firefox or Chromium)

![Screenshot from 2023-04-26 09-54-13](https://user-images.githubusercontent.com/1457576/234508352-ac796adf-c1f8-4f45-aa3e-51265c786803.png)

The search is returning 0 results whatever the query is

**Comment by felixxm** [comment]
Can you check again? It should work now.

**Comment by ewjoachim** [comment]
![Screenshot from 2023-04-26 10-12-15](https://user-images.githubusercontent.com/1457576/234512591-9b24d66b-2cfc-4f18-9ea9-a24439856b9b.png)

Yes it does, thanks! What was the issue ?

**Comment by felixxm** [comment]
Documents were not indexed.
