### ISSUE TITLE
Django 4.0 cannot be downloaded on the downloads page

### ISSUE THREAD

**Issue by ebaumgartner** [django/djangoproject.com#1362]
https://www.djangoproject.com/download/ does not have a download link for
Django 4.0 anywhere.

Support for 4.0 ended fairly recently, maybe when the link was removed
from the "Previous Releases" section it didn't get added back in the
"Unsupported Prior Releases" section?

FWIW I noticed this because I tend to upgrade from LTS to LTS, and when I
do so I go one version at a time, running tests to see what kinds of
deprecation warnings appear. So even though 4.0 is unsupported I still
have reason to install it (briefly) on the way to 4.1 and 4.2.

**Comment by felixxm** [comment]
Thanks for the report. Fixed.
