### ISSUE TITLE
Update fellows list 

### ISSUE THREAD

**Issue by pauloxnet** [django/djangoproject.com#1363]
The list of Django fellows on the DSF Committees page is not updated:
https://www.djangoproject.com/foundation/committees/#fellow

**Comment by nessita** [comment]
This required access to the admin, so I fixed it myself. Below screenshot of the result:

![image](https://github.com/django/djangoproject.com/assets/124304/1fa1626b-d3b8-4c4b-9d24-3aaf5a81ee60)
