### ISSUE TITLE
Bug: Docs route is not working locally

### ISSUE THREAD

**Issue by omgupta2202** [django/djangoproject.com#1373]
After Running Locally with Docker, I encountered an issue- On clicking the documentation button. When accessing the URL "http://docs.localhost:8000/en/4.2/", I'm getting a "Page not found (404)" error.

Issue Description:
I encountered an error when trying to access a specific documentation page on my Django application. The error message indicates that the JSON data file for the requested documentation page is not found. Here are the details of the issue:

Steps to Reproduce:

Build the documentation project.
Start the Django application.
Access the documentation page with the URL en/4.2/.

Expected Behavior:
The documentation page should be displayed without any errors.

Actual Behavior:
I receive a "Page not found (404)" error message and the following stack trace:

<img width="1437" alt="Screenshot 2023-06-14 at 6 15 57 PM" src="https://github.com/django/djangoproject.com/assets/66220328/7ae53f05-6a69-46e7-86d5-24d472617920">

<img width="641" alt="Screenshot 2023-06-14 at 6 15 24 PM" src="https://github.com/django/djangoproject.com/assets/66220328/2999ff6d-a0fb-4ceb-8098-d408ae4dc55d">

Please let me know if there's any additional information or context that would be helpful in troubleshooting this issue.

**Comment by omgupta2202** [comment]
Hi @sabderemane i tried to run command "docker-compose exec web python manage.py update_docs_and_index" this gives error- "ModuleNotFoundError: No module named 'registration'". I installed registration module still same error.

**Comment by implicitdefcncdragneel** [comment]
Hi @omgupta2202 did you tried `python manage.py update_docs` ?
