### ISSUE TITLE
[Docs] Adding another language support in Docs : Hindi

### ISSUE THREAD

**Issue by 1Shubham7** [django/djangoproject.com#1382]
Hindi the widely understood in India, a country many Django developers come from. Adding Docs in Hindi can help the project significantly. 
![django](https://github.com/django/djangoproject.com/assets/116020663/4f3e00c7-ff44-4a59-8a2c-52c4ae512b94)

**Comment by Esh07** [comment]
Hi @1Shubham7, I appreciate your contribution and I believe that the [Django Docs Translations repository](https://github.com/django/django-docs-translations) would be the best place to post your content to keep it related to the repository. 

The repository has a good description that points out where active discussions usually take place regarding the docs and translations. 

Thank you for considering this suggestion.
