### ISSUE TITLE
Color contrast choice for the banner on the header.

### ISSUE THREAD

**Issue by waregagbagbo** [django/djangoproject.com#1399]
![current-design](https://github.com/django/djangoproject.com/assets/44092807/20496ec4-65ed-4141-8d60-4b48be1d1ee0)
![rev](https://github.com/django/djangoproject.com/assets/44092807/99c985a2-3708-4479-812d-3a3276088312)

### Please read this first:

This is the issue tracker for the website at djangoproject.com, **not** for Django itself.

If you are looking for help or support with using Django, please follow the links in [our documentation](https://docs.djangoproject.com/en/stable/faq/help/).

If you want to submit a bug report or a feature request to Django (including [documentation](https://docs.djangoproject.com)), you can find instructions [here](https://docs.djangoproject.com/en/stable/internals/contributing/bugs-and-features/).

If you want to [report a bug on translations](https://docs.djangoproject.com/en/stable/internals/contributing/localizing/#translations) in Django or djangoproject.com, please use [Transifex](https://www.transifex.com/django/django/dashboard/).

**Comment by sabderemane** [comment]
Thank you for your concern, I'm closing it since it is already mentioned in issue #1381

**Comment by waregagbagbo** [comment]
Great.
