### ISSUE TITLE
27abraham06.13@gmail.com

### ISSUE THREAD

**Issue by Abraham0613** [django/djangoproject.com#1403]
### Please read this first:PORT=6060
CLIENT_ORIGIN_URL=http://localhost:4040
AUTH0_AUDIENCE=AUTH0-AUDIENCE
 @AUTH0_DOMAIN=AUTH0-DOMAIN

This is the issue tracker for the website at djangoproject.com, **not** for Django itself.

If you are looking for help or support with using Django, please follow the links in [our documentation](https://docs.djangoproject.com/en/stable/faq/help/).

If you want to submit a bug report or a feature request to Django (including [documentation](https://docs.djangoproject.com)), you can find instructions [here](https://docs.djangoproject.com/en/stable/internals/contributing/bugs-and-features/).

If you want to [report a bug on translations](https://docs.djangoproject.com/en/stable/internals/contributing/localizing/#translations) in Django or djangoproject.com, please use [Transifex](https://www.transifex.com/django/django/dashboard/).

**Comment by sabderemane** [comment]
Closing as there are no relevant issue here

**Comment by Abraham0613** [comment]
Repositorio de clave.
