### ISSUE TITLE
Make it clear to use `object_list` to get the QuerySet results in the template/view approach

### ISSUE THREAD

**Issue by imran-uk** [django/djangoproject.com#1413]
The docs [here ](https://docs.djangoproject.com/en/4.2/topics/pagination/#using-paginator-in-a-view-function) explain about using the Paginator in a view/template but do not clearly explain about use of `object_list` to get the results.

Please make it clear that you cannot simply pass "page_obj" to the context and expect everything to work like in the ListView approach.

Instead you need to explicitly pass in a template variable like:

```python
page_obj = paginator.get_page(page_number)
results_list = page_obj.object_list
```

then in context

```python
{
 "page_obj": page_obj,
 "results_list": results_list,
}
```

finally in the template you can iterate over "results_list"

I spent quite a bit of time just passing "page_obj" to my template and iterating over it and tearing my hair out why I was not getting any results.

**Comment by JohnPaulGummapu** [comment]
@imran-uk
You're correct that it's not enough to pass `page_obj` alone to the template

When using Paginator in Django templates, you need to follow these steps.

-> In your view, create an instance of the Paginator class and use it to paginate your queryset.

```
from django.core.paginator import Paginator

def my_view(request):
    items_per_page = 10  # Define the number of items per page
    queryset = YourModel.objects.all()
    paginator = Paginator(queryset, items_per_page)
    
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    
    results_list = page_obj.object_list  # Extract the list of objects for the current page
    
    context = {
        "page_obj": page_obj,
        "results_list": results_list,
    }
    
    return render(request, 'your_template.html', context)

```

-> In your template, you can then iterate over the `results_list` to display the items on the current page.

```
<ul>
    {% for item in results_list %}
        <li>{{ item.name }}</li>
        <!-- Display other item attributes as needed -->
    {% endfor %}
</ul>
```

->To create pagination controls, you can use the page_obj provided by the Paginator:

```
<div class="pagination">
    <span class="step-links">
        {% if page_obj.has_previous %}
            <a href="?page=1">&laquo; first</a>
            <a href="?page={{ page_obj.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current-page">{{ page_obj.number }}</span>

        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">next</a>
            <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
        {% endif %}
    </span>
</div>
```

**Comment by sathyaar5** [comment]
> The docs [here ](https://docs.djangoproject.com/en/4.2/topics/pagination/#using-paginator-in-a-view-function) explain about using the Paginator in a view/template but do not clearly explain about use of `object_list` to get the results.
> 
> Please make it clear that you cannot simply pass "page_obj" to the context and expect everything to work like in the ListView approach.
> 
> Instead you need to explicitly pass in a template variable like:
> 
> ```python
> page_obj = paginator.get_page(page_number)
> results_list = page_obj.object_list
> ```
> 
> then in context
> 
> ```python
> {
>  "page_obj": page_obj,
>  "results_list": results_list,
> }
> ```
> 
> finally in the template you can iterate over "results_list"
> 
> I spent quite a bit of time just passing "page_obj" to my template and iterating over it and tearing my hair out why I was not getting any results.
@imran-uk 

It's important to note that you can't simply pass "page_obj" to the context and expect it to work like in the ListView approach. Instead, explicitly extract the object_list like this:
`page_obj = paginator.get_page(page_number)
results_list = page_obj.object_list
`
Then, include both "page_obj" and "results_list" in your context:
`{
 "page_obj": page_obj,
 "results_list": results_list,
}
`
In your template, iterate over "results_list" to display the paginated results. This clarification can save you from the frustration of not seeing results when mistakenly passing just "page_obj" to your template.

**Comment by sathyaar5** [comment]
Hey @imran-uk 
It's important to note that you can't simply pass "page_obj" to the context and expect it to work like in the ListView approach. Instead, explicitly extract the object_list like this:

`page_obj = paginator.get_page(page_number)
results_list = page_obj.object_list
`
Then, include both "page_obj" and "results_list" in your context:

`{
 "page_obj": page_obj,
 "results_list": results_list,
}
`
In your template, iterate over "results_list" to display the paginated results. This clarification can save you from the frustration of not seeing results when mistakenly passing just "page_obj" to your template.

**Comment by sathyaar5** [comment]
Hey @imran-uk  that's correct!
It's important to note that you can't simply pass **page_obj** to the context and expect it to work like in the **ListView** approach. 

Instead, explicitly extract the **object_list** like this:
`page_obj = paginator.get_page(page_number)
`
`results_list = page_obj.object_list
`
Then, include both "page_obj" and "results_list" in your context:

`{
 "page_obj": page_obj,

 "results_list": results_list,
}
`
In your template, iterate over **results_list** to display the paginated results. This clarification can save you from the frustration of not seeing results when mistakenly passing just **page_obj** to your template.

**Comment by imran-uk** [comment]
Thank you for the explanation and detailed reply.

I did figure it out eventually.

What I'm saying is that the examples in the documentation need to be clear
- your example below would be a good starting point, just add it to the
page.

**Comment by jackoconnordev** [comment]
If this issua still exists should a new issue be opened in the main Django repository, since the documentation pages are generated by Sphinx from docs in django/django?

**Comment by felixxm** [comment]
This is the issue tracker for the djangoproject.com website.
