### ISSUE TITLE
Searching documentation is broken

### ISSUE THREAD

**Issue by iamjameswalters** [django/djangoproject.com#1416]
![image](https://github.com/django/djangoproject.com/assets/33947683/da74411f-dfae-4364-921e-895ade8eb46f)

When searching for most any keyword in the documentation, the search returns 0 results.

**Comment by CuriousLearner** [comment]
Hello @iamjameswalters 👋🏼 

Thanks for the report. I am not able to reproduce this. Can you please add more info if this is still occurring for you?

<img width="997" alt="Screenshot 2023-10-10 at 8 44 55 PM" src="https://github.com/django/djangoproject.com/assets/8039608/f39b4af7-7bc8-406d-a8e9-aa3c350551b1">

**Comment by CuriousLearner** [comment]
Are you trying this on a local build?

**Comment by iamjameswalters** [comment]
Ah, it appears to be resolved now! No I wasn't working locally on it, I was using the site. I'll close this now since it looks like it's working again.
