### ISSUE TITLE
Fix mobile menu initial flashing

### ISSUE THREAD

**Issue by circus2271** [django/djangoproject.com#1423]
There is a flash of "unstyled" menu content on mobile devices

<div style="display: flex">
  <img src="https://github.com/django/djangoproject.com/assets/6430448/367bafc2-48a6-4541-8979-72f89881a895" width="25%" style="display: block">
  <img src="https://github.com/django/djangoproject.com/assets/6430448/af975888-03df-4099-a86d-cf6cca607fec" width="25%" style="display: block">
</div>

**Comment by akshayrajput12** [comment]
hello sir i would like to contribute on this issue

**Comment by akshayrajput12** [comment]
@circus2271  i would like to work on this issue

**Comment by circus2271** [comment]
Hi @akshayrajput12 
No doubt, it's a nice issue, but chances are that pr above covers the case

**Comment by circus2271** [comment]
(closed by assident, sorry)

**Comment by sabderemane** [comment]
Hi @circus2271 , can you give us more information on how this happened please? Even a short video if you can.

**Comment by circus2271** [comment]
yeah, sure @sabderemane 

https://github.com/django/djangoproject.com/assets/6430448/6cb3541f-70fe-4573-ab48-1c0755a8f1e3
