### ISSUE TITLE
Link to source code in the documentation

### ISSUE THREAD

**Issue by plktagrawal** [django/djangoproject.com#1425]
Python documentation provides Github link of the corresponding source code on each page. 

For example: 
![Screenshot 2023-10-31 at 4 15 24 PM](https://github.com/django/djangoproject.com/assets/44734800/1a9bfa56-1601-4d3f-977e-827d60f105cd)

It should be useful to have similar links in the Django documentation as well, especially will so many form classes and Model classes in the framework.

**Comment by sabderemane** [comment]
Hi @plktagrawal, this is already a ticket for this in [django core](https://code.djangoproject.com/ticket/29942) and a PR linked, you can follow the progress there. Closing this issue since there a ticket open in django core.
