### ISSUE TITLE
Docker build fail

### ISSUE THREAD

**Issue by jitvimol** [django/djangoproject.com#1428]
I run docker-compose build and I got this error.  I have no idea how to fix so I would like to report problem here.

#8 79.24 E: Failed to fetch http://deb.debian.org/debian/pool/main/i/isl/libisl23_0.23-1_amd64.deb  503  Service Unavailable [IP: 199.232.166.132 80]
#8 79.24 E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?

#12 97.32 E: Failed to fetch http://deb.debian.org/debian/pool/main/n/node-mute-stream/node-mute-stream_0.0.8-2_all.deb  503  Service Unavailable [IP: 199.232.166.132 80]
#12 97.32 E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
#12 97.32 Fetched 49.3 MB in 1min 12s (680 kB/s)
------
process "/bin/sh -c apt-get update     && apt-get install --assume-yes --no-install-recommends         gettext         git         make         netcat-openbsd         npm         postgresql-client-13         rsync     && rm -rf /var/lib/apt/lists/*" did not complete successfully: exit code: 100
ERROR: Service 'web' failed to build : Build failed

**Comment by sabderemane** [comment]
This doesn't seems related to the project but more on your installation and docker. 

As you have an error service unavailable, I think you wasn't able to reach the website to get the package and might try again or see with community docker support.

Closing this issue, as it's not related to djangoproject.com.

**Comment by jitvimol** [comment]
Thank you very much.  My apologize.
