### ISSUE TITLE
Upgrade Django from 3.2 to 4.2

### ISSUE THREAD

**Issue by sarahboyce** [django/djangoproject.com#1437]
As 3.2 will no longer be supported from Q2 next year, we should upgrade Django.

**Comment by bmispelon** [comment]
Hi,

I've been working for the past few weeks on bringing code.djangoproject.com to modern Python and Django versions and we're almost caught up to Django 3.2 now.

Would it be OK for me to pick this issue up so I can work on upgrading both sites in parallel?

**Comment by sabderemane** [comment]
Hi @bmispelon 😄 sure, I've assigned you in the issue

**Comment by sarahboyce** [comment]
Yes 🙂 we're been trying to upgrade the dependencies. These are the sticking points:
- django-push needs to issue a release to pypi but the package is looking for a new home. Been trying to move to Jazzband with no luck: https://github.com/jazzband/help/issues/351
- we've had to revert a django-recaptcha upgrade twice and have raised an issue here: https://github.com/django-recaptcha/django-recaptcha/issues/348

**Comment by bmispelon** [comment]
Thanks and thanks 😁 

Knowing what the blocker are is super helpful 👍🏻  I'll see if I can come up with alternate solutions or if i can poke the right people to move things forward

**Comment by bmispelon** [comment]
I've added a workaround for the issue with django-recaptcha: #1480

**Comment by sarahboyce** [comment]
Django 3.2 is no longer supported: https://www.djangoproject.com/weblog/2024/apr/03/bugfix-release/
I think our blocker here is needing a solution for `Django-PuSH`

**Comment by bmispelon** [comment]
> Django 3.2 is no longer supported: https://www.djangoproject.com/weblog/2024/apr/03/bugfix-release/ I think our blocker here is needing a solution for `Django-PuSH`

No release has been made on PyPI, but support for Django 4.2+ has been committed, so we can pin against that. I've taken that approach in PR #1487 and it seems to work well.

**Comment by bmispelon** [comment]
I've finally deployed 4.2 (it took more work than I'd hoped but we got there in the end).

Thanks to everyone involved, this was a big team effort and you're all amazing! ✨
