### ISSUE TITLE
Donation not working: "There was an error setting up your donation. Sorry. Please refresh the page and try again."

### ISSUE THREAD

**Issue by nemecek-filip** [django/djangoproject.com#1442]
Hello,

_not sure if this is most appropriate way to report this, feel free to close this issue if not._

I was checking the funding state and wanted to contribute _(I am currently using GitHub sponsors)_ but it doesn't seem to work. Both in Safari and Firefox I am getting error dialog after clicking on "Donate".

Tried refreshing the page many times and still the same issue. I am on macOS Sonoma with up-to-date browsers. Mobile Safari works and redirects to Stripe.

<img width="893" alt="image" src="https://github.com/django/djangoproject.com/assets/49204469/8c5f321a-c1e5-4829-a38f-1d170b072dea">
<img width="918" alt="image" src="https://github.com/django/djangoproject.com/assets/49204469/cedf85f4-9244-49d7-b740-98b7325b0b68">

Seems to be Stripe issue with reCAPTCHA though:

<img width="651" alt="image" src="https://github.com/django/djangoproject.com/assets/49204469/62cd9366-755e-4f8c-9249-83a9bd9a6910">

**Comment by CuriousLearner** [comment]
I tried it on macOS Ventura on Chrome & Safari, along with on an iPhone, but couldn't reproduce this. I'll try it after updating macOS, but can you try to use an incognito window/ clear up the cache of your browser?

**Comment by nemecek-filip** [comment]
Just tried it in private window in Firefox and it worked on the first try. When I was submitting the issue I knew it was probably quite rare but since donations are quite important I thought it made sense to raise the issue :-)
