### ISSUE TITLE
bulk_create example code provided seems to go into infinite loop

### ISSUE THREAD

**Issue by blokeish** [django/djangoproject.com#1449]
The code provide [here](https://docs.djangoproject.com/en/5.0/ref/models/querysets/#bulk-create) seems to go into an infinite loop. The _batch_ list variable seems to always get the first 100 items from _objs_ list, so the batch list will never go empty.

```
from itertools import islice

batch_size = 100
objs = (Entry(headline="Test %s" % i) for i in range(1000))
while True:
    batch = list(islice(objs, batch_size)) # <--- this always seems to be yielding the same single first batch.
    if not batch:
        break
    Entry.objects.bulk_create(batch, batch_size) 
```
I have seen this had got carried over to stack over flow. I am relatively new to Python and Django, so, sorry if I am making a stupid entry.

**Comment by lachlantownshend** [comment]
Make sure that the `objs = (Entry(headline="Test %s" % i) for i in range(1000))` line is making a tuple rather than a list. If using a list it won't progress the iterator and will loop infinitely

**Comment by felixxm** [comment]
This is the issue tracker for the djangoproject.com website. Please see [TicketClosingReasons/UseSupportChannels](https://code.djangoproject.com/wiki/TicketClosingReasons/UseSupportChannels) for ways to get help with Django usage.
