### ISSUE TITLE
Site version picker rendering link text as tuples with identical `href` attributes; stuck on 5.0 without URL changes

### ISSUE THREAD

**Issue by trojjer** [django/djangoproject.com#1459]
I've never seen an issue with the Django docs site version picker before, but nothing is reachable besides 5.0 without manually changing the URL.

I think I've found a potential candidate, involving the templatetag: https://github.com/django/djangoproject.com/commit/7596a1ffa861702948a30ec3fb27d686bdb47209#r136155462

@felixxm Hi, sorry to tag you if I'm wrong, but it's the only recent change that seems relevant :)

Reproduced on Safari to validate my theory.

**Comment by felixxm** [comment]
#1460
