### ISSUE TITLE
./manage.py update_docs_and_index failing

### ISSUE THREAD

**Issue by czue** [django/djangoproject.com#1504]
I'm trying to set up my development environment following the instructions in the README. When I run `./manage.py update_docs_and_index` I get the following error:

```
Sphinx version error:
The sphinxcontrib.applehelp extension used by this project needs at least Sphinx v5.0; it therefore cannot be built with this version.
sphinx-build returned an error (release fr/5.0, builder json)
```

This appears to step from the `Sphinx==4.5.0` requirement. I tried [pinning Sphinx to 5.0.2 and it works](https://github.com/sphinx-doc/sphinx/issues/11890#issuecomment-1916491145), but I'm not sure that introduces any breaking changes to the built output.

**Comment by czue** [comment]
After this command failed I wasn't able to run it again without this change: https://github.com/django/djangoproject.com/pull/1507

**Comment by ulgens** [comment]
This looks like can be closed thanks to https://github.com/django/djangoproject.com/pull/1519

**Comment by czue** [comment]
Thanks
