### ISSUE TITLE
aiomysql usage issue with Django

### ISSUE THREAD

**Issue by owais142002** [django/djangoproject.com#1510]
I am getting same problem as stated in this URL: https://stackoverflow.com/questions/78165096/flask-with-aiomysql-runtime-error-event-loop-closed
Only thing is changed is that I am using Django. First request works perfectly fine but after that I am getting Event loop closed. What should I do? I cant find anything helping at this point and is stuck from last month.

**Comment by bmispelon** [comment]
Hi,

Sorry to hear you're having issues.
This github issue tracker is for bugs on the Django website itself. Please see the documentation on where to get help using Django (email list, forum, discord, ...): https://docs.djangoproject.com/en/5.0/faq/help/#how-do-i-do-x-why-doesn-t-y-work-where-can-i-go-to-get-help


Have a nice day!
