### ISSUE TITLE
Site performance issues/outages

### ISSUE THREAD

**Issue by c3pmark** [django/djangoproject.com#1516]
When I try to access djangoproject.com, I sometimes get timeouts or Varnish errors. An example from today is

```
Error 503 first byte timeout

first byte timeout
Error 54113

Details: cache-yvr1524-YVR 1712690329 2287605865
```

Typically when this happens, I will get errors on most page loads for a period of minutes to hours.  I haven't kept careful track of how frequently this happens, but it feels like I run into it maybe every 4-6 weeks?

Is this a known issue with the site?  As an experienced Python developer and ops engineer, is there something I can do to help troubleshoot this or otherwise contribute towards improving the site's uptime?

**Comment by efstone** [comment]
Yeah, same here. Found some dead links...

- https://docs.djangoproject.com/en/dev/internals/contributing/bugs-and-features/
- https://docs.djangoproject.com/en/5.0/search/

And something similar to the original issue post:

`Error 503 first byte timeout`

`first byte timeout`
`Error 54113`

`Details: cache-cmh1290062-CMH 1712697682 2723352570`

`Varnish cache server`

**Comment by bmispelon** [comment]
Hi and thanks for the report!

We have been experiencing a lot of timeouts recently but it's been tricky to track down exactly what's causing them. The ops team has been working on getting some tools set up to be able to investigate the source of the performance problems.

Meanwhile, if you need to access the documentation and the site isn't cooperating you can use the mirror at Read the Docs: https://django.readthedocs.io/en/stable/ (it's not as pretty, but the content should be up to date).

**Comment by bmispelon** [comment]
While we still experience outages for which we haven't fully tracked down the source, we now have a more robust alert system so we're able to react faster to the site being down.

As such, I'm going to close this for now. Please reopen or comment if you still experience issues with the site.

Thanks! ✨
