### ISSUE TITLE
Typo in href in the template?

### ISSUE THREAD

**Issue by nakib103** [django/djangoproject.com#1520]
https://github.com/consideratecode/django-tutorial-step-by-step/issues/3

It seems there is a typo in the step-by-step tutorial. In the [template](https://github.com/consideratecode/django-tutorial-step-by-step/issues/3) for polls index page the link for the details page uses link - `polls/{{ question.id }}/` containing an extra `polls`. It should be only `{{ question.id }}/`.

**Comment by bmispelon** [comment]
Hi,

Thanks for the report, but  this issue tracker is for the djangoproject.com website itself. The tutorial you're referencing is not affiliated with us.
