### ISSUE TITLE
Request to Add "Python Niger Community Launch" Event to Local Django Communities List

### ISSUE THREAD

**Issue by HamaBarhamou** [django/djangoproject.com#1522]
Dear Django Community,

I hope this message finds you well.

I would like to request the addition of our upcoming event, the "Python Niger Community Launch," to the Local Django Communities list on the Django [website](https://www.djangoproject.com/community/local/).

Event Details:
- Event Name: Python Niger Community Launch
- Date: April 28, 2024
- Time: 9:00 AM
- Location: UDDM de Maradi, Niger
- Contact: contact@pythonniger.org, django@pythonniger.org
- Event Website: [link](https://docs.google.com/forms/d/e/1FAIpQLSdP-5X6OuywQldIIRuj9_V6-zDJZZb73jUHx2_fCS05OjDhPA/viewform)

Partners and Sponsors:
1. Python Software Foundation (PSF)
2. Django
3. Salim Transport
4. UDDM
5. E-E Solutions
6. Inovatech
7. Digital Niger

This event aims to celebrate innovation and foster a collaborative and dynamic technological community centered around Python in Niger. We believe that listing our event on the Django website will help raise awareness and encourage participation from Django enthusiasts and developers in our region.

Thank you for considering our request. Please let me know if there are any additional steps we need to take or if you require further information.

Best regards,

ISSAKA HAMA Barhamou

**Comment by sabderemane** [comment]
Hi @HamaBarhamou 👋🏽 
I have replied to your forum post and send you a message in Discord to get additional informations before to proceed :)

**Comment by HamaBarhamou** [comment]
> Hi @HamaBarhamou 👋🏽 I have replied to your forum post and send you a message in Discord to get additional informations before to proceed :)

que pense tu de cette version:

> The Python Niger community is dedicated to all Python enthusiasts in Niger! Our team is organizing a series of exciting events, including PyCon Niger, Django Girls, and many more to come. Stay connected with us through our LinkedIn pages: [LinkedIn page 1](https://www.linkedin.com/company/103446000/admin/feed/posts/) or [LinkedIn page 2](https://www.linkedin.com/company/103440505/admin/feed/posts/). You can also contact us via email at: django@pythonniger.org; contact@pythonniger.org or by phone at +227 97557852 or +227 97984333. Join us in this exciting adventure!
