### ISSUE TITLE
Dashboard doesn't work

### ISSUE THREAD

**Issue by felixxm** [django/djangoproject.com#1525]
https://dashboard.djangoproject.com/ no longer updates stats:

![image](https://github.com/django/djangoproject.com/assets/2865885/2abe5399-5cfd-449e-8929-7dfe11f7a131)

**Comment by bmispelon** [comment]
Running `./manage.py update_metrics` locally results in `xmlrpc.client.ProtocolError: <ProtocolError for code.djangoproject.com/rpc: 429 Too Many Requests>` so I believe it has to do with the anti-spam measure that were deployed last week.

This would probably be fixed by #1479

**Comment by felixxm** [comment]
> This would probably be fixed by #1479

Thanks, let me review it :detective:

**Comment by felixxm** [comment]
It seems that it doesn't work again :disappointed: 

![image](https://github.com/django/djangoproject.com/assets/2865885/d78e70e3-49ce-491e-a640-ee4983819665)

**Comment by bmispelon** [comment]
Thanks for the report! This must be related to the Django update, I'll look into it. 👀

**Comment by bmispelon** [comment]
It was indeed the Django update. Turns out our cron jobs were using `django-admin.py` which was removed in favor of `django-admin` (in 4.0 actually).

Thanks again for the heads up 🚀
