### ISSUE TITLE
.save() is not working

### ISSUE THREAD

**Issue by dinesh1299** [django/djangoproject.com#1536]
my_query = Model.objects.using('dbname').filter(ref_id=self.utils.my_ref_id)
my_query_first = my_query.first()
my_query_first.last_updated = self.utils.date_obj1.replace(tzinfo=tzlocal()) - timedelta(days=1)
my_query_first.save(using='dbname')

I couldn't able to update the value of first in queryset

**Comment by bmispelon** [comment]
Hi,

This issue tracker is for problems with the Django website itself. To get help with using Django, please use the support channels (forum, discord, ...) linked on that page: https://www.djangoproject.com/community/

Have a nice day 🌞
