### ISSUE TITLE
Why doesn't `manage.py startapp` give us an option to automatically add the app to `INSTALLED_APPS`?

### ISSUE THREAD

**Issue by nbro** [django/djangoproject.com#1539]
I've just run `python manage.py startapp --help` and I've not found an option to automatically add our newly created app to `INSTALLED_APPS`, which is very surprising to me, because, clearly, in many if not most cases, we want to do this operation immediately after running the `startapp` command.

So, why isn't there a flag that allows us to do this automatically? Why should we always have to manually do this?

I'm using Django 5.0.6.

Feel free to move this issue to another more suitable repository.

**Comment by bmispelon** [comment]
Hi,

Django uses a different system for bugs/feature requests. This repository is only for issues with the website itself.

Please see this page for how to report issues to Django: https://docs.djangoproject.com/en/dev/internals/contributing/bugs-and-features/#reporting-bugs

Have a nice day

**Comment by nbro** [comment]
@bmispelon This is not a feature request. It's a question about `manage.py startapp`, who answer could actually be on the website. Eventually, I could also request this feature, but I'd like to first understand why this doesn't exist.

**Comment by bmispelon** [comment]
I see, either way this repository is for issues with the website itself, not with Django or its documentation.

See the FAQ https://docs.djangoproject.com/en/5.0/faq/help/#how-do-i-do-x-why-doesn-t-y-work-where-can-i-go-to-get-help for where you can ask these questions.
