### ISSUE TITLE
Template tags made available by context processors

### ISSUE THREAD

**Issue by plktagrawal** [django/djangoproject.com#1552]
On this link we can see the template tags available by default in Django:
https://docs.djangoproject.com/en/5.0/ref/templates/builtins/

The above page should also highlight that some other tags (such as {{ user }} ) are also made available by default context processors. This information is currently buried at the following location:
https://docs.djangoproject.com/en/5.0/ref/templates/api/#built-in-template-context-processors

This would provide a holistic picture in my opinion. The {{user}} tag for instance is used in some of the examples in the documentation. A user tends to search built in tags for more information but finds nothing on that location regarding this tag.

Hope this is a useful suggestion.

**Comment by bmispelon** [comment]
Hi,

Thanks for the suggestion, but this issue tracker is for bugs and improvements for the website itself, not for the content of the documentation. Please see this page for how to report an issue against the content of the documentation: https://docs.djangoproject.com/en/dev/internals/contributing/bugs-and-features/

Have a nice day 🌞
