### ISSUE TITLE
[Bug] Validate Azure access token in Django Rest API and call graph API

### ISSUE THREAD

**Issue by shreyanshjain1605** [django/djangoproject.com#1564]
Hello Team,

Form Angular application using MSAL, I login to azure and receive accessToken. Now to pull data from API I am passing access token as bearer in header of API.
Now please let me know how I can validate/authorize this token in backend Django rest api.

Do we have any in built function or module that I need to install and validate?
If not please let me know how I can validate/authorize my token and call graph api to get additional information of user.

**Comment by bmispelon** [comment]
Hi,

This issue tracker is for the djangoproject.com website. For getting help with how to use Django, try the forum, the discord channel, or the mailing list: https://docs.djangoproject.com/en/dev/faq/help/#how-do-i-do-x-why-doesn-t-y-work-where-can-i-go-to-get-help

Have a nice day ✨
