### ISSUE TITLE
RSS feeds should only include items from approved feeds

### ISSUE THREAD

**Issue by bmispelon** [django/djangoproject.com#1573]
As reported in https://github.com/django/djangoproject.com/issues/1299#issuecomment-2198751205, the RSS feeds (that is to say, the actual XML files) for the feeds on the [community page](https://www.djangoproject.com/community/) (blog posts, jobs, packages, ...) include items for feeds that are not approved.

When listing items on the site (for example https://www.djangoproject.com/community/packages/), such items will be correctly excluded.

The RSS feeds (in `aggregator/feeds.py`) should be modified to also exclude un-approved feeds (and some tests should be added as well).

**Comment by bmispelon** [comment]
@medmunds I've just deployed this change and the spam in the "new packages" feed should be gone now. Thanks again for pointing it out 👍🏻

**Comment by medmunds** [comment]
Much better. (I mean, still seven years out of date, but no more spam! 😄 )
