### ISSUE TITLE
Problem updating babel dependency

### ISSUE THREAD

**Issue by bmispelon** [django/djangoproject.com#1597]
Looks like the migration check breaks when updating `babel`: https://github.com/django/djangoproject.com/pull/1593

I haven't had time to investigate, but it seems that upgrading `babel` triggers some changes in some models in the `foundation` app (from the CI failure in the PR linked above):
```
 Migrations for 'foundation':
  foundation/migrations/0005_alter_approvedgrant_amount_currency_and_more.py
    - Alter field amount_currency on approvedgrant
    - Alter field treasurer_balance_currency on meeting
 ```

We have a check that triggers a failure when such changes happen, which is why the PR has a red mark.

I don't have time to look at it right now, so if anyone wants to dig into the issue, they are most welcome.

**Comment by RajuShivarama** [comment]
Hi sir, please assign this issue to me
