### ISSUE TITLE
How to use custom headers for passing session_id and csrf_token in Django with database-backed sessions?

### ISSUE THREAD

**Issue by hitesh-scanova** [django/djangoproject.com#1626]
I'm using Django with a database-backed session storage, and as a result, the `session_id` is stored in cookies. However, we're using a Caddy server that removes cookies from the request headers.

I need to:

1. Pass the `session_id` and `csrf_token` via custom headers (instead of cookies).
2. Use these custom headers for session validation and CSRF protection in Django.

Additionally, I am storing values in the session that are used to validate the request and fetch data from the session during API calls.

Is it possible to configure Django to accept and validate these custom headers (`session_id` and `csrf_token`) rather than reading them from cookies? If so, how can this be achieved?

Any advice or code examples would be much appreciated.

Django database django_session table:-
![Screenshot 2024-09-24 at 2 01 54 PM](https://github.com/user-attachments/assets/67b02641-d92e-4e75-bc3f-a05779413ba3)

Request headers:-
![Screenshot 2024-09-24 at 2 02 19 PM](https://github.com/user-attachments/assets/cace97d4-a155-45bb-9e4e-41d1b15243c7)

**Comment by bmispelon** [comment]
Hi,

This issue tracker is for the Django website, not Django itself. Please see the links at https://docs.djangoproject.com/en/5.1/faq/help/#how-do-i-do-x-why-doesn-t-y-work-where-can-i-go-to-get-help for where you can get help with your Django questions.

Have a nice day 🌞
