### ISSUE TITLE
Search highligt is not working online in some circumstances

### ISSUE THREAD

**Issue by pauloxnet** [django/djangoproject.com#1629]
Searching highlights is not working online for some words:
- https://docs.djangoproject.com/en/5.1/search/?q=Triaging

![Screen Shot 2024-09-26 at 14 48 45](https://github.com/user-attachments/assets/7be80add-db5f-47b2-bda6-049c0cf80992)

It works for other search terms:
- https://docs.djangoproject.com/en/5.1/search/?q=text

![Screen Shot 2024-09-26 at 14 49 17](https://github.com/user-attachments/assets/b9af38f4-e664-4f7e-ae81-50d8b44f2890)

It's working in both case locally as tested by @bmispelon with PostgreSQL 16.

Remotely the website is using PostgreSQL 14.

**Comment by bmispelon** [comment]
@t-payne tried with a postgres 14 (docker) and the highlighting work, so it's not a version issue. I will keep digging ⛏️
