### ISSUE TITLE
URL's in Django and it's rest framework

### ISSUE THREAD

**Issue by ivose** [django/djangoproject.com#1635]
It might be worth considering an improvement to the Django framework. Currently, Django REST Framework treats URLs with and without a trailing slash differently. For example:

- http://localhost:8000/posts/6
- http://localhost:8000/posts/6/

These two URLs lead to different results, which can cause inconsistencies. It’s crucial that both versions of a URL, with and without the trailing slash, behave the same way. In comparison, PHP's Laravel framework doesn't face this issue—its URL handling system is more flexible in this regard. Addressing this in Django could streamline development and reduce potential confusion.

**Comment by bmispelon** [comment]
Hi,

This ticket tracker is for the development of the djangoproject website itself, not Django. I think your question might be better suited for [the forum](https://forum.djangoproject.com/c/internals/5).

Have a nice day! 🌞
