### ISSUE TITLE
Drop support for Python 3.8

### ISSUE THREAD

**Issue by tobiasmcnulty** [django/djangoproject.com#1644]
Since adding Python 3.12 and dropping Python 3.8 support are being handled separately, I'm creating a new issue for dropping Python 3.8 support.

@bmispelon in #1574:
> Some of our dependencies have started dropping support for Python 3.8 (the one we're currently running in production).

> I don't think there's much to be done in this project's codebase (this is mostly an ops issue), but I wanted to have an issue where I can track which dependencies are being affected:

- [ ] `docutils` (+ `Sphinx`): #1571
- [ ] `pre-commit`: #1568
- [ ] `watchdog`: #1617

Other to dos:
- [ ] Update the `pyupgrade` repo in `.pre-commit-config.yaml` to target `--py312-plus`

**Comment by pauloxnet** [comment]
What do you think it's the best way to drop Python 3.8 and start using Python 3.12 in production?

**Comment by pauloxnet** [comment]
In the meantime Python 3.8 is now officially EOL 👇
https://discuss.python.org/t/python-3-8-is-now-officially-eol/66983
