### ISSUE TITLE
Check if code highlighting theme matches styleguide

### ISSUE THREAD

**Issue by jezdez** [django/djangoproject.com#165]
The code highlights on the start page seem to be a bit oddly colored, I wonder if that shouldn't be using a different Pygments theme?

**Comment by faizan842** [comment]
can I work on it?

**Comment by rixx** [comment]
I don't think we have code highlights anywhere on the start page anymore; looks like we can just close this issue?

**Comment by carltongibson** [comment]
Indeed. 

And the docs' choice of highlighter seems OK. 

E.g. https://docs.djangoproject.com/en/4.1/intro/tutorial01/

Let's close.
