### ISSUE TITLE
Outdated text in templates

### ISSUE THREAD

**Issue by bmispelon** [django/djangoproject.com#1665]
While working on translating the website, Mark found a few outdated templates that could use some updating:

1) https://github.com/django/djangoproject.com/blob/main/djangoproject/templates/accounts/user_profile.html#L29

Suggested wording:
> If you see outrageous errors, please file an issue on GitHub (link to https://github.com/django/code.djangoproject.com/issues/new)
---

2) https://github.com/django/djangoproject.com/blob/main/djangoproject/templates/aggregator/delete-confirm.html#L9-L10

Suggested wording:
> We haven't implemented an undo feature yet, so all items will be deleted immediately.

**Comment by bmispelon** [comment]
@marksweb Not sure why, but I can't seem to assign you to this issue so I'm pinging you instead

**Comment by sabderemane** [comment]
> @marksweb Not sure why, but I can't seem to assign you to this issue so I'm pinging you instead

@bmispelon I think it's because only members can be assigned
