### ISSUE TITLE
:pencil: Add Markdown support to Blog Entry

### ISSUE THREAD

**Issue by jefftriplett** [django/djangoproject.com#1675]
This came up during @jacobian's office hours today, and it's one that bugged me for a while, too. 

Our Blog Entry module supports reStructuredText and html, but not Markdown which is universally used in most writing platforms. 

![Screenshot 2024-10-16 at 4 34 04 PM](https://github.com/user-attachments/assets/fa1e332d-e612-4662-9d87-6a019ccbf3e3)

I know picking a Markdown library to support is a whole mailing list or forum topic, but I'm happy with **any** library, which means we get the basic subset of Markdown.

**Comment by bmispelon** [comment]
There you go @jefftriplett https://github.com/django/djangoproject.com/pull/1678
