### ISSUE TITLE
Remove reference to Django core team

### ISSUE THREAD

**Issue by bmispelon** [django/djangoproject.com#1686]
While reviewing #1672 I noticed that there was a page still referencing the Django core team: https://github.com/django/djangoproject.com/blob/d786988b9a64185c71582ffc26c946ea084fe3bf/djangoproject/templates/conduct/changes.html#L18

The Django core team was dissolved a while back, so the text of this page and any others (`git grep -i "core team"` seems to yield other files too) should be updated.

**Comment by ontowhee** [comment]
Running the grep command above returned the following:

```
djangoproject/templates/conduct/changes.html:    sent to the DSF, the Django core team, and the Django community for comment.
djangoproject/templates/conduct/changes.html:      a core dev vote</a> for the core team).
djangoproject/templates/diversity/changes.html:    sent to the DSF, the Django core team, and the Django community for comment.
djangoproject/templates/diversity/changes.html:      a core dev vote</a> for the core team).
djangoproject/templates/foundation/coreawardcohort_list.html:{% block og_description %}{% translate "Former Django Core Team dissolved on March 12, 2020." %}{% endblock %}
```
Looks like the only valid line is the one in `coreawardcohort_list.html`. I also looked at `diversity/changes.html` and `conduct/changes.html`, and the content look similar between those two files.

Is there a phrase that should be used to replace of "core team", or should "core team" be removed? I'm happy to make these changes, if that helps.

**Comment by thibaudcolas** [comment]
Thank you both for reporting and investigating! Historical mentions are fine. For the two _sent to the DSF, the Django core team,_, I would recommend removing the "the Django core team" mentions. The alternative would be to switch to the Steering Council but it’s not their prerogative to review code of conduct changes.

For further context on the rationale for the rewriting, see [DEP PR #95](https://github.com/django/deps/pull/95), and linked other PRs updating the DEPs terminology.
