### ISSUE TITLE
Upgrade to psycopg 3

### ISSUE THREAD

**Issue by pauloxnet** [django/djangoproject.com#1714]
Since Django 4.2 has been added the support for Psycopg 3 (https://docs.djangoproject.com/en/4.2/releases/4.2/#psycopg-3-support).

> Support for psycopg2 is likely to be deprecated and removed at some point in the future.

So we want to upgrade from `psycopg2` to `psycopg` version 3.

**Comment by bmispelon** [comment]
Hi and thanks for opening this!

Could you expand on what the benefits of upgrading/switching to `psycopg` would be? The release notes mentions the possibility of `psycopg2` being deprecated, but that hasn't happened yet, has it? Is there a performance benefit in switching, or some code simplifications that could be enabled on our end?

The release notes also mention that there might be some backwards incompatibilities between `psycopg2` and `psycopg`: https://www.psycopg.org/psycopg3/docs/basic/from_pg2.html. Have you looked into those? If so, can you share the steps you took to verify the compatibility (that would help with reviewing the PR).

Thanks! ✨

**Comment by marksweb** [comment]
@bmispelon This is a simple table comparison;

https://www.geeksforgeeks.org/comparing-psycopg2-vs-psycopg-in-python/

On the whole it's a case of having more modern support, for newer postgres features and async.

So the benefit comes really from running modern postgres and making use of those things. Which we might not do. But equally I don't think there's any detriment in running the newer version

**Comment by pauloxnet** [comment]
> Could you expand on what the benefits of upgrading/switching to `psycopg` would be? The release notes mentions the possibility of `psycopg2` being deprecated, but that hasn't happened yet, has it? Is there a performance benefit in switching, or some code simplifications that could be enabled on our end?

`Psycopg` 3 is the new asynchronous rewrite of `Pyscopg2`, which contains all the performance and security improvements, which are not released in `psycopg2`.

`Psycopg2` may not be updated at all, or be deprecated in the next Django release, and we don't know when, and in that case we should hurry up and do a migration.

My question is rather why keep the dependency with a version of a package that we already know will be deprecated when Django already supports the new version well?
 
> The release notes also mention that there might be some backwards incompatibilities between `psycopg2` and `psycopg`: https://www.psycopg.org/psycopg3/docs/basic/from_pg2.html. Have you looked into those? If so, can you share the steps you took to verify the compatibility (that would help with reviewing the PR).

All these points have already been taken into account in the PR that added support for `psycopg` 3 in the Django ORM.

I have tested `psycopg` 3 locally, and in tests.

Also, I have already done this migration in many projects without problems.

**Comment by bmispelon** [comment]
Thanks for both explanations, that gives me more confidence that deploying this won't break the site 😅 

Could we have an update for code.djangoproject.com also?

**Comment by pauloxnet** [comment]
> Thanks for both explanations, that gives me more confidence that deploying this won't break the site 😅
> 
> Could we have an update for code.djangoproject.com also?

Done!

https://github.com/django/code.djangoproject.com/pull/223
