### ISSUE TITLE
Unable to find Django Nigeria Local Community

### ISSUE THREAD

**Issue by doctorpentagon** [django/djangoproject.com#1728]
### Name

Unable to find Django Nigeria Local Community

### Description

Unable to find Django Nigeria  Social Group for local community  events, learning and Meetup. Nigeria is very large and big with millions of population and thousands of Django users. I will be very happy If I can find a local community or be able to create one for like minds and passionate individuals willing to contribute

### City

Ilorin

### Country

Nigeria

### Event or website URL

N/A

**Comment by thibaudcolas** [comment]
@doctorpentagon thank you for raising this! I’ve reached out to a few people, we’ll see if they have any to recommend.

**Comment by doctorpentagon** [comment]
Okay, I am always ready to contribute greatly to this and be part of the
team for this, I have experience and am passionate about community and
social impact, I would be happy to take part of the Django Nigeria
community, hence, my communication...


Here is my profile to check:
https://www.linkedin.com/in/wahab-kehinde-idris-747038234?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app

**Comment by thibaudcolas** [comment]
hi @doctorpentagon, I’ve heard back from some of the people I contacted, and we have someone else asking the same thing in #1743. Unfortunately there doesn’t seem to be any Django-specific event / user group / community in Nigeria at this time.

Having said that – the wider Python and open source community is strong there :) I would recommend the following two local groups (which you might already be aware of):

- [Python Nigeria](https://www.pynigeria.org/). I’m sure there are people who do web development / Django there.
- [Open Source Community Africa (OSCA)](https://oscafrica.org/). This is for all of Africa but there are a lot of local chapters all around Nigeria in particular.

I hope this helps. For now we will close this issue as there isn’t an obvious existing group for us to link to from our community page.
