### ISSUE TITLE
Community Request - South Africa

### ISSUE THREAD

**Issue by koketsomotse** [django/djangoproject.com#1733]
### Name
  Koketso Motse

### Description
  Looking for support to start Django community in South Africa

### City
  Johannesburg, Gauteng

### Country
  South Africa

**Comment by sabderemane** [comment]
Hi @koketsomotse, this form is to add an existing community which is not the case as I understand with the description. 

What I can suggest to start a community is:
- post on the [Django forum](https://forum.djangoproject.com/c/events/12) to find people to help you
- [contact team of PyCon ZA](https://za.pycon.org/about/contact-us/) that could help you or connect with people who could help
- join [black python devs discord](https://discord.gg/yed8Hj3U) if you're not there and ask for people who would like to help 
- ask on Mastodon/X/LinkedIn if people could help you

I hope this helps
