### ISSUE TITLE
Django community Nigeria

### ISSUE THREAD

**Issue by Josephchinedu** [django/djangoproject.com#1743]
### Name

Django community Nigeria

### Description

 Please, I want to make enquiry if there's a Django community in Nigeria, 
  And can I start one if there's none.

### City

Lagos, Nigeria

**Comment by thibaudcolas** [comment]
Hi @Josephchinedu, see #1728 :) I’ll close this new issue as a duplicate.

@sabderemane might be worth us changing the wording on the page, to encourage people to also search within existing issues? Maybe use a specific issue label so we can make it easier to do that, creating a link to all current and past requests?
