### ISSUE TITLE
Broken "Download latest release" label in home page

### ISSUE THREAD

**Issue by pauloxnet** [django/djangoproject.com#1747]
The label of the download button of the latest Django release on the home page is broken.
![Screenshot 2024-11-18 at 13-08-58 The web framework for perfectionists with deadlines Django](https://github.com/user-attachments/assets/0a0ad3d8-ad39-438c-8f50-0da192c0c316)

In the latest commit, I think the translation opening for that text was missing or a translation block, given the presence of HTML tags.

- https://github.com/django/djangoproject.com/commit/9997c224b2961790ff84d1036809efbe3a151b1e#diff-2932f838a52df1042af7848648637ca0bc5ce85b820f010885d0c9b91aeaf33dL113

**Comment by bmispelon** [comment]
Good catch, thanks. Working on a fix now.

**Comment by bmispelon** [comment]
The change should be live (caching might make it take a few minutes to propagate).

Thanks Paolo and Pat (on Discord) for reporting this 👍🏻
