### ISSUE TITLE
Stripe event handling doesn't verify the source

### ISSUE THREAD

**Issue by alexgmin** [django/djangoproject.com#1765]
https://github.com/django/djangoproject.com/blob/5537f965ece29b766efe17c1d2137c3d2037811c/fundraising/views.py#L196-L201
Instead of calling Stripe with the event id it should verify the source of the event and prevent replay attacks as indicated here
https://docs.stripe.com/webhooks#verify-events

The Stripe library already has a method to do this https://docs.stripe.com/webhooks?lang=python#verify-webhook-signatures-with-official-libraries

**Comment by bmispelon** [comment]
@alexgmin I've opened a PR for this: #1770

Does that seem ok to you?

**Comment by bmispelon** [comment]
The stripe webhook started failing in production, so I had to revert while I figure out what I did wrong 🕵🏻‍♂️
