### ISSUE TITLE
Django Italy (English)

### ISSUE THREAD

**Issue by Binotali** [django/djangoproject.com#1785]
Django Italy (English)

### Description

Django Italy (English) English speaking Italian community for python programmer and web development 

### Savona 

Savona Cairo montenotte

**Comment by sabderemane** [comment]
Hello @Binotali, is Django Italy a community which exist in Savona or not at all? We need more information including a link to redirect to make the addition on the website.

**Comment by thibaudcolas** [comment]
👋 it’s been three weeks with no further info coming in, and I personally can’t find anything that seems like a match for "Django Italy", "Django Savona". or "Django Cairo montenotte". I’ll close this for now, we can re-open if more information emerges.
