### ISSUE TITLE
Improve the copy for the failed payment email

### ISSUE THREAD

**Issue by nanorepublica** [django/djangoproject.com#1790]
The failed payment email [here](https://github.com/django/djangoproject.com/blob/main/djangoproject/templates/fundraising/email/payment_failed.txt) is not accurate in what actually happens with a failed payment. I would suggest it be updated to the following copy:

```
{% load i18n %}{% spaceless %}{% url 'fundraising:manage-donations' donation.donor.pk as manage_url %}
{% blocktranslate with name=donation.donor.name_with_fallback %}
Hi {{ name }},

This is to let you know that payment for your recurring donation to the Django Software Foundation has failed.
This might be because your payment card has expired or you don't have enough funds

Please check your bank balance or go to {{ manage_url }} to add a new card. We will try to take payment again in 3 days.

Thanks very much for your support.

Regards,
Django Software Foundation
{% endblocktranslate %}
{% endspaceless %}
```

**Comment by bmispelon** [comment]
The proposed change seems like an improvement 👍🏻 

If anyone would like to try their hand at submitting a pull request for this, I'd be happy to review it.

Thanks for filing the issue! ✨

**Comment by Adityaupadhye** [comment]
@bmispelon I would like to try out this issue.

**Comment by bmispelon** [comment]
> @bmispelon I would like to try out this issue.

Excellent, thanks! The next thing to do would be to open a pull request with the changes proposed by `nanorepublica` above. Once you've done that, you can request a review by me and I'll take a look at it. 🔎

**Comment by Adityaupadhye** [comment]
Hello @bmispelon 
Please have a look at PR #1795
