### ISSUE TITLE
Figure out stylesheet sharing with Trac repo

### ISSUE THREAD

**Issue by jezdez** [django/djangoproject.com#187]
Right now we have to copy CSS files over to the code.djangoproject.com repo and that sucks.

We could merge the other repo into this djangoproject.com repo since it would centralize everything, docs, trac and the www code. Then in the deploy script we could create symlinks to the static root of the www site to be used by the trac instance.

@aaugustin I think you worked on Trac last in any bigger capacity, do you remember why the Trac repo is split apart from this repo?

**Comment by timgraham** [comment]
I guess the status quo is fine. There aren't many changes that need to be synced.
