### ISSUE TITLE
trac comments can be hard to read

### ISSUE THREAD

**Issue by prestontimmons** [django/djangoproject.com#191]
I find the trac comments difficult to read in the new design. I think this could be improved with some small changes. Here are my suggestions:

1) Can the reply/edit buttons be reduced in size?  They feel really obtrusive for long discussions.

2) Block quotes render at 2.8rem. I think they should be the same font size as normal text.

3) The trac css uses ``div[role="main"] #main {sans-serif !important}`` for the body font. Is the font stack overwritten on purpose?

4) Is the big sidebar necessary on ticket pages? I think it makes the discussion feel smashed.

Here's a rough before-and-after of what I mean:

### Before

![screenshot 2014-12-16 11 47 34](https://cloud.githubusercontent.com/assets/207051/5458624/7e52d782-8519-11e4-80dc-f21068279ca6.png)

### After

![screenshot 2014-12-16 12 13 57](https://cloud.githubusercontent.com/assets/207051/5458998/a3e1aab6-851c-11e4-9d9a-b5d9e209abc7.png)

**Comment by timgraham** [comment]
Preston's PR has been merged.
