### ISSUE TITLE
On large screens there is an unsightly rectangle

### ISSUE THREAD

**Issue by epicserve** [django/djangoproject.com#193]
Here is a screenshot.

![the web framework for perfectionists with deadlines django 2014-12-16 12-37-36](https://cloud.githubusercontent.com/assets/191620/5459429/7f80af9c-8520-11e4-858f-680efbe84c4f.jpg)

**Comment by epicserve** [comment]
Has this been deployed yet? I'm still seeing the rectangle. I've cleared my case and refreshed the page.

**Comment by jezdez** [comment]
@epicserve Yeah, but the cache may be still going, it's cached for 60 mins.

**Comment by epicserve** [comment]
Just checked, it's not there now! Good job everyone!
