### ISSUE TITLE
Sidebar is too wide

### ISSUE THREAD

**Issue by berkerpeksag** [django/djangoproject.com#205]
Perhaps limiting sidebar's width to Django logo would be better. I added a marker via devtools:

![django](https://cloud.githubusercontent.com/assets/26338/5464000/066c832c-858b-11e4-91c5-0f22a8c60daa.png)

**Comment by jezdez** [comment]
Is this still an issue @berkerpeksag now that we've moved the sidebar to the right side?

**Comment by berkerpeksag** [comment]
Looks great, thanks @jezdez :)
