### ISSUE TITLE
Move foundation flatpages as static templates

### ISSUE THREAD

**Issue by olasitarska** [django/djangoproject.com#207]
This way everyone can contribute to them by sending a pull request and it's easier to redesign them next time :)

**Comment by jezdez** [comment]
So I was wondering if we could use my good old [django-dbtemplates](https://github.com/jezdez/django-dbtemplates) as a compromise. We'd keep the admin interface and ease of deployment but would gain having Django template abilities in the admin -- including fancy syntax highlighted editor. I'd need to update it and do a new release, but that's been on my TODO list anyways. Opinions?

**Comment by freakboy3742** [comment]
If there's no significant performance hit to this, that sounds fine to me. Longer term, transitioning to actual database-backed pages for most of this content would be preferable. I'll make a note to spec out the features for a foundation app.

**Comment by jezdez** [comment]
There wouldn't be performance issues as dbtemplates are heavily cached, but the the recent template changes in 1.8 (that we strive to move to very soon with this code base, #345) make me nervous about adding another yak to the herd to be shaved so to say. Let's do the jump to a proper foundation app instead. I guess #362 is related.

**Comment by timgraham** [comment]
At this point, the status quo seems fine.
