### ISSUE TITLE
Hover effect and grey outline on Trac ticket results makes text hard to read

### ISSUE THREAD

**Issue by mawe42** [django/djangoproject.com#211]
![dj_trac_links](https://cloud.githubusercontent.com/assets/812001/5468991/a208868c-85d6-11e4-90f7-554aea625651.png)

The above image shows the ticket table in Chromium 39.0.2171.95 on Linux, mouse hovering over the first link. It looks slightly better in Firefox, as there is no visible outline on the links, but the contrast is still too low, I think.

Here a comparison of the grey outlines as rendered by Chromium...
![dj_chromium](https://cloud.githubusercontent.com/assets/812001/5469055/57b18286-85d7-11e4-924d-be8952674318.png)

...and Firefox:
![dj_firefox](https://cloud.githubusercontent.com/assets/812001/5469060/63cf877a-85d7-11e4-9261-7e66557c3343.png)

Thanks for your hard work on the new design, overall it looks fantastic and is a huge improvement!

**Comment by mattseymour** [comment]
I think the text-shadow was part of the problem but I also think the color of the text itself needs to be a little darker when the row is being hovered.

**Comment by bmispelon** [comment]
I believe this has been fixed.

Please reopen/comment if that's not the case.

Thanks!
