### ISSUE TITLE
Thanks logos in footer misaligned

### ISSUE THREAD

**Issue by ookami-kb** [django/djangoproject.com#227]
Right thanks logo in footer is cut and both are not aligned with &:
![d](https://cloud.githubusercontent.com/assets/853356/5482756/cc1ebac8-8666-11e4-9002-ca31d31d499d.png)

Chrome 39.0.2171.95 (64-bit), Firefox 34.0
Ubuntu

**Comment by timgraham** [comment]
I guess this issue isn't so important as I imagine all browsers will support SVG sooner or later. Those that don't, can live with some cosmetic imperfections.
