### ISSUE TITLE
Background color

### ISSUE THREAD

**Issue by AcmeProgramming** [django/djangoproject.com#253]
White it just too bright, make it an off white and make the fonts slightly bigger, one or two sizes.

**Comment by AgDude** [comment]
@evildmp I would like to ask that this ticket be reconsidered, or perhaps changed to something like "improve readability". I also had this thought when I first saw the new site, and decided to give it a few weeks. I still find myself squinting every time I open the docs.

Specific to the background, the format of the docs means that there is a lot of white space on the page compared with many sites, 

However, I think this issue could be addressed by changing the font color away from green.  There is a very high contrast ratio between the body text (```#0c3c26```) and the background (ratio of 12.4:1). For example purposes, open dev tools, and change the font color to ```545454``` which is the grey font used by Google, and has a contrast ratio of 7.6:1. I find that this drastically improves the readability.

**Comment by AcmeProgramming** [comment]
How difficult can it possibly be to soften the background color from white to something easier on the eyes?

**Comment by AcmeProgramming** [comment]
In addition, much like AgDude said, there is a lot of wasted real estate on the screen with the text just 'floating around' without being given the sense that it is actually anchored to anything.
