### ISSUE TITLE
Broken footer on Trac pages

### ISSUE THREAD

**Issue by apollo13** [django/djangoproject.com#271]
The footer on trac timeline pages looks currently like this: http://imgur.com/vQkKotO This is due to trac restyling h2 for the timeline headers without scoping the css at all…

**Comment by bmispelon** [comment]
I've open an issue on Trac with a proposed fix: http://trac.edgewall.org/ticket/12048

**Comment by timgraham** [comment]
Closing given the fix was merged to Trac.
