### ISSUE TITLE
Consider concatenating js and images

### ISSUE THREAD

**Issue by apollo13** [django/djangoproject.com#274]
To increase first load times it could help to concatenate the images (http://css-tricks.com/svg-sprites-use-better-icon-fonts/) and js files as well as serving webfont.js from our static dir.

**Comment by jezdez** [comment]
Good idea!

**Comment by jezdez** [comment]
Ok, we've started serving webfont.js locally now.

**Comment by faizan842** [comment]
can I work on it?

**Comment by timgraham** [comment]
Eight years later, I guess we can say this isn't that important.
