### ISSUE TITLE
"About the Django Contributor License Agreement" refers to "Content Licensing Agreement"

### ISSUE THREAD

**Issue by lukegb** [django/djangoproject.com#282]
There's one (and only one) reference to "Content Licensing Agreement" at https://www.djangoproject.com/foundation/cla/faq/, which should probably say "Contributor License Agreement" instead.

Wasn't sure what mailing list this should go to, and I didn't feel like filling out the nebulous Foundation "contact us" form, so here's a ticket instead.

**Comment by freakboy3742** [comment]
Thanks for the report - I've just corrected the text.
