### ISSUE TITLE
Heart progress bar

### ISSUE THREAD

**Issue by olasitarska** [django/djangoproject.com#293]
The idea is that each "pixel" of the heart will light up as the progress goes up. We will have to create a picture of the heart for each step separately or use some magical svg tricks? The second solution is probably better, but I am not entirely sure if possible.

**Comment by treyhunner** [comment]
I had understood this as a fill (similar to a glass filling) [like this](http://jsbin.com/veyijo/1/edit?html,css,output).  "Pixels" lighting up seems better.

IE8 doesn't include SVG support, though I'm not sure whether that matters here.

What if each pixel/block of the heart was an image?  That would require some careful alignment, but then each block could be stacked with CSS and controlled separately.  This would allow a little more flexibility also (e.g. pixels could increase in brightness until they fill in all the way).

**Comment by olasitarska** [comment]
We should probably provide some fallback to IE8 -- like just a static "full" heart, without progress bar on the heart. 

You think this would work with SVG in all other browsers?

**Comment by treyhunner** [comment]
Sorry for the lack of response.  I've been under the weather the last few days and neglected my plans to try out an SVG.

I took a stab at this in #312.  Changing the behavior of the pixels is easy now that they're SVG-ified.
