### ISSUE TITLE
Donation form on fellowship page

### ISSUE THREAD

**Issue by olasitarska** [django/djangoproject.com#294]
In the dropdown of donation amount, you should be able to choose: 
- [ ] 1 Hour (~~$43,75~~ $50)
- [ ] 2 Hours (~~$87,5~~ $100)
- [ ] Half a day of Fellowship program (~~$175~~ $200)
- [ ] Day of Fellowship program (~~$350~~ $400)
- [ ] 3 Days of Fellowship program (~~$1050~~ $1200)
- [ ] Week of Fellowship program (~~$2450~~ $2800)
- [ ] Custom amount (by choosing this, the dropdown should be replaced with input, defaulting to ~~$43,75~~ $50)

This form has work exactly like the form here: https://www.djangoproject.com/foundation/donate/

**Comment by jezdez** [comment]
Hm, couldn't we make those numbers look nicer, like $50 for one hour for example?

**Comment by olasitarska** [comment]
Sure, I don't see a problem with that :)

**Comment by jezdez** [comment]
Cool!
