### ISSUE TITLE
Displaying Django Heros on fellowship page

### ISSUE THREAD

**Issue by olasitarska** [django/djangoproject.com#297]
In default, we should show Heros (=donors) from current week and last week, with simple pagination (next, prev) showing previous donors. Amounts should be disclosed only if someone agreed for that.

Heros should be ordered by amount of money donated and then by date of donation.

If someone donated at least $350 (day worth of Fellowship), we should display their logo (if they provided one), otherwise only a name (of person or organization). If they provided a link, it should be linked. 

All this information will be gathered via #295

**Comment by asendecka** [comment]
To implement it correctly we will need to store an amount of donation somewhere. I'm not sure where we plan to store it, but I suggest that we simply put that as an extra `DjangoHero` field. Once we can match Paypal transaction with a donor, we will simply update `DjangoHero`.

**Comment by asendecka** [comment]
Actually, after giving it more thought, I think adding value to `DjangoHero` model is not the best idea. Donations and a way we display them depend on date. If the same person donated multiple times and we can match their e-mail address, there's no point in creating `DjangoHero` for each donation. We should reuse that. That is why donations should be stored separately. 

I will create a simple Donation model we can fill in with data from Stripe.

**Comment by olasitarska** [comment]
+1 to the second solution :)

**Comment by asendecka** [comment]
I'm on it :night_with_stars:!

**Comment by jezdez** [comment]
> Am 18.01.2015 um 00:05 schrieb asendecka <notifications@github.com>:
> 
> Actually, after giving it more thought, I think adding value to DjangoHero model is not the best idea. Donations and a way we display them depend on date. If the same person donated multiple times and we can match their e-mail address, there's no point in creating DjangoHero for each donation. We should reuse that. That is why donations should be stored separately.
> 
> I will create a simple Donation model we can fill in with data from Stripe.
> 

No need that's covered by the stripe app I'll hook into tomorrow. I can easily replace the model though when I get there if that works for you, too?

**Comment by asendecka** [comment]
@jezdez ok, I already implemented Donations, so I have something I can work with right now :). 

You can replace the model tomorrow, when you'll have Stripe figured out. 

Also - how we will connect Stripe donations with our `DjangoHeros`?

**Comment by jezdez** [comment]
> Am 18.01.2015 um 01:01 schrieb asendecka <notifications@github.com>:
> 
> @jezdez ok, I already implemented Donations, so I have something I can work with right now :).
> 
> You can replace the model tomorrow, when you'll have Stripe figured out.
> 
> Also - how we will connect Stripe donations with our DjangoHeros?
> 
I'll update that model to inherit from the stripe app's customer model, so we can directly write information about individuals that donate there. That means the heroes would be unique as what stripe considers unique, basically meaning that we don't have to do the syncing between donations and heroes manually on our side. That's important I think to have a full history of contribution per user.

**Comment by asendecka** [comment]
@jezdez that sounds awesome!
