### ISSUE TITLE
Donation snippet in sidebar everywhere 

### ISSUE THREAD

**Issue by olasitarska** [django/djangoproject.com#298]
Everywhere on the top (?) of the sidebar we should display small heart (static or dynamic with progress?) and information like that: "Ola Sitarska just donated $25 to support development of Django. Join them!" 

We should choose a random donation every time. Show amount only if someone allowed us to show it in the form in #295! Otherwise show only "Ola Sitarska just donated to support development of Django. Join them!"

**Comment by freakboy3742** [comment]
Some thoughts about presentation, using examples from Kogan (a Django-using e-retailer in Australia), and Wikipedia.

Kogan use a subtle on-page popup dialog. Visit any page on their site (e.g: (https://www.kogan.com/au/shop/tablets-laptops/ipad/)[here]), and wait a few seconds. A popup will appear on the bottom left, letting you know that someone has just bought something. 

Kogan does this to overcome 2 of the psychological hurdles of online shopping - that you can't see what is in the next persons shopping basket and think "I want that too"; and that you can't tell if the store is popular or not. The popup ticker gives the impression that people are actually using the site, and what is shown will trend towards popular products. 

Wikipedia is an obvious example, getting *really* in your face at the top of every page when they haven't met funding goals. They do this once a year, until the annual goal is met. We could do the same.
