### ISSUE TITLE
Paypal API webhook setup

### ISSUE THREAD

**Issue by olasitarska** [django/djangoproject.com#299]
We need to setup webhook with DSF Paypal account. This requires access to the account.

**Comment by jezdez** [comment]
It doesn't apparently require access, the standard Paypal integration we use right now just can be given a parameter called `notify_url` with the callback URL and then we're good. I'll use django-paypal for that.

**Comment by olasitarska** [comment]
Awesome!

**Comment by olasitarska** [comment]
Closing this because #317
