### ISSUE TITLE
Check fellowship data gathering with legal

### ISSUE THREAD

**Issue by olasitarska** [django/djangoproject.com#300]
Data we would be gathering from users (only if they want):
- emails
- names (of person or organization)
- logos
- links
- information if they want to show the amount of donation (checkbox)

Data we would be gathering from Paypal API:
- emails
- dates of transactions
- amount of transactions

**Comment by jezdez** [comment]
Using django-paypal we'll get a lot more data, so we'll have to either accept that we get it or purge the data after we receive it automatically with a signal handler.
