### ISSUE TITLE
Note target browser support in README or elsewhere

### ISSUE THREAD

**Issue by treyhunner** [django/djangoproject.com#301]
I was looking for a note about the supported Internet Explorer versions, but I haven't found any such note yet.

I think a list of target browsers could be listed in the README would be helpful.

**Comment by jezdez** [comment]
Yeah, we support IE8 and above, see #163 for more details including some stats about our users.

**Comment by jezdez** [comment]
To be clear it doesn't have to be perfect in IE8, some stuff just doesn't work in it, but the site should at least be browseable with it, until it's finally sent to hell on January 12, 2016.
