### ISSUE TITLE
Docs: Shouldn't have ligatures enabled for monospace text

### ISSUE THREAD

**Issue by timgraham** [django/djangoproject.com#304]
(moved from https://code.djangoproject.com/ticket/24131)

It's ugly. See attached screenshot.
Multiple pages affected. Example: ​https://docs.djangoproject.com/en/1.7/topics/logging/

![monospaceligatures](https://cloud.githubusercontent.com/assets/411869/5696834/19530314-99ac-11e4-8d47-10890b66b1af.png)

**Comment by jezdez** [comment]
Hm, which browser was that? @davidfstr was that you?

**Comment by timgraham** [comment]
I can reproduce on Firefox/Ubuntu 14.04. The new monospace font does seem a bit strange to me.

**Comment by jezdez** [comment]
Aha, I was trying all kinds of OS/browser combinations with browserstack.com and couldn't reproduce it. Let me explicitly disable the ligatures..

**Comment by kevin-brown** [comment]
I can reproduce this on Firefox (on Ubuntu 14.04) but not in Chrome. The issue does not happen in the fallback `Consolas` font, only when using `Fira Mono`.

**Comment by jezdez** [comment]
Okay, deployed, can you try https://docs.djangoproject.com/en/1.7/topics/logging/#examples again?

**Comment by kevin-brown** [comment]
Appears to be fixed

![image](https://cloud.githubusercontent.com/assets/1991850/5697289/3fc2e02e-99ba-11e4-8f0e-ba0cc4a8b77c.png)

**Comment by davidfstr** [comment]
Confirmed as fixed for (Firefox latest, OS X) and (Chrome latest, OS X) but still repros for (Safari latest 7.1.2, OS X 10.9.5) and (WebKit latest r178244, OS X 10.9.5).

**Comment by jezdez** [comment]
@davidfstr Should be working now, can you double check?

**Comment by davidfstr** [comment]
Confirmed as fixed for (Safari latest 7.1.2, OS X 10.9.5).
