### ISSUE TITLE
Style glitch for deprecation warnings

### ISSUE THREAD

**Issue by aaugustin** [django/djangoproject.com#305]
https://docs.djangoproject.com/en/1.7/howto/initial-data/#automatically-loading-initial-data-fixtures
![screen shot 2015-01-13 at 14 33 08](https://cloud.githubusercontent.com/assets/788910/5721366/1ec16986-9b31-11e4-8090-d3f052ffe1ad.png)

**Comment by jezdez** [comment]
Yeah, I saw it a couple of times already, just forgot to open a ticket, thanks @aaugustin!

**Comment by jezdez** [comment]
![screen shot 2015-01-13 at 16 47 43](https://cloud.githubusercontent.com/assets/1610/5723421/2de0a31a-9b44-11e4-8af3-3152c4af91d9.png)

**Comment by aaugustin** [comment]
Looks good! :star:
