### ISSUE TITLE
UX issue: label of version select in search form

### ISSUE THREAD

**Issue by olasitarska** [django/djangoproject.com#306]
I got a bug report from a friend saying that the select input under search doesn't really change the version of the docs and that they had to use the version switcher at the bottom of the page.

This is obviously a UX issue: people think that "Version: [select here]" is actually changing the version of docs too. I think changing the label from "Version" to "Search in version" would fix this.

**Comment by jezdez** [comment]
This is an issue that won't be a problem with the new search in #301 since the version select is removed there.

**Comment by jezdez** [comment]
Err #303

**Comment by olasitarska** [comment]
Awesome, that's why I decided not to fix it right away, knowing that there is a search work going on. Thanks @jezdez!
