### ISSUE TITLE
Move Trac repo into this one

### ISSUE THREAD

**Issue by jezdez** [django/djangoproject.com#307]
We have a separate repo for code.djangoproject.com and that's silly. This should also help fix #187

**Comment by alej0varas** [comment]
Got this trying to run code.djangoproject.com in the same invironment that dp.com

    Trac doesn't support Python 3 (yet)

**Comment by timgraham** [comment]
The idea of this issue is to combine the code repositories, not to run them in the same virtual environment.

**Comment by carltongibson** [comment]
I'm not convinced about this. If e.g. Florian/Markus/Mariusz were to take it up that would be one-thing, but otherwise I don't think it's likely to happen.
