### ISSUE TITLE
Move dev dashboard code into this repo

### ISSUE THREAD

**Issue by jezdez** [django/djangoproject.com#309]
There just was this PR to update the dev dashboard to the new styles: https://github.com/django/django-dev-dashboard/pull/15

And I think similar to the Trac issue we'll have a hard time keeping them in sync separately. Plus, Jacob has indicated that he wants to do less not more Django work, so I guess we better move this over. What do you think? We can handle the same stuff with our new multiple host stuff based on django-hosts.

**Comment by timgraham** [comment]
So you don't want to run that on Heroku anymore? What if people.djangoproject.com wants to use the new styles? Do they have to merge into this repo and run on the djangoproject.com server too?

**Comment by jezdez** [comment]
@timgraham Yeah, no Heroku anymore for the dashboard.

People is a lot more complex tech wise and isn't particular close style wise to www anyway. The dashboard is simplistic code though and can totally run on our side of things.

**Comment by relekang** [comment]
I started to do [some work on this](https://github.com/relekang/djangoproject.com/compare/django:master...relekang:djddashboard), based on django/django-dev-dashboard#15.

**Comment by jezdez** [comment]
This is now merged and deployed. @timgraham Only thing needed is the DNS change, which I can't do because I don't have access to the Rackspace console.
