### ISSUE TITLE
Unsubscribing from feed in admin gives a 500 error

### ISSUE THREAD

**Issue by bmispelon** [django/djangoproject.com#311]
I was trying to deactivate a feed on the site by switching its status to "denied" in the admin.

Trying to do so leads to an error page (500).

    Here's the traceback and error messages associated (provided by Tim):
    ...
      File "django/contrib/admin/options.py", line 1045, in save_model
        obj.save()
      File "aggregator/models.py", line 54, in save
        self.unsubscribe()
      File "aggregator/models.py", line 63, in unsubscribe
        Subscription.objects.get(topic=self.feed_url).unsubscribe()
      File "django_push/subscriber/models.py", line 86, in unsubscribe
        return self.send_request(mode='unsubscribe')
      File "django_push/subscriber/models.py", line 131, in send_request
        response,

    SubscriptionError: (u'Error during request to hub https://superfeedr.com/hubbub for topic http://feeds.delicious.com/v2/rss/tag/django?count=15: Unauthorized', <Subscription: http://feeds.delicious.com/v2/rss/tag/django?count=15: https://superfeedr.com/hubbub>, <Response [401]>)

**Comment by bmispelon** [comment]
For the record, there's also an error (probably the same one) when trying to approve a feed.

**Comment by jezdez** [comment]
We changed the email address of the superfeedr account a while ago to ops@d.c and the credentials were still using the old address. I just pushed a new update, can you try again?

**Comment by freakboy3742** [comment]
@jezdez I'm guessing the answer is no, if the error I saw in #418 is the same thing.

**Comment by timgraham** [comment]
I looked into this a bit and the credentials look okay on our end. I'd like to contact Superfeedr to see if something might have been missed on their end when they changed the email address on our account. Jannis, do you have the contact from when you did that?

**Comment by jezdez** [comment]
@timgraham julien at superfeedr dot com

**Comment by timgraham** [comment]
In the authentication credentials, we needed to use the username instead of the email address.

**Comment by freakboy3742** [comment]
I'm still seeing this error when approving feeds.

**Comment by timgraham** [comment]
The error is:
```
SubscriptionError: ('Error during request to hub https://superfeedr.com/hubbub for topic
http://timonweb.com/taxonomy/term/60/all/feed: Make sure your callback returns a 2XX
status code. You returned 404 to https://www.djangoproject.com/subscriber/846/?
hub.mode=subscribe&hub.topic=http%3A%2%2Ftimonweb.com%2Ftaxonomy%2Fterm%2F60%2Fall%2Ffeed&
hub.challenge=xedbjdr6bt9&hub.lease_seconds=315360000', <Subscription: Subscription object>,
<Response [422]>)
```
I couldn't quickly debug the issue.

As a workaround, approving feeds using the [change list page](https://www.djangoproject.com/admin/aggregator/feed/?approval_status__exact=P) seems to work fine.

**Comment by freakboy3742** [comment]
Hrm... I get an error even from the change list, but it appears that approvals are going through (at least, the approval status is updating).

**Comment by timgraham** [comment]
Moving this to a new issue (https://github.com/django/djangoproject.com/issues/511) because the original problem of bad credentials has been solved and unsubscribing no longer crashes.
