### ISSUE TITLE
Clicking on the documentation version switcher makes it not work on hover anymore.

### ISSUE THREAD

**Issue by gcbirzan** [django/djangoproject.com#315]
To reproduce, go to https://docs.djangoproject.com/en/1.7/ (or any doc page), click on "documentation version: 1.7".

This could be a 'feature', but to me it feels like a bug.

**Comment by bmispelon** [comment]
I can indeed reproduce this (on Firefox 34) but I have no idea what's causing the issue.

The js code that sets up the events is at https://github.com/django/djangoproject.com/blob/master/djangoproject/static/js/mod/version-switcher.js#L21 and I don't see anything wrong with it.

**Comment by oinopion** [comment]
JS uses `toggle`, which sets up the `display` property on elements. This has more specificity than definitions in CSS file.
