### ISSUE TITLE
Stripe integration for fundraising page

### ISSUE THREAD

**Issue by olasitarska** [django/djangoproject.com#317]
- [ ] Update ansible playbook to contain the live Stripe API keys
- [x] Test on mobile
- [ ] Test on Internet Explorer
- [x] Make sure the heart still works
- [ ] Try out the donation form in the foundation pages' sidebar
- [ ] Try to break the form with some senseless input

Post launch:
- [ ] Send email to donors with link to update their donation info

**Comment by timgraham** [comment]
IE9 doesn't support the placeholder I believe, so all the boxes are empty which makes for a confusing UI there. Not sure if this matters for our audience.

**Comment by timgraham** [comment]
There are no error indicators on the credit card page except the box border turning red on error. Should this be improved?

**Comment by timgraham** [comment]
re: "Send email to donors with link to update their donation info" -- I think we could defer this for launch and handle these requests (if any) manually.

**Comment by timgraham** [comment]
Heart was fixed by https://github.com/django/djangoproject.com/pull/325

**Comment by olasitarska** [comment]
> re: "Send email to donors with link to update their donation info" -- I think we could defer this for launch and handle these requests (if any) manually.

I agree!

**Comment by olasitarska** [comment]
Moved tracking of remaining issues to #327
