### ISSUE TITLE
Question for Django Core Team?

### ISSUE THREAD

**Issue by Copser** [django/djangoproject.com#319]
Hello there this is maybea of topic but I wont to ask Django Core Team, did they now someone who is practising Django in Belgrade-Serbia, or Zagreb-Croatia, I now there is a strong Slovenia team there, but I was wondering about this area around Bosnia where I live in.
I am asking because I was inspired by this post here http://blog.djangogirls.org/post/108268319658/django-girls-core-team-grows, and mine chat whit Daniel Roy Greenfel @pydanny over Twitter https://twitter.com/Coopsess/status/556665409693163520.
So do you now eny one? 
Tank you.

**Comment by timgraham** [comment]
Please use the [django-users mailing list](https://groups.google.com/group/django-users) for queries like this. The Django Girls team is a different entity from the "Django Core Team" so you may want to contact them separately if that's your interest. Thank-you.

**Comment by Copser** [comment]
Ok sory for this.
