### ISSUE TITLE
Not showing up in "Heroes"?

### ISSUE THREAD

**Issue by carljm** [django/djangoproject.com#333]
I donated $200 at https://www.djangoproject.com/fundraising/ and then filled out the "Hero" form, but after waiting for a while, I'm not seeing my info show up next to @jezdez under "Django Heroes."

I don't really care whether my info in particular shows up, just reporting in case this is an issue that will affect other future contributors, too.

It may just be a matter of caching (though it's been twenty minutes or so, so if so the cache must have a longish timeout), but even so that may be something people who fill out the "Hero" form should be made aware of.

Thanks for all the work on the new site, and the new fundraising infrastructure!

**Comment by carljm** [comment]
(Also, if it's caching, it's not full-page caching, because the fundraising numbers -- percentage of goal, dollars, and number of donors -- immediately reflected my contribution, and have continued to update since.)

**Comment by timgraham** [comment]
There's a moderation queue and we need someone to delegate permissions in the admin.

**Comment by carljm** [comment]
Ah! Makes sense. Perhaps a note to that effect on the Hero form would be useful, so people don't expect to see their logo right away. (Or maybe there's already a note there and I just missed it, that's quite possible.)

**Comment by olasitarska** [comment]
Yeah, note about it should be added :)

**Comment by timgraham** [comment]
How about if we change the checkbox to say "Yes, display my name, URL, and logo on this site. (It'll be displayed shortly after we verify it.)"
