### ISSUE TITLE
Display non-amount disclosed donations separately

### ISSUE THREAD

**Issue by timgraham** [django/djangoproject.com#334]
The current sorting of donations enables you to estimate the donation amount by looking at the neighboring donations.

**Comment by treyhunner** [comment]
You could also use random sorting on the two groups of donors.  A possible downside is that really big donations may not show up first.

**Comment by jezdez** [comment]
Agreed, random sorting seems sensible here.

**Comment by aaugustin** [comment]
On https://myks.org/en/multiple-template-engines-for-django/funders/ I went for the cop-out — make a dedicated section for people who don't disclose the amount.

**Comment by bmispelon** [comment]
What about weighted random (by donation amount)?
