### ISSUE TITLE
Gray out title of unpublished blog posts

### ISSUE THREAD

**Issue by MarkusH** [django/djangoproject.com#339]
If there is an unpublished blog post, I can't see if it is already published. I think a gray-ish color would solve the problem:

![django-blog-unpublished](https://cloud.githubusercontent.com/assets/475613/5844993/c54a7c7e-a1b8-11e4-9a21-3375ed43081b.png)

**Comment by timgraham** [comment]
Core dev problems...

**Comment by jezdez** [comment]
:zap:
