### ISSUE TITLE
Improve donation error handling

### ISSUE THREAD

**Issue by mjtamlyn** [django/djangoproject.com#342]
Even if there's no helpful message from stripe, something is better than a 500.

**Comment by jezdez** [comment]
Agreed, and IIRC the stripe APIs does provide more detailed exceptions than the generic one we use right now.

**Comment by acdha** [comment]
I believe I just ran into this earlier – retyping my CVV2 fixed it. The main thing I wanted on that page was clear statement that it's safe to either reload the page or try again.

**Comment by jezdez** [comment]
This should be refactored in #335

**Comment by jezdez** [comment]
Scratch that, PR coming up..

**Comment by jezdez** [comment]
PR at #360
