### ISSUE TITLE
Extra space after Hero name

### ISSUE THREAD

**Issue by jaap3** [django/djangoproject.com#347]
There's an extra space after the Hero name on https://www.djangoproject.com/fundraising/, but for some reason only for the Hero's that have is_amount_displayed enabled.

**Comment by bmispelon** [comment]
Hi,

I'm not sure I see the extra space you're talking about. Could you post a screenshot of what you're seeing?

Thanks :sparkles:

**Comment by mjtamlyn** [comment]
![](https://www.dropbox.com/s/o99fsphkk9lt7wh/Screenshot%202015-01-22%2016.00.44.png?dl=1)

Note how the underline extends past the `n` on Paul's name, but not Roberto's.

**Comment by bmispelon** [comment]
Weid, I'm not seeing that at all...
![support_django_django_-_2015-01-22_17 03 23](https://cloud.githubusercontent.com/assets/6345/5859182/a46d3c44-a258-11e4-8fe3-d22c7d3b9e82.png)

(Firefox on Linux here)

**Comment by jaap3** [comment]
I'm seeing what @mjtamlyn is seeing in Chrome on OSX

**Comment by mjtamlyn** [comment]
Yeah, I'm Chrome on OSX. Webkit fail at a guess...

Probably related to these lines: https://github.com/django/djangoproject.com/blob/65fb0f0b4a159d0169fd3124f7bb8e957bfc1c48/djangoproject/templates/fundraising/index.html#L133-L135

Basically it doesn't like an `<a>` with trailing whitespace followed by a `<br>`. I don't know why... Maybe put those three lines together and it might fix it. If I edit the html on the page so there is no extra whitespace inside the `<a>` tag it looks fine.
