### ISSUE TITLE
Add FAQ: How can I donate if Stripe won't process my payment?

### ISSUE THREAD

**Issue by timgraham** [django/djangoproject.com#358]
Asked in #django-websites

**Comment by jezdez** [comment]
Makes sense, it's simple: send a donation via PayPal (sorry) to ` jkocherhans@djangoproject.com` and let me how much you donated. We can add the donation to the database manually.

**Comment by jezdez** [comment]
Also added to the flatpages based FAQ here: https://www.djangoproject.com/foundation/donate/#donation-alternatives
