### ISSUE TITLE
Update Docker logo on fundraising page?

### ISSUE THREAD

**Issue by kencochrane** [django/djangoproject.com#359]
When we made a donation from Docker, I guess we used the wrong logo, and it is too small. Would it be possible to update the logo to the one attached to this issue? 

Sorry for the trouble, if you need the file emailed or in a different format or size, please let me know.

![3-vertical-transparent_no_blank](https://cloud.githubusercontent.com/assets/261601/5888840/d305a850-a3db-11e4-8e8b-e38b62a48734.png)

**Comment by jezdez** [comment]
Done, may take a few minutes for the cache to invalidate.
