### ISSUE TITLE
Lincoln Loop and Two Scoops Press don't show up as donors

### ISSUE THREAD

**Issue by pydanny** [django/djangoproject.com#367]
We've both sent in funds, but we don't appear to be live on the donor page yet: https://www.djangoproject.com/fundraising/

**Comment by timgraham** [comment]
Just approved Two Scoops entry and @jezdez is addressing Lincoln loop.

**Comment by mtrythall** [comment]
Thanks for investigating!

**Comment by jezdez** [comment]
Found the problem and asked @ipmb to resubmit the Django hero data. Should be up in a few minutes after cache is refreshed. Thanks all!
