### ISSUE TITLE
`rel=nofollow` on fellowship donor links

### ISSUE THREAD

**Issue by freakboy3742** [django/djangoproject.com#371]
A potential fellowship donor has contacted the DSF asking if the `rel=nofollow` on donor links could be removed, so that his consultancy gets a small SEO kick from being listed. 

That doesn't sound fundamentally unreasonable to me - if someone is willing to make a financial contribution, a link back isn't much to ask.

Was the use of `rel=nofollow` a deliberate decision? For comparison, the links on corporate members aren't `nofollow`ed.

**Comment by timgraham** [comment]
Yes, Jannis raised a concern about this: 65fb0f0b4a159d0169fd3124f7bb8e957bfc1c48

**Comment by freakboy3742** [comment]
I presume the concern is making us looking like a link farm? I'm not an SEO guy, but is it really that much of a risk, given the number of back links we have giving us authority for "Django"?

**Comment by jezdez** [comment]
> Am 29.01.2015 um 01:54 schrieb Russell Keith-Magee <notifications@github.com>:
> 
> I presume the concern is making us looking like a link farm? I'm not an SEO guy, but is it really that much of a risk, given the number of back links we have giving us authority for "Django"?
> 
It is if we are taking money for the links. I strongly suggest to keep using nofollow to not risk being downrated or at worst being investigated by Google. This was after getting feedback from a fellow webdev at Mozilla so not completely out of the blue.

It's a common practice to use nofollow for links that are outside one's area of influence, and even if we are doing cursory review of the URLs we can't be sure if the content may not change of one of the sites. It also makes sense as it simplifies scaling the fundraising efforts.
