### ISSUE TITLE
Reopening for this issue.

### ISSUE THREAD

**Issue by AcmeProgramming** [django/djangoproject.com#378]
Sorry but 'change your font size and your background color' is not a good enough resolution.

https://github.com/django/djangoproject.com/issues/253

And 'we did it this way because everyone else does.' isnt a satisfactory answer.

**Comment by jezdez** [comment]
Hi @AcmeProgramming, thanks again for your repeated feedback. Changing the font size or background color in your browser is definitively a good resolution from our perspective as it would help fix your immediate problem.

I would also recommend to check out https://userstyles.org/ which provides some info about how to override default styles of websites with own preferences (includes plugins for Firefox and Chrome).

We'll be taking a look at the blank whitespace of some pages soon while working on new features such as case studies. Thanks again for your feedback, I hope you'll still use our website.
