### ISSUE TITLE
New displaying of Django Heros on Fundraising pages

### ISSUE THREAD

**Issue by olasitarska** [django/djangoproject.com#384]
We've decided to implement new displaying & sorting of Django Heros on Fundraising pages.

- We display everyone in two columns: companies & organizations on the left, individuals on the right. This is to show that even though individuals can obviously donate less than organizations, we value the help from them equally.
- We won't be disclosing the amounts of donations anymore. This should also remove the checkbox about it from the Django Hero form.
- Both organizations and individuals should be sorted by amount of donation (highest first). With recurring donations, we should take an accumulated sum of all previous donations to given campaign into account.

**Comment by surfing-girl** [comment]
Let me look at it if I can fix the issue.
