### ISSUE TITLE
Error with example on primary_key

### ISSUE THREAD

**Issue by psnma** [django/djangoproject.com#391]
Link: https://docs.djangoproject.com/en/1.7/topics/db/models/#field-options

The primary key field is read-only. If you change the value of the primary key on an existing object and then save it, a new object will be created alongside the old one.

But in the example primary_key is not changed, only the value of the name field.

**Comment by timgraham** [comment]
`name` is the primary key -- see how it's declared with `primary_key=True`?

For future reference, documentation bugs go to https://code.djangoproject.com/. Thanks!
