### ISSUE TITLE
Provide "View on Github" link for source files.

### ISSUE THREAD

**Issue by phalt** [django/djangoproject.com#392]
Often when browsing the documentation I end up viewing the source code on djangoproject.com (like [this page here](https://docs.djangoproject.com/en/1.7/_modules/django/core/validators/#RegexValidator)). From here I often need to check the file on Github, of link to a certain line in the code (on GitHub), which I have to do manually. 

It would be useful to provide a "view this file on github" link for source code pages that link to their corresponding file.

**Comment by jezdez** [comment]
Yeah, not a bad idea. This sounds like a thing we'd need to do on Sphinx' side.

**Comment by zachborboa** [comment]
Linking to GitHub source files would be really helpful. I've found myself missing this feature.

We could change the "[source]" links and have them point directly to the GitHub source pages. The "View on GitHub" links should still be added for users that visit the source code pages on docs.djangoproject.com directly.

A simple solution to accomplish the above would be to create our own Sphinx documentation extension that is very much similar to the [sphinx.ext.viewcode](https://github.com/sphinx-doc/sphinx/blob/master/sphinx/ext/viewcode.py) that is [already enabled](https://github.com/django/django/blob/master/docs/conf.py#L43) for Django documentation.

- Change "[source]" links by modifying [def doctree_read](https://github.com/sphinx-doc/sphinx/blob/master/sphinx/ext/viewcode.py#L53).
- Add "View in Github" links by modifying [def collect_pages](https://github.com/sphinx-doc/sphinx/blob/master/sphinx/ext/viewcode.py#L146).

**Comment by carltongibson** [comment]
Fixed by https://github.com/django/django/pull/15808 I think.

**Comment by zachborboa** [comment]
> Would you try to propose a PR to fix this?

Thanks for reopening. Will work on one

**Comment by zachborboa** [comment]
Will enable the "sphinx.ext.linkcode" extension and implement `linkcode_resolve()`.
https://www.sphinx-doc.org/en/master/usage/extensions/linkcode.html

**Comment by zachborboa** [comment]
created https://github.com/django/django/pull/16203

**Comment by zachborboa** [comment]
Believe this can be closed as https://code.djangoproject.com/ticket/29942 was fixed and "[source]" links now point to the source code in GitHub.

**Comment by bmispelon** [comment]
> Believe this can be closed as https://code.djangoproject.com/ticket/29942 was fixed and "[source]" links now point to the source code in GitHub.

Good call, thanks for the heads up it's much appreciated ✨
