### ISSUE TITLE
Mention disabling local users explicitly

### ISSUE THREAD

**Issue by mkesper** [django/djangoproject.com#395]
If you configure according to https://docs.djangoproject.com/en/1.7/howto/auth-remote-user/#authentication-using-remote-user you disable all local users.
This should be mentioned explicitly.
You will eg. be able to use commands like manage.py createsuperuser.

**Comment by timgraham** [comment]
Thanks for the report, but documentation tickets should be reported here: https://code.djangoproject.com/newticket.
