### ISSUE TITLE
Page Not Found - https://www.djangoproject.com/about/

### ISSUE THREAD

**Issue by WilliamQLiu** [django/djangoproject.com#398]
Hi, I'm new here so let me know if this is the wrong place to issue a hyperlink bug.

When I access this [page](https://www.djangoproject.com/weblog/2015/jan/27/django-fellowship-fundraising-goal-achieved/), there's a link all the way on the bottom that says "There are always alternative ways to donate or partner with the Django Software Foundation.".  The 'Django Software Foundation' link points to a broken link [here](https://www.djangoproject.com/about/)

**Comment by bmispelon** [comment]
Hi,

I'm pretty sure this is the correct place to report this kind of issues.

I've update the link in the blog post and it should now be fixed (there might be some caching involved so it could take some time to actually appear online).

Thank you for the report! :rocket:
