### ISSUE TITLE
TypeError: Sorting watchlist not working

### ISSUE THREAD

**Issue by jdufresne** [django/djangoproject.com#401]
* Sign in
* Go to URL <https://code.djangoproject.com/watchlist>
* Click the headers multiple times to sort by the column ascending and descending
* Notice the sort order does not change

There is an error in the Firebug console:

```
TypeError: c[f] is undefined
https://code.djangoproject.com/chrome/watchlist/js/dynamictables.js
Line 24
```

**Comment by timgraham** [comment]
We're going to ditch this plugin as it doesn't seem to be useful or actively maintained.
