### ISSUE TITLE
You are here as breadcrumbs

### ISSUE THREAD

**Issue by wimfeijen** [django/djangoproject.com#403]
Hi,

Django's documentation is staggering. I really like the "You are here" path in the right sidebar in order to navigate more easily.

In effect, they function as breadcrumbs. For me, it would be more clear if we included those as a breadcrumb path in a small font size just below or to the right of the page heading.

**Comment by timgraham** [comment]
Could be useful but who will implement it? Better to keep things simple, I suppose. Closing as wontfix.
