### ISSUE TITLE
active (current) page in menu is not highlighted

### ISSUE THREAD

**Issue by wimfeijen** [django/djangoproject.com#404]
Hi,

I like the new layout very much.

A small improvement could be to highlight the current page in the top menu.

For example, we could use light green as a color for the active page if we are on that page or a subpage. If we want the effect to differ from the mouse-over effect, we could add an underline to the mouse-over.

It is a small detail that helps people figuring out where they are.

**Comment by maurodoglio** [comment]
I'm going to give it a try

**Comment by maurodoglio** [comment]
The problem seems to be with a missing variable in the template context.

**Comment by maurodoglio** [comment]
Does anyone know where I can take the "section" information from?

**Comment by bmispelon** [comment]
I believe this is the same as issue #354 which has a bit more information in it. :bug:
