### ISSUE TITLE
Setup a local development environment using vagrant or docker 

### ISSUE THREAD

**Issue by maurodoglio** [django/djangoproject.com#408]
This would make it easier to contribute for new comers.

**Comment by jezdez** [comment]
I'm happy to work on this as I've had something similar already in place a few months ago.

**Comment by maurodoglio** [comment]
Thanks @jezdez !

**Comment by alej0varas** [comment]
Hi @jezdez, are you working on this? I'm interested too.

**Comment by alej0varas** [comment]
I'm working on these here https://github.com/alej0varas/djangoproject.com/tree/issue-408

I've automated the deployment process documented in the readme. Adding two containers one with PostgreSQL and other with Elasticsearch.

**Comment by timgraham** [comment]
For what it's worth, we have a private repository with ansible scripts to deploy the djangoproject.com server. It might be better if we could make these public (except the "secrets") instead of duplicating that work in another set of scripts.

**Comment by maurodoglio** [comment]
Making the deployment code public sounds like a sensible idea anyway :smiley:.
Do the ansible scripts also include some machine provisioning?

**Comment by timgraham** [comment]
In production we launch our VMs manually on Rackspace.

**Comment by alej0varas** [comment]
What about development environment? I've reduced from 12 to 4 steps the deployment process. And no PostgreSQL or Elasticsearch setup is required. No need to edit /etc/hosts!

Some details need to be addressed like data persistence. None of the containers is configured to do this.

**Comment by timgraham** [comment]
I created a VM in VirtualBox for testing the ansible scripts but I do development on my local machine. I don't object to your work, just afraid that it might go stale over time unless you have a continued interest in maintaining it. (I'm not sure I want to task the Django team with maintaining it on an ongoing basis.)

**Comment by alej0varas** [comment]
Made a new branch. Only changed the Readme and Makefile to point to the containers but made them optional. 

https://github.com/alej0varas/djangoproject.com/tree/issue-408-1

**Comment by mjhea0** [comment]
https://github.com/django/djangoproject.com/pull/912
