### ISSUE TITLE
Move to libsass

### ISSUE THREAD

**Issue by jezdez** [django/djangoproject.com#417]
Apparently there is now an official sass compiler written in C++ and there is a pretty neat Python package to use that: https://pypi.python.org/pypi/libsass

Since that would prevent us from having to have Ruby on the server and is also much faster to run, I'd say we move away from committing the built CSS files and do the compile step during deployment.

**Comment by mtrythall** [comment]
The Compass dependency would make the move a little harder, but I just looked through the project's SCSS and I can't see a big reason for still needing it. If I'm wrong, please someone correct me. 

A lot of it seems to be for vendor prefixes that could be easily built out, or are no longer necessary.

**Comment by jezdez** [comment]
@mtrythall Makes sense to me, if you happen to have a bit more experience than I do (I know you have) and have a bit spare time, let me know how we can work on this together. Or if you want to pick this up completely..

**Comment by mtrythall** [comment]
I have a bit of time and have been trying to find a way to contribute, so sure, I'm all for it. I can, at least, handle it from the Sass/CSS end and have it so everything compiles nicely with Libsass, sans-Ruby.

I'll start poking around this week(end) or so. I'm in IRC so around if you want to ping me.

**Comment by mtrythall** [comment]
Hey @jezdez - Started some work on this in a fork:

https://github.com/lincolnloop/djangoproject.com/tree/remove-ruby

Will keep you posted. Going to keep chugging along.

**Comment by mtrythall** [comment]
Ok, that fork+branch linked above now compiles without Ruby using [sassc](https://github.com/sass/sassc), which is a command line wrapper for Libsass. I'll need to do cross browser testing still, but the changes were incredibly minor (mostly removing prefix mixins, easy stuff), so I don't expect much if anything to turn up.

It looks like next steps are:

1. Figure out how we'll be compiling Sass via Python. If https://pypi.python.org/pypi/libsass, then...
2. We'll need to figure out how to replace `compass watch`, which was a nice (probably necessary) utility for development.
3. Figure out how all of this works with deployment.
4. Update the docs.

I'll see what I can do with 1 and 2 but help is always appreciated.

**Comment by mtrythall** [comment]
Using this branch strictly for the removal of the mixins:

https://github.com/lincolnloop/djangoproject.com/tree/remove-compass-mixins

You can technically still use Compass (as a sort of wrapper) for compilation, we just aren't using any of its mixins anymore. This branch might be ready to merge before all of the Libsass conversion is ready.

**Comment by mtrythall** [comment]
Pete @ LL did some digging and it looks like sassc gets installed with libsass (didn't even see that). So, no need for watchdog or anything. Just have make wrap sassc and we're good. I'll take a look at this tonight/tomorrow.

**Comment by mtrythall** [comment]
Update on this issue, there is a pull request out for the removal of the Ruby dependency:

https://github.com/django/djangoproject.com/pull/420

Integration into deployment (and thus removing the CSS files from the project) has to be done by someone else.

**Comment by jezdez** [comment]
I'm calling this done for now since we're now shipping the css files as before. Integration with staticfiles may need to wait.
