### ISSUE TITLE
Displaying problem on android devices

### ISSUE THREAD

**Issue by mishavetl** [django/djangoproject.com#419]
I have a big space on the right.
Samsung S3 Android

**Comment by mtrythall** [comment]
@mishavetl - Is this just on the homepage or any specific page?

**Comment by mishavetl** [comment]
On all pages
I tried on Google Chrome, Mozilla Firefox, Opera. In all there is the same problem

Sorry for my bad english. It is not my native language

**Comment by mtrythall** [comment]
Unfortunately, switching the whole site over to Bootstrap would be a massive undertaking and ultimately results in an entirely new site. 

I did a quick test (albeit, via an emulator) and wasn't able to reproduce your problem. These are on an S3 with Chrome:

http://app.crossbrowsertesting.com/screenshots/558867/631028/5850368?type=windowed

http://app.crossbrowsertesting.com/screenshots/558867/631028/5850369?type=windowed

http://app.crossbrowsertesting.com/screenshots/558869/631030/5850391?type=windowed

http://app.crossbrowsertesting.com/screenshots/558869/631030/5850392?type=windowed

Can you maybe post a screenshot and give us more info?

**Comment by mishavetl** [comment]
I tried again and the problem disapeared. Maybe that was a bug on the server or on my local phone. Thank you for your support.
