### ISSUE TITLE
Searching for `setup.py` yields no result but should

### ISSUE THREAD

**Issue by bmispelon** [django/djangoproject.com#423]
Reported originally as ticket [24557](https://code.djangoproject.com/ticket/24557).

I think it's worth investigating (with any luck, #303 will fix the issue for free).

Note that when searching for `setup`, the page containing `setup.py` shows up but it goes away when searching for `setup.`.

**Comment by jezdez** [comment]
Yeah this will be fixed once I have the refactored search done.
