### ISSUE TITLE
Search should treat _ as a "word-character"

### ISSUE THREAD

**Issue by aaugustin** [django/djangoproject.com#425]
If you search for list_display, some results highlight the word list.

@jezdez points out that quoting seems to improve search but the highlighting problem persists. This isn't very intuitive for users anyway.

Based on my very superficial understanding of ElasticSearch, this could be related to the lexer: it shouldn't treat _ as a separator.

**Comment by ierror** [comment]
I would like to work on this. As @aaugustin mentioned we need to define our own analyzer / tokenizer: http://www.elastic.co/guide/en/elasticsearch/guide/master/custom-analyzers.html

**Comment by ierror** [comment]
ATM we are using the "simple" analyzer. I would suggest to replace it by a custom "whitespace + lowercase" analyzer?

**Comment by jezdez** [comment]
Hi Bernhard, I'm sorry but I've been working on this already over the long weekend and will soon push it to the server
