### ISSUE TITLE
Homepage icons upside down

### ISSUE THREAD

**Issue by freakboy3742** [django/djangoproject.com#431]
As of time of writing, the icons on the home page are upside down.

![screenshot 2015-04-04 06 04 55](https://cloud.githubusercontent.com/assets/37345/6989636/9ad8280e-da90-11e4-862b-a048a5120108.png)

**Comment by timgraham** [comment]
Fixed in 2c0d0630a8adb9e79fd5d1b093bdd14c0db5805a.
