### ISSUE TITLE
Django 1.6 documentation missing

### ISSUE THREAD

**Issue by grantmcconnaughey** [django/djangoproject.com#439]
The documentation for Django 1.6 appears to be gone. It is not in the "Documentation version" picker at the bottom of the page. To reproduce:

* Go to djangoproject.com
* Click documentation
* Notice that 1.6 is not in the list

Alternatively, notice that going to https://docs.djangoproject.com/en/1.6/ results in a 404.

**Comment by timgraham** [comment]
I'm debugging ongoing issues with doc build errors. Hopefully https://github.com/django/djangoproject.com/commit/6d657eb171ed3fc94ce172602ee3d50bab22a9a8 will prevent versions from going missing.

**Comment by axisofentropy** [comment]
I don't think this is fixed.

**Comment by timgraham** [comment]
Django 1.6 hasn't received security updates since April 2015 and its documentation is now removed from docs.djangoproject.com.
