### ISSUE TITLE
Add Sentry logo to footer

### ISSUE THREAD

**Issue by jezdez** [django/djangoproject.com#441]
I have a EPS logo file in case anyone wants to work on it

**Comment by girishkumarkh** [comment]
Sure you can send it over! I will work on it

**Comment by olasitarska** [comment]
https://www.dropbox.com/s/z8t5d3y2c1rv1zk/sentry-icon-black.svg?dl=0
https://www.dropbox.com/s/0u2esju0cj7eaad/sentry-logo-black.svg?dl=0
https://www.dropbox.com/s/ewflsojllqhcm49/sentry-avatar.png?dl=0
https://www.dropbox.com/s/jq7ebmhy61qpltc/sentry_logo_stacked.eps?dl=0

**Comment by jezdez** [comment]
EPS here: http://jzdz.me/code/1S1K3n2x3G1C

**Comment by timgraham** [comment]
I added an "in-kind" donor section to https://www.djangoproject.com/fundraising/. Maybe that's sufficient instead of also recognizing everyone in the footer, what do you think?
