### ISSUE TITLE
Add Elasticsearch logo to footer

### ISSUE THREAD

**Issue by jezdez** [django/djangoproject.com#442]
Hey @HonzaKral, any way to get a good logo file for the footer?

**Comment by HonzaKral** [comment]
Sure: https://www.dropbox.com/s/fokpcjarjktrvqw/elastic_logo_color.eps?dl=0

**Comment by girishkumarkh** [comment]
Awesome! I am adding the logo to the footer.

**Comment by girishkumarkh** [comment]
![screen shot 2015-06-04 at 16 54 18](https://cloud.githubusercontent.com/assets/2886380/7988269/63671824-0ada-11e5-981d-95147fc024cc.png)
Should look like this.

**Comment by HonzaKral** [comment]
Thanks @girishkumarkh !

**Comment by girishkumarkh** [comment]
You are welcome @HonzaKral

**Comment by jezdez** [comment]
Eh, I think I just deployed that, FYI
