### ISSUE TITLE
Error on requesting docs version with invalid language

### ISSUE THREAD

**Issue by timgraham** [django/djangoproject.com#446]
Requested URL: https://docs.djangoproject.com/wp-admin/css/colors-classic.css/
```
AttributeError: 'NoneType' object has no attribute '_info'
(1 additional frame(s) were not displayed)
...
  File "docs/views.py", line 56, in document
    activate(lang)
```

**Comment by timgraham** [comment]
Can't reproduce locally and not sure why sentry doesn't show the full traceback, but I guess the root cause might be here: https://github.com/django/django/blob/8bb369ef6345074216471c41bd575d540992c76e/django/utils/translation/trans_real.py#L172-L174

`base_lang(lang)` is 'wp' so if `_translations` contains that and `res` is `None`, the next line would throw the exception. It seems this code has been refactored in 1.8, so this might be fixed there.

@claudep care to take a look?

**Comment by claudep** [comment]
Yes, this is most probably a race condition where two threads are entering the `translation(language)` function with the same language. In 1.8 and up, this should be almost impossible, as the test of the language presence in `_translations` and adding the language in `_translations` happens in just two lines:
```
    if language not in _translations:
        _translations[language] = DjangoTranslation(language)
```
We could use a lock if this were still problematic.

**Comment by timgraham** [comment]
Thanks, I'll file a Django ticket if we see the issue after upgrading then.
