### ISSUE TITLE
Missing fontfile?

### ISSUE THREAD

**Issue by apollo13** [django/djangoproject.com#448]
our (webserver) error logs show many logs ala: server: code.djangoproject.com, request: "GET /chrome/site/fonts/fira-mono/FiraMono-Regular.ttf HTTP/1.1", host: "code.djangoproject.com", referrer: "https://code.djangoproject.com/chrome/site/css/trachacks.css".

Is that file at a different location or just missing?

**Comment by bmispelon** [comment]
We might need to copy over the fontfile to the `code.djangoproject.com` repo.

It's possible that we forgot to do it when we copied over the CSS which referenced it.

**Comment by bmispelon** [comment]
PR opened: https://github.com/django/code.djangoproject.com/pull/48
