### ISSUE TITLE
Add "running unit test" infos in new-contributors page

### ISSUE THREAD

**Issue by feroda** [django/djangoproject.com#453]
Hi guys,

I'm participating in a sprint at Pycon6 in Italy and I am wondering if the short snippet found about running test in https://github.com/django/django/blob/master/README.rst should be included in the page:

https://docs.djangoproject.com/en/dev/internals/contributing/new-contributors/

because knowing how to run the test suite is a basic first step for new contributors.

The snippet is:

```
To run Django's test suite:

    Follow the instructions in the "Unit tests" section of docs/internals/contributing/writing-code/unit-tests.txt, published online at https://docs.djangoproject.com/en/dev/internals/contributing/writing-code/unit-tests/#running-the-unit-tests
```

I see that "Running the test suite" is also present at https://code.djangoproject.com/wiki/Sprints
It may be also useful in CONTRIBUTING.rst?

I hope it is useful, thanks for your work.
Luca

**Comment by timgraham** [comment]
Added in https://github.com/django/django/commit/074706c64d1e125e31dd0eeced04231eeb3eedd8. Thanks for the suggestion.
