### ISSUE TITLE
"Transifex" points to a deprecated link

### ISSUE THREAD

**Issue by zhang-z** [django/djangoproject.com#455]
A very minor issue, on page https://code.djangoproject.com/newticket, the "Transifex" link points to https://www.transifex.net/projects/p/django/, which shows SSL certificate expired error. I supposed "https://www.transifex.net" was deprecated and should be replaced by "https://www.transifex.com"

**Comment by timgraham** [comment]
Fixed in https://github.com/django/code.djangoproject.com/commit/5266fb8fbd123fe87ddd2f011e5d0436bbc8f683, thanks.
