### ISSUE TITLE
display: none on "The web framework for perfectionists with deadlines."

### ISSUE THREAD

**Issue by evildmp** [django/djangoproject.com#461]
The only place the "perfectionists with deadlines" text is visible now is in the `<title>`, because:
```
<p class="meta">The web framework for perfectionists with deadlines.</p>
```
has a ```display: none``` on it.

That's such a nice tagline, and it seems a shame not to make at least a good use of it as was made previously.

**Comment by relekang** [comment]
It may be a browser issue, I get it with `display: block;`.  Could you please provide info about which browser you run so it is easier to reproduce?

**Comment by bmispelon** [comment]
It seems to be a screen size issue.

If the screen width is < 1150px then the tagline is hidden to make room for the menu.

While I do like this tagline, I'm not convinced that this behavior should be changed but I don't have strong feelings against it.

**Comment by timgraham** [comment]
I think it's okay as designed.
