### ISSUE TITLE
last_login database field doesn't update to null=true when appling migrations

### ISSUE THREAD

**Issue by LondonAppDev** [django/djangoproject.com#462]
In Django 1.8 the `last_login` field can now be null. If you have an existing Django implementation with a custom user model, then applying the new Django migrations using `python manage.py migrate --fake-initial` does not modify this field to accept null values.

I have detailed all the information here:
http://stackoverflow.com/questions/29913612/upgrading-from-django-1-6-with-south-to-1-8-doesnt-modify-last-login-on-the

**Comment by bmispelon** [comment]
Hi,

This is the ticket tracker for the website of djangoproject.com, not for the framework.
Would you mind re-opening your issue at https://code.djangoproject.com/newticket (and maybe make sure it hasn't been reported yet)?

Thanks!
