### ISSUE TITLE
Pagination (releases) should work the other way

### ISSUE THREAD

**Issue by chimeno** [django/djangoproject.com#463]
I just saw in https://docs.djangoproject.com/en/1.8/releases/1.7.8/ and related that the pagination is working in the other way I expected, in the left side the newer one and in the right side the older one.

I may be expected the other way:
Left side: older on release.
Right side: newer release.

**Comment by timgraham** [comment]
Thanks for the suggestion, but I don't think we're going to change it since it would require listing the oldest releases first in the table of contents.
