### ISSUE TITLE
DjangoCon EU missing in upcoming events list

### ISSUE THREAD

**Issue by shaib** [django/djangoproject.com#466]
On the right side of https://www.djangoproject.com/weblog/

@bmispelon took a glance and thought it should have been there.

**Comment by jezdez** [comment]
Seems like the ordering doesn't work correctly.

**Comment by bmispelon** [comment]
#467 ought to fix this.

Thanks for the heads up.

**Comment by bmispelon** [comment]
Merged, thanks! :boar:
