### ISSUE TITLE
Validate blog.Entry.summary before saving

### ISSUE THREAD

**Issue by bmispelon** [django/djangoproject.com#469]
Right now, it's possible to add a blog entry with a `summary` containing errors (say a rst link with no reference, like ``` `foobar`_ ```).

When this happens, the page listing all the post shows an unfriendly error message:
![458fb7e1_o](https://cloud.githubusercontent.com/assets/6345/7696864/18b6a4a0-fe02-11e4-8add-de3e6b7eb100.png)

Ideally, the admin form validation should catch that and not allow saving an invalid summary (or body for that matter).

**Comment by relekang** [comment]
#507 contains a proposed solution. However, as @timgraham pointed out it might be more hassle for the user than it is worth. I'm out of ideas on how to make it better. Suggestions are very much welcome and I am happy to try out new ideas.

**Comment by timgraham** [comment]
Seems like more trouble than it's worth.
