### ISSUE TITLE
Repository does not have a LICENSE file

### ISSUE THREAD

**Issue by freakboy3742** [django/djangoproject.com#477]
Occasionally, it's helpful to point potential contributors at the djangoproject.com repository; however, there's no LICENSE file, so it's unclear if anyone is allowed to use the code they find, or the terms for contributing back.

**Comment by timgraham** [comment]
Is the license from Django itself appropriate?

**Comment by freakboy3742** [comment]
I imagine so; BSD should be as good as any other alternative.
