### ISSUE TITLE
Display the donation statistics (💸) correctly on new fundraising page

### ISSUE THREAD

**Issue by olasitarska** [django/djangoproject.com#480]
So with the new :sparkles: recurring donations, we need to change the way we display the fundraising campaign statistics (% of goal achieved, etc). 

The idea @oinopion has was to display the following things:
- a total sum of all donations (recurring and not)
- total sum of donations in the last X days (treat this as a goal - to, for example, get $20.000 every 90 days)
- display percentage of the goal achieved in the last X days 
- total number of donors

**Comment by timgraham** [comment]
@adriennefriend, do you think we need to make any changes or additions to the current statistics on the fundraising page? (besides resetting the goal when we "launch")

**Comment by adriennefriend** [comment]
Hiya Tim, great question! 

Typically the main things donors care about are: 
1) some kind of visual representation of progress
2) how many people have given
3) how much we've received to a certain date (and how it compares to our overall goal)

A sum of donations in the last x days is nice, but not necessary. 

I've attached a few visuals from successful campaigns. 

Side note, related to 1) above - the heart image that we're using is lovely, but could we use one that shows progress a little more clearly? For example, could the heart's pixels fill as we get closer to our goal? 

![campaign1](https://cloud.githubusercontent.com/assets/3959233/11486980/67286d9a-978a-11e5-8cdd-e520babd2bb9.jpg)
![campaign2](https://cloud.githubusercontent.com/assets/3959233/11486983/6b1fc6aa-978a-11e5-8f0a-8b5dea21bd7b.jpg)
![campaign3](https://cloud.githubusercontent.com/assets/3959233/11486985/6e8eaab8-978a-11e5-8db1-ca4436268714.jpg)

**Comment by timgraham** [comment]
The heart actually does change as the donations increase (it starts off all white and turns pink with donations). Maybe you want to open a new ticket for some specific changes if it's not obvious? I don't see anything we don't already have listed on the page, so I think we can close this issue.

**Comment by adriennefriend** [comment]
Done, thanks.
