### ISSUE TITLE
Improve readability of code examples allowing overflow scroll

### ISSUE THREAD

**Issue by srus** [django/djangoproject.com#488]
There are a couple of CSS rules for `<pre>` that avoid `overflow: scroll` in code examples, and makes a little difficult to read the code in small screens:

```css
white-space: pre-wrap;
word-wrap: break-word;
```

Please, remove those rules and let the code flow horizontally.

**Comment by timgraham** [comment]
As for me, I don't find horizontal scrollbars more helpful, and I'm not sure it's worth revisiting the decision that our designer made.
