### ISSUE TITLE
SelectDateWidget(empty_label) is not working

### ISSUE THREAD

**Issue by LABETE** [django/djangoproject.com#492]
Hi,

I was trying to use the SelectDateWidget(empty_label="Nothing") and the SelectDateWidget(empty_label=("Choose Year", "Choose Month", "Choose Day")) as is displayed in the example of the official site of Django version 1.8 but it is still displaying the dropdowns as mandatory and is not displaying an empty label "---" or "Choose Year" as an option

![screenshot from 2015-06-17 12_54_19](https://cloud.githubusercontent.com/assets/5135212/8215154/c97efb72-14f3-11e5-8702-15ebd674eacd.jpg)

![screenshot from 2015-06-17 12_54_58](https://cloud.githubusercontent.com/assets/5135212/8215404/31046d1c-14f5-11e5-9688-dce193d30b5b.jpg)

**Comment by timgraham** [comment]
From [the docs](https://docs.djangoproject.com/en/1.8/ref/forms/widgets/#django.forms.extras.widgets.SelectDateWidget.empty_label): "If the DateField is not required, SelectDateWidget will have an empty choice at the top of the list (which is --- by default). You can change the text of this label with the empty_label attribute."

Your date fields don't have `required=False`.

By the way, this is the ticket tracker for the djangoproject.com website. The correct tracker for bugs in Django itself can be found at code.djangoproject.com.

**Comment by LABETE** [comment]
Oh, I see, sorry for the error

Regards
