### ISSUE TITLE
Would it be possible to show a search bar on page not found page?

### ISSUE THREAD

**Issue by wimfeijen** [django/djangoproject.com#495]
Hi, when I go to a dead url, for example:
https://docs.djangoproject.com/en/1.3/ref/contrib/csrf/#subdomains

Would it be possible to show the search bar in the right column? 

Regards, Wim

**Comment by timgraham** [comment]
The search bar uses the current version the docs so for non-existent versions what would you want? The current stable version perhaps? It's probably feasible to implement.

**Comment by wimfeijen** [comment]
Yes, the current stable version would be brilliant! Thanks

**Comment by timgraham** [comment]
I guess I'm not seeing much advantage to the additional complexity here. A search box is one click away if you click on "Documentation" in the header anyway.
