### ISSUE TITLE
Make "Support versions" linkable

### ISSUE THREAD

**Issue by asendecka** [django/djangoproject.com#505]
Table on the page: https://www.djangoproject.com/download/ under "Supported versions" is very useful, but hard to find. It would be great to make it possible to link to the table. 

Ideally, https://docs.djangoproject.com/en/dev/internals/release-process/#supported-versions should link to the table, so it's easier to discover.

**Comment by timgraham** [comment]
Good idea. I won't be so lazy next time. :turtle:

**Comment by bmispelon** [comment]
:sparkles: :rabbit2: :sparkles:

**Comment by asendecka** [comment]
:rainbow: :ocean: :seedling: :sparkles: :zap: Thank you!
