### ISSUE TITLE
Nicer landpoint for new tickets

### ISSUE THREAD

**Issue by ewjoachim** [django/djangoproject.com#533]
When arriving to [this](https://code.djangoproject.com/newticket) page (for example, following the link from django's README.md) while not logged (try opening it in a private browsing session), user gets yelled at with "Error: Forbidden" and a sentace that might be not easy to grasp for non-experienced developers ("TICKET_CREATE privileges are required to perform this operation on Ticket #None. You don't have the required permissions." )

It says "you're currently not logged", it says "forbidden" but what it does not say is that loging in or signing up may help. Not very welcoming. Maybe we could do something (like redirecting the the login or sign up page (with a ?next=...) ?)

**Comment by timgraham** [comment]
https://github.com/django/code.djangoproject.com/issues/64 is a duplicate -- that's probably the correct tracker anyway.
