### ISSUE TITLE
Disable [source] links in search results

### ISSUE THREAD

**Issue by bmispelon** [django/djangoproject.com#534]
Example:

Searching for [color](https://docs.djangoproject.com/en/1.8/search/?q=color) gives the following result:
![search_django_documentation_django_-_2015-10-07_23 38 24](https://cloud.githubusercontent.com/assets/6345/10351951/9204c666-6d4c-11e5-80c6-ea81dfa34d5b.png)

Personally, I've never found those results to be particularly useful and I think it'd be better to simply remove them (rather than trying to score them lower in the search results).

From what I remember, we didn't have those before so I think it must have been a sphinx update that brought them on (and I'm fairly sure it's unrelated to the search refactor with elastic because I remember seeing those results before).

**Comment by charettes** [comment]
Another related issue I remember from interacting on #django is that people assumed some API were public because they showed up in the documentation.

**Comment by timgraham** [comment]
Those pages are added for the [source] links: https://github.com/django/django/commit/9ed4a8c6b1a552a03fd27b77f1b742e3f9c66bde. It might be feasible to exclude them from elasticsearch's indexing.

**Comment by bmispelon** [comment]
Seems like there's some code that tries to do that but i guess somehow it's not working: https://github.com/django/djangoproject.com/blob/master/docs/search.py#L167-L169

**Comment by bmispelon** [comment]
I did some research with @HonzaKral on this and it turns out the offending line is in the `update_docs` management command: https://github.com/django/djangoproject.com/blob/master/docs/management/commands/update_docs.py#L196.

The line pointed out in my earlier comment is only used for two things:

* Looking for an exact title match in the search query (if the search query matches a page's title exactly - case and all - then the user is redirected to that page).
* When running the `update_index` command.

I suggest the following approach:

* Remove all indexing logic from `update_docs` (this has the nice side effect of not requiring a working install of elasticsearch to run that command anymore)
* Deploy the docs using `update_docs && update_index --delete`


One question that remains is how much time it takes to rebuild the index every time. Can someone with access to the server give us an idea?
