### ISSUE TITLE
Sitemap is broken

### ISSUE THREAD

**Issue by aaugustin** [django/djangoproject.com#535]
https://docs.djangoproject.com/sitemap.xml shows bad URLs e.g.

    <url>
        <loc>https://www.djangoproject.comhttps://docs.djangoproject.com/en/dev/./</loc>
        <changefreq>daily</changefreq>
        <priority>0.5</priority>
    </url>

**Comment by timgraham** [comment]
Pull request: https://github.com/django/djangoproject.com/pull/544 (needs tests)

**Comment by timgraham** [comment]
Duplicate of https://github.com/django/djangoproject.com/issues/472.
