### ISSUE TITLE
Donate page is kinda broken

### ISSUE THREAD

**Issue by adrienbrunet** [django/djangoproject.com#538]
If you try to reach the donate page via the forms "Donate 25$", you perform a 'GET' request on https://www.djangoproject.com/fundraising/donate/?amount=25.00, the view is expecting a 'POST' and you get a really nice blank page. Not cool.

**Comment by adrienbrunet** [comment]
@ewjoachim and myself are working on it (under the hood sprint)! :smiley:

**Comment by timgraham** [comment]
@adriennefriend -- This is about the donation box on the right side of https://www.djangoproject.com/foundation/donate/ (it leads to a blank page). We could fix this or simply remove the box and link the "Donate..." text to https://www.djangoproject.com/fundraising/.

One possible point of confusion from @ewjoachim if we keep the box: "And I'm a little uncomfortable with a small nice form saying "25$ :heart:" that redirects you to "Oh so you wish to give us 25$ a month ?". I know I, as an user, wouldn't be comfortable with this." We can make the box create a one-time donation, but then we never present the user with the option of making a recurring donation (I think) which doesn't seem ideal.

**Comment by adriennefriend** [comment]
If we are to offer opportunities to make donations on places other than the main fundraising page, we should present the same experience each time (which includes an option for recurring). If this is not possible, we should use links to the main page instead.

Would @ewjoachim feel comfortable telling me more about his discomfort with the form? We may be discontinuing this anyway, but I would the chance to hear more about why it makes him uncomfortable.

**Comment by ewjoachim** [comment]
I completely agree with this.

Concerning discomfort (in the context of a form with juste an amount that goes to a recurring donation form), if you're talking about an amount of money without mentioning a frequency, I guess I'd be inclined to think it's a one-off. Recurring payments are not that usual. So if I see a form asking for, say, $25 and I click, I expect it will cost me $25, not $25 every month. With the UI as-is, having a "amount only" form redirecting to a pre-filled recurring donation form feels to me a like a "bad surprise". When you've clicked on the form you've removed a psychological barrier and you're ready to give money and you're comfortable with the amount you entered. And now the website is suddenly asking for a lot more. That's what I'm referring to as "not comfortable". 

This being said, I'd be totally comfortable with a simple link to the current campaign, which will give a far better explanation on what we need the money for (and then maybe helping people to give more, to understand why recurring is better, etc.)

**Comment by timgraham** [comment]
I removed and/or replaced the donate boxes with a link. Thanks!
