### ISSUE TITLE
As of today, can one add a feed to the "Community blog posts"?

### ISSUE THREAD

**Issue by alexmorozov** [django/djangoproject.com#541]
I've submitted my blog feed a couple days ago, but it still doesn't show up. Is it because of #511 , or the moderation process simply takes a bit longer?
Just in case: the feed is https://alexmorozov.github.io/feeds/tag-django.atom.xml .

**Comment by timgraham** [comment]
I've just approved your feed, so new posts should now appear.

**Comment by alexmorozov** [comment]
@timgraham , blazing fast, thank you!
