### ISSUE TITLE
Blog Posts not appearing in Django Community feed

### ISSUE THREAD

**Issue by lferrari** [django/djangoproject.com#542]
Hi, 
a couple of months ago I added a feed to the Django Community blog but any of the posts are published in the Django community blog.

I think that the feed is already approved but I don't know why the posts are not showin up, could it be #511 issue?

Just in case the feed is http://blog.octobot.io/category/pythondjango/feed/
Thanks.
Luciano

**Comment by timgraham** [comment]
The latest post in that feed is August 14. Only new posts will appear after the feed is approved.
