### ISSUE TITLE
Donate page is kinda broken for Bitcoin

### ISSUE THREAD

**Issue by rossigee** [django/djangoproject.com#549]
![dj-bitcoin-not-configured](https://cloud.githubusercontent.com/assets/5194485/11235352/66971416-8e03-11e5-8c81-a487c1fc97b6.png)

**Comment by olasitarska** [comment]
Fixed it. Thanks!

**Comment by timgraham** [comment]
Are we allowed to accept Bitcoin? https://www.djangoproject.com/foundation/donate/ says no.

**Comment by olasitarska** [comment]
Technically, Stripe is receiving bitcoin, we're receiving USD $.

**Comment by timgraham** [comment]
Okay, I'll revise that answer to say, "Yes, choose the "Bitcoin" option  on the Stripe payment page." if that sounds okay.

**Comment by olasitarska** [comment]
Awesome!

**Comment by rossigee** [comment]
@olasitarska - https://www.djangoproject.com/fundraising/donate/?amount=10 now just giving me a blank page. I got to it by putting 10 into the donate widget in the right-hand sidebar and clicking the love icon.

@timgraham - i don't use banks or credit cards, or paypal, due to my political beliefs - i just use Bitcoin, and I use Django, and I enjoy donating to open source projects - it doesn't mention anywhere on your site that you accept Bitcoin, so I was expecting to drop out at the checkout, like I do on so many projects other projects I come across - in this case, I was pleasantly surprised that the Bitcoin option was actually there at the end (and also glad that reporting this misconfiguration was quickly and easily possible via github tickets!) - so, yes, i think you'd get a few more donations if you were to update your donate page FAQ answer to 'Yes', and perhaps more if you also made it a bit more obvious from the front that you *do* take Bitcoin, and not just the usual traditional bunch of methods :)

**Comment by timgraham** [comment]
The blank page issue is tracked in https://github.com/django/djangoproject.com/issues/538.

Donation FAQ is updated. Thanks!
