### ISSUE TITLE
Remove $5 and $25 choices from fundraising page

### ISSUE THREAD

**Issue by timgraham** [django/djangoproject.com#554]
From @adriennefriend: We should remove the US $5 and $25, because they don't really make sense to suggest. If someone really wants to just give $5 or $25, they can use the other amount to write it in.

**Comment by timgraham** [comment]
What about that amount as a recurring donation?

**Comment by adriennefriend** [comment]
Ah, if we have them on the same page, then it should be left up. :) Good catch!

**Comment by adriennefriend** [comment]
Even if it is a recurring donation, people can still use the other write in.
