### ISSUE TITLE
Donor report

### ISSUE THREAD

**Issue by adriennefriend** [django/djangoproject.com#557]
Hi there! I need a report that will show the following info:

Donor name, Donor email address1, Donor email address for email receipt2, Last gift date, Gift amount, and Interval

Columns should be in that order.

1 and 2 - occasionally these differ, so I want both.

Please only return entities who have said it is okay that they be contacted by the DSF, as I am using this information to build out a list of individuals who I intend to contact for donations.

Thank you!

**Comment by timgraham** [comment]
Would it be simpler for you if we include 1 email address column and only use the stripe email address if the other email address is empty?

For recurring donations, should the "Last gift date" be the date the recurring donation was created or the date of the last payment?

**Comment by adriennefriend** [comment]
Thank you for these questions, Tim! The only reason I was interested in the Stripe email address is because I noticed that sometimes the first email address is a general one, like "mycompany@mycompany.com", whereas the Stripe will be associated with some name, "tim@mycompany.com". If you think there will be issues with providing both, feel free to just do the one, and in case I run across an email address where I feel like I need more info, I can always just go back and look at it myself. :)

Great question about recurring! Definitely want the date of the last payment. Since there'll also be a "recurring" status column, I can make a mental note of that when I see it.

**Comment by timgraham** [comment]
Okay, I'll collapse the emails into one column (using the stripe email if the other is blank) and provide a separate "alternate email" column if the stripe email differs from the other one.

**Comment by timgraham** [comment]
How about a column or indication in the "interval" column about whether or not the recurring donation is active? At least one person signed up for recurring donations by mistake and immediately canceled it. If you email them about their recurring donation, it'll cause confusion.

**Comment by adriennefriend** [comment]
That's definitely helpful, Tim, thanks! Always good to hear of little outliers like that.

Could you point me in the direction of how to run the report myself, if that functionality is already available? And if not - no rush - just let me know when it will be. Thank you!

**Comment by timgraham** [comment]
You can run the report by going to https://www.djangoproject.com/admin/fundraising/djangohero/. Select "By Agreed to displaying on the fundraising page?" on the right side filters, use the check box to select all records, then choose "Action" -> "Download donor report".

**Comment by adriennefriend** [comment]
Awesome, Tim, that worked beautifully. Only I selected "Agreed to be contacted by DSF" because that was more my interest. Thanks for building this out! It's fantastic.
