### ISSUE TITLE
Provide updated page text for fundraising page.

### ISSUE THREAD

**Issue by timgraham** [django/djangoproject.com#563]
We need new text for https://www.djangoproject.com/fundraising/ before we launch the next round of fundraising. The text should describe both the fellowship program and the other activities of the DSF and make it clear that donations aren't earmarked for any specific purpose. To that end, I'm not sure if it makes sense to keep the "1 hour, 1 day, etc." descriptions next to the donation amounts.

A related page which has some info that might be useful: https://www.djangoproject.com/foundation/donate/

**Comment by adriennefriend** [comment]
Thanks very much! I'm still waiting on copy from the DSF Board (particularly the Treasurer and Secretary) about our activities and successes in 2015 before I can craft this text. 

You bring up an important point about donor intent that I'll be mulling over.

**Comment by timgraham** [comment]
Pull request for review: https://github.com/django/djangoproject.com/pull/589
