### ISSUE TITLE
Add an optional field on donation form to collect donor location

### ISSUE THREAD

**Issue by adriennefriend** [django/djangoproject.com#567]
When reviewing our donor report, I realized it would be helpful to know where our donors are located, for the purpose of planning travel and publicizing the option to meet with donors at Python & Django conferences. 

Is there a way we could request this information (optionally) at the point at which donors make gifts? Optional is important - I don't want anyone to feel like they have to note their city/country, but if they're willing to, great.

**Comment by timgraham** [comment]
What's the exact text you want to use to prompt for the info? You can see the other fields on the form at https://github.com/django/djangoproject.com/blob/38343c0acde80969f7210be4487a94b35b027dea/fundraising/forms.py#L12-L57.

**Comment by adriennefriend** [comment]
Good question, Tim - thanks for linking me to the form.

I think we can keep it simple - just ask "Where are you located?" (optional) and put it between "Your name or the name of your organization" and "Which URL should we link your name to?"
