### ISSUE TITLE
First recurring donation doesn't get a receipt from Stripe

### ISSUE THREAD

**Issue by timgraham** [django/djangoproject.com#575]
See screenshot for ordering of actions (seems like the email is set after the invoice and charge happen):

![actions](https://cloud.githubusercontent.com/assets/411869/11664103/c64b1d26-9dad-11e5-9405-7347ccfceee0.png)

**Comment by timgraham** [comment]
@danielroseman, I wonder if you can quickly spot the issue here?

**Comment by danielroseman** [comment]
We don't do anything to set the email, the user enters that directly into the modal dialog created by the third-party Stripe JS; in fact we use the value that Stripe returns from there to populate the email field in DjangoHero. So it's definitely not anything to do with the order of those actions.

The [Stripe subscription docs](https://stripe.com/docs/guides/subscriptions#invoices) do state that the initial invoice isn't actually sent to the customer. I don't know if the payments themselves are supposed to trigger an email. We might need to do this ourselves, by adding something that listens to the `invoice.payment_succeeded` webhook.

**Comment by timgraham** [comment]
When this happens, the Stripe UI says "No receipts sent — No email address for this payment".

**Comment by timgraham** [comment]
I don't have time to test until tomorrow, but possibly adding `email=receipt_email` to [stripe.Customer.create](https://github.com/django/djangoproject.com/blob/65689e42deacf30516583706f334e0b5b045126d/fundraising/forms.py#L204) would work.

**Comment by adriennefriend** [comment]
Hi Tim, Sorry to ask you about a closed issue - just curious if you were able to get the receipt working for first-time recurring donation? I'm still playing catch-up from last week.
