### ISSUE TITLE
Searching for "verb" doesn't yield results for "verb+ing"

### ISSUE THREAD

**Issue by bmispelon** [django/djangoproject.com#576]
I noticed this while searching for "[unapply](https://docs.djangoproject.com/en/1.9/search/?q=unapply)".

Notice how it doesn't include a search result for [this page](https://docs.djangoproject.com/en/1.9/ref/migration-operations/#django.db.migrations.operations.RunPython) which includes the word "unapplying".

Is that a deliberate behavior?

**Comment by pauloxnet** [comment]
After merge of this Pull Request the search you wrote about now is working

https://docs.djangoproject.com/en/dev/search/?q=unapply

contains a link to

https://docs.djangoproject.com/en/dev/ref/migration-operations/

@timgraham I think you can close this issue
