### ISSUE TITLE
Check "Corporate Membership" edits

### ISSUE THREAD

**Issue by timgraham** [django/djangoproject.com#583]
Please check https://www.djangoproject.com/foundation/corporate-membership/ for accuracy of edits based on the new membership structure.

**Comment by shaib** [comment]
Are "corporate members" edits included in this? Either way, I think XtremIO's description is missing a word (we are developing "all flash arrays", not "flash arrays"; it's a well-known term in the storage industry).

**Comment by timgraham** [comment]
Those descriptions were copied from the original flat page and I suspect we didn't edit it in the first place.

**Comment by adriennefriend** [comment]
Hi @shaib, thanks for letting us know. We will update. If you want a fuller description, please let us know. https://www.djangoproject.com/foundation/corporate-members/

**Comment by adriennefriend** [comment]
Looks good to me. Thank you Tim!
