### ISSUE TITLE
Update Tweet template on thank-you page

### ISSUE THREAD

**Issue by timgraham** [django/djangoproject.com#584]
Currently it says "I just donated to support the Django Fellowship Program! Do it. https://www.djangoproject.com/fundraising/  #SupportDjango"

I guess we should at least change "Django Fellowship Program" to "Django Software Foundation" and maybe "Do it." to something like "Join me!"

**Comment by adriennefriend** [comment]
Yes! Let's use:

"I just donated to support the Django Software Foundation. Join me! https://www.djangoproject.com/fundraising/ #SupportDjango" 

Thank you Tim!
