### ISSUE TITLE
Remove "1 hour, etc." from donate form?

### ISSUE THREAD

**Issue by timgraham** [django/djangoproject.com#585]
Since the donation page is more about the DSF in general, should we remove the hour/day/week designations from the donate form? Maybe it's a good time to think about if we want to change the default amounts too.

**Comment by adriennefriend** [comment]
Good call. We do need to remove all time-based language.

Could you please update the drop-down to feature the following amounts:

50
100
250
500
750
1000
1250
2500

**Comment by adriennefriend** [comment]
Tim, Sorry - could you add $25 back, please?

**Comment by timgraham** [comment]
Done
