### ISSUE TITLE
Change "Django Heroes" header to something else

### ISSUE THREAD

**Issue by adriennefriend** [django/djangoproject.com#591]
We're designating "Heroes" as anyone who gives a gift any amount to the DSF (contrasting with Leaders, who give $1000 and above). Therefore, we should change the "Django Heroes" header to something else. 

"Our Donors"? "Supporters"? "DSF Donors"?

**Comment by timgraham** [comment]
Have changed it to "DSF Supporters" in https://github.com/django/djangoproject.com/pull/589.
