### ISSUE TITLE
Run on link/bad text on corporate membership page

### ISSUE THREAD

**Issue by adriennefriend** [django/djangoproject.com#593]
On https://www.djangoproject.com/foundation/corporate-membership/, under "How do I become a member?" there should not be a "Fill out our dues" line, and most of that section should not be clickable links. 
![corporate-member-page](https://cloud.githubusercontent.com/assets/3959233/11855179/a36f1db0-a416-11e5-811a-153a90581491.jpg)

**Comment by timgraham** [comment]
Oops, added the missing quote in the HTML.
