### ISSUE TITLE
Remove old donors - calendar is reset

### ISSUE THREAD

**Issue by adriennefriend** [django/djangoproject.com#596]
Today we announced our new campaign and reset the ticker to 0. 

This means we need to remove most of the out of date donors from the donor roll below.

**Comment by timgraham** [comment]
I thought we agreed to display all donors who have given in the past 365 days? Otherwise we penalize donors who give at the end of a campaign.

**Comment by adriennefriend** [comment]
We talked it through, but essentially, it doesn't make sense to have our heart at 0% funded and then this giant donor roll below. Technically, the people who gave under the last campaign, should have been recognized up until we announced the new one today. And anyone who gives today forward should be recognized through next December.

**Comment by adriennefriend** [comment]
Ideally we would feature:

1) Anyone who gave in December 2015, since we didn't send them an email about a second gift (will do in the spring)
2) All current corporate members
3) Anyone who gave to the new campaign

It's not an incentive to make a new gift and have your name/logo featured as part of the new campaign if it's still up for the old one. 

What do you think?

**Comment by timgraham** [comment]
Many people will fall off in mid-January since that's when we started the last campaign. I think the current scheme is simple and straightforward. The page even says, "Our donor roll for all donations made in the last 365 days."

**Comment by adriennefriend** [comment]
Makes sense! We can close this for now, then.
