### ISSUE TITLE
OddBird mistakenly dropped from DSF Corporate Members page

### ISSUE THREAD

**Issue by adriennefriend** [django/djangoproject.com#598]
Hi all, Received a kind note from @carljm at OddBird noting that the company was mistakenly dropped from the DSF Corporate Members page. Their membership is currently and our summary for them should be re-added to https://www.djangoproject.com/foundation/corporate-members/.

Logo and link should also be featured on the main fundraising page under Silver Corporate Members ($2,000+).

OddBirds thrive on shared ideas & playful collaboration, crossing disciplines, breaking boundaries, and eating dessert with the soup spoon. From open-source tools like Django, Compass, and Susy to bespoke web applications to experiments in digital storytelling — we love molding ideas into experiences for humans.

**Comment by timgraham** [comment]
To fix this, correct their membership record at https://www.djangoproject.com/admin/members/corporatemember/20/. I guess the "expires" date in the spreadsheet was off by 1 year.

**Comment by adriennefriend** [comment]
Thanks for pointing me here! I do not see a place to adjust an expires date.

**Comment by timgraham** [comment]
Forgot to assign you the correct permissions, please look again.

**Comment by adriennefriend** [comment]
Adjusted, thanks!

Do I need to make a separate request for getting their logo added to the fundraising page?

**Comment by timgraham** [comment]
You can upload their logo on that same page.

**Comment by carljm** [comment]
If you need our logo, it's at http://files.oddbird.net/oddlogo.png or http://files.oddbird.net/oddlogo.svg. PNG version is logo only, no wordmark, which might be fine here since the company name is underneath anyway.

**Comment by timgraham** [comment]
Thanks, uploaded the png.

**Comment by carljm** [comment]
Thanks!
