### ISSUE TITLE
Lincoln Loop's logo not displaying correctly under Silver Corporate Sponsors

### ISSUE THREAD

**Issue by adriennefriend** [django/djangoproject.com#601]
I just added Lincoln Loop, a new Silver Corporate Sponsor, to our Corporate members using the admin interface. I uploaded their logo, but it does not appear on the main fundraising page - instead, a heart is appearing.

**Comment by timgraham** [comment]
It looks good to me now. Our website caches most pages for 5 minutes so that might be what happened here.

**Comment by adriennefriend** [comment]
Oh great, thank you!
