### ISSUE TITLE
Add internal dashboard of key data for corporate members

### ISSUE THREAD

**Issue by timgraham** [django/djangoproject.com#606]
We should add some additional columns in the admin view to see the membership data at a glance. Two  additions are the expiration date of their membership and whether or not they need to be invoiced (this would let the treasurer login and easily see what needs to be done).

![member-data](https://cloud.githubusercontent.com/assets/411869/12059612/a092f528-af2c-11e5-8a16-0da11b6befbb.png)

**Comment by timgraham** [comment]
@adriennefriend, can you think of anything else useful to add?

**Comment by adriennefriend** [comment]
Thanks for thinking of this, and for asking! I agree that expiration date is probably the most important data point. I would also add "effective date" for viewing at a glance. The only other thing I can think of that might be helpful is membership level: Silver, Gold, Platinum, or "Other". 

I really like what you've done and will support & appreciate how you implement!

**Comment by timgraham** [comment]
How would "effective date" be calculated? Since we're adding members to the website before they pay or are invoiced, I'm not exactly sure what you have in mind for what the column is supposed to represent.

The data will be added to https://www.djangoproject.com/admin/members/corporatemember/ which already has membership level.
