### ISSUE TITLE
Improve UX to prevent accidental recurring donations

### ISSUE THREAD

**Issue by timgraham** [django/djangoproject.com#608]
More than once we've had someone inadvertently signup for recurring donations.  We could change the default option from "Monthly" to "One-time", or update the Donate button so that it reflects the selected interval and reads something like "Donate Monthly".

**Comment by adriennefriend** [comment]
I'm all for either - whatever is easier for you to implement. I know I suggested changing the default option, but I'm partial to your idea of updating the donate button.
