### ISSUE TITLE
Create a model to track foundation meeting minutes

### ISSUE THREAD

**Issue by timgraham** [django/djangoproject.com#609]
Currently all board meeting minute pages are flatpages.

This idea is to create a "foundation" app with a `BoardMinutes` model that has a few fields: date (of meeting), body, content_format (html or restructured text, like the `Entry` model in the `blog` app).

Then add a few views to automate generation of the minutes pages (e.g. /foundation/records/minutes/2015-08-06/) and the index (/foundation/records/minutes/) instead of using flatpages. We'll link to the new index page from https://www.djangoproject.com/foundation/records/.

**Comment by Saurabh-Singh-00** [comment]
Hey!, I have completed the feature but stuck at rendering the restructured text in django template. The HTML template renders correctly using the safe filter. Is there any filter for restructured text ? I hopped around sphinx documentation but couldn't find any way to render restructured text in templates. 
![restructured text](https://user-images.githubusercontent.com/36993159/52568866-ee706b00-2e35-11e9-9814-0d70c93a27bb.png)

**Comment by timgraham** [comment]
You can use a similar approach to https://github.com/django/djangoproject.com/blob/33047d71fa4bb1f1eabb38128482427b1067e5f2/blog/models.py#L93-L99

**Comment by Saurabh-Singh-00** [comment]
I have also added a view to add board minutes. I just needed to ask that only admin and users with staff status can add board minutes?
![screenshot from 2019-02-17 13-31-48](https://user-images.githubusercontent.com/36993159/52910082-6ae0cf00-32b8-11e9-9f47-35c12b143db6.png)

**Comment by timgraham** [comment]
We can use the admin add view. A separate view isn't needed.

**Comment by Saurabh-Singh-00** [comment]
So, I guess the work is done?

**Comment by timgraham** [comment]
Please send a pull request so we can see what's done.

**Comment by Saurabh-Singh-00** [comment]
> Please send a pull request so we can see what's done.
My pull request failed. Before updating my master branch I pulled the latest changes from upstream. What should I do now?

**Comment by timgraham** [comment]
You'll need to remove the unrelated changes from the PR. It should be a single squashed commit. You might look at https://docs.djangoproject.com/en/dev/internals/contributing/writing-code/working-with-git/ if you don't have much experience with Git.

**Comment by ubernostrum** [comment]
Could you hold off on this? As the person who'd actually have to use it (I'm the current Secretary of the DSF), I'd like to build this myself to suit the needs of the Board.

**Comment by Saurabh-Singh-00** [comment]
It took me a month to complete this (because of my exams). Can you just check my work and see it, if you think you should continue or extend my work, please merge my work and continue from there or if you would like to startup from scratch I could hold on, not a problem. I am a newbie to open source contribution, so I took this easy picking. I don't mind holding on this issue.
Foundation App -
https://github.com/Saurabh-Singh-00/djangoproject.com/tree/master/foundation

> Could you hold off on this? As the person who'd actually have to use it (I'm the current Secretary of the DSF), I'd like to build this myself to suit the needs of the Board.
