### ISSUE TITLE
NASA might be moved from Django to Drupal under "Sites Using Django" on the Overview tab(https://www.djangoproject.com/start/overview/))

### ISSUE THREAD

**Issue by vaibhavgb** [django/djangoproject.com#615]
![s2](https://cloud.githubusercontent.com/assets/8201144/12212499/2cd9ae08-b691-11e5-904d-c30336f92b05.png)

**Comment by timgraham** [comment]
Also rdio is defunct and The Guardian seems to use Scala based on their job postings.
