### ISSUE TITLE
Google search results displaying doc pages not in preferred language.

### ISSUE THREAD

**Issue by timgraham** [django/djangoproject.com#621]
Searching Google will often turn up docs pages that aren't in your preferred language. We should figure out how to fix this. Possible solution: https://support.google.com/webmasters/answer/2620865?hl=en

**Comment by olasitarska** [comment]
Also, maybe this? https://support.google.com/webmasters/answer/189077?hl=en

Just stumbled upon this webmasters answer today.

**Comment by timgraham** [comment]
Looks like the `hreflang` addition from David is working. Now I'm always seeing English results here. Thanks for the suggestion Ola!

**Comment by rfleschenberg** [comment]
If my browser language preference is set to [German, English], I still find the French (or sometimes the Japanese) docs instead of the English ones. If I set it to to [English, German], I find the English ones.

I'm no expert on this, but maybe we could make use of ``hreflang="x-default"`` for the English docs?

Also, isn't it a little weird that https://docs.djangoproject.com/ja/1.9/releases/security/ exists, but has English content? Should we open another issue for this?

**Comment by timgraham** [comment]
1. [Google says](https://support.google.com/webmasters/answer/189077?hl=en): 

    > For language/country selectors or auto-redirecting homepages, you should add an annotation for the hreflang value "x-default" as well:
   `<link rel="alternate" href="http://example.com/" hreflang="x-default" />`

 It's not obvious to me that your proposal is the correct usage of `x-default` but I'm new to this as well.

2. [The alternate languages are added](https://docs.djangoproject.com/en/dev/internals/contributing/localizing/#documentation) as soon as `docs/intro` is translated. English content will appear elsewhere until more translations are completed.

**Comment by rfleschenberg** [comment]
Yes, Google's documentation on this is confusing to me, too. If I understand this page correctly, it would be ok to use it in this case: https://webmasters.googleblog.com/2013/04/x-default-hreflang-for-international-pages.html

**Comment by timgraham** [comment]
I guess there's not much harm in trying. Care to submit a PR?

**Comment by rfleschenberg** [comment]
I'm quite unfamiliar with the relevant codebase, but I can create a PR if you allow me some time for it :)

**Comment by rfleschenberg** [comment]
Seems to be working better now -- thanks @gbdlin.

**Comment by timgraham** [comment]
Actually that commit isn't merged or deployed (https://github.com/django/djangoproject.com/pull/649).

**Comment by rfleschenberg** [comment]
Oh, right. And I can still reproduce the issue if I use a private browsing session. I will send a PR.

**Comment by rfleschenberg** [comment]
Unfortunately, I am still seeing this issue. Either the fix from 0ac648b is not working, or Google is really slow to pick up the change. Maybe someone with access to the Google Webmaster tools or such can do some further analysis on this?

**Comment by timgraham** [comment]
Not sure if we have Webmaster Tools setup. I likely won't prioritize this myself before the 1.10 feature freeze, but I'll reopen this issue.

**Comment by apollo13** [comment]
I just enabled it. On a quick glance, 0ac648b17c399f85810d72123c1cfe2452fb5810 is wrong -- we should still keep hreflang="en" there and have "x-default" in addition to en.

**Comment by rfleschenberg** [comment]
I was trying to follow the example from https://webmasters.googleblog.com/2013/04/x-default-hreflang-for-international-pages.html, but it is entirely possible that I misunderstood it :)

**Comment by apollo13** [comment]
I was mainly following the example at https://support.google.com/webmasters/answer/189077?hl=en

**Comment by apollo13** [comment]
After reading a little bit more (especially: http://www.rebelytics.com/hreflang-canonical/ and http://www.thesempost.com/google-alerts-webmasters-issues-hreflang-relcanonical-urls/ )

I think that google is ignoring hreflang completely since our canonical links do not match any alternate link. Proposed solution (following the second picture of the first linked article):

If we want google to index all Django versions: change the canonical to point to the latest version and serve duplicate content. Put hreflang links as currently onto the versioned pages (not on the stable one though!).

If we want google to just index one version: point every versioned page to /stable/ (canonical) and only put hreflangs there.

Either way we should remove the redirect from the "canonical" url (stable currently) back to a versioned one -- this seems to utterly confuse google.

**Comment by gbdlin** [comment]
From my point of view most confusing part for google is almost same (not translated) content. I'm pretty sure that google is able to check actual language of site based on it's content and if it doesn't match tags, ignores them. 

In my opinion pages that aren't translated in more than 50% shouldn't be visible for google (what is the point of indexing them anyway...).

**Comment by apollo13** [comment]
@gbdlin Cause figuring out which pages are actually translated and which not is hard. Setting a canonical link and hreflang is easy and lets google do the right thing (even if that means showing half translated docs for spanish users etc…). Google can handle the current situation if we properly set the links.

**Comment by apollo13** [comment]
What do you think about https://github.com/django/djangoproject.com/compare/seo

**Comment by rfleschenberg** [comment]
Looks great to me. Thank you for doing the research on this!

**Comment by apollo13** [comment]
Ok, I've pushed it to master -- lets see if google picks up a few hreflang tags over the next days.

**Comment by apollo13** [comment]
Changed a few things around, but the results are starting to look promising: Searching "django auth" on google.at gives me english as first match. Searching on google.fr gives me the french translation first!

**Comment by timgraham** [comment]
I think we're done for now.

**Comment by apollo13** [comment]
Indeed :)

**Comment by ulope** [comment]
Unfortunately I think there is still something wrong here.

Various combinations of accept-language localized google search page and available language version still seem to produce invalid results.

Example query: `django databases`

Physical location|Accept-Language|google.(.+)|1st result language|correct?
-----------------|-----------------|-----------|-------------------|--------
de|en-us|de|ja|
de|en-us|it|ja|
de|en-us|nl|ja
de|en-us|fr|fr|:white_check_mark:
de|en-us|es|es|:white_check_mark:
us|en-us|de|ja|
us|de,en-US;q=0.8,en;q=0.6|de|ja|
us|de,en-US;q=0.8,en;q=0.6|es|ja|
us|de,en-US;q=0.8,en;q=0.6|com|ja|
us|en-US,en;q=0.8,de;q=0.6|com|en|:white_check_mark:
us|it,en-US;q=0.8,en;q=0.6|de|ja|
us|it,en-US;q=0.8,en;q=0.6|it|ja|
us|es,en-US;q=0.8,en;q=0.6|com|es|:white_check_mark:
us|es,en-US;q=0.8,en;q=0.6|de|es|:white_check_mark:

All tests were done in "anonymous mode" and I repeated them with multiple browsers (Safari, Chrome, Firefox).

From this limited data set it seems that searches in languages for which no translated docs exist still default to the Japanese version.

**Comment by apollo13** [comment]
What do you get with physical location de and Accept-Languages set to:
```
en-US,en;q=0.7,de;q=0.3
```
and
```
de,en-US;q=0.7,en;q=0.3
```
I am getting _en_ in the first case and _ja_ in the second one. Nice debugging!

**Comment by apollo13** [comment]
Does something in Django set the proper language per request? Or can that https://github.com/django/djangoproject.com/blob/master/docs/views.py#L49-L50 result in leaking languages?

**Comment by ulope** [comment]
> I am getting en in the first case and ja in the second one.

Yes, I get that as well.

**Comment by gbdlin** [comment]
Looks like google discards information about page language, when this information does not match context of page. In my opinion only solution for that is to release documentation translated for certain language, when translations are done or nearly done.

**Comment by apollo13** [comment]
Looking at transifex, only the french translation would fit the criterion of "nearly done" (just from a percentage point of view), but I do not think that that is a feasible solution -- do we really have noone at google who can explain what we are doing wrong?

**Comment by rfleschenberg** [comment]
Doesn't it make more sense to say *"sorry, we do not have documentation in Klingon right now, here is a link to the English documentation"* than to say *"here is the Klingon documentation"* and then display content that is mostly in English?

**Comment by apollo13** [comment]
The thing is a) how to determine if we actually have enough translated content on this page and b) I think showing half translated documentation can have an positive effect and encourage people to submit more translations.

Either way, we cannot be the only one with such problems…

**Comment by gbdlin** [comment]
@apollo13 I haven't noticed French translation in my google search result from long time and I don't have french in prefered languages neither in google nor in browser, so I can say: having actually translated content helps.

I think good way to go is to put link to english (or other languages) version on pages that haven't been translated to language prefered by user. We will then have some content visible in that language.

**Comment by rfleschenberg** [comment]
For a), I would suggest the proven best practice of "ask a human" ;) 

b) is a very good point, I didn't think of that.

**Comment by jezdez** [comment]
I've stumbled over this a few times and wonder what the status about this is.

Whatever the technical solution is I think it hurts Django's reputation as having good documentation if we show half-translated documents to people coming from Google. So I'd suggest to role back shipping translated documentation for now until we've figured this out.

**Comment by gbdlin** [comment]
According to this document: https://support.google.com/webmasters/answer/182192?hl=en especially this fragment:

> Google uses only the visible content of your page to determine its language. We don’t use any code-level language information such as lang attributes. You can help Google determine the language correctly by using a single language for content and navigation on each page, and by avoiding side-by-side translations. 

Google will treat translations as duplicated content unless it is fully translated. I think best solution will be to add robots.txt file that will prevent google from indexing non-translated pages. Aparently there is no other solution.

**Comment by shaib** [comment]
On Tuesday 18 October 2016 11:03:44 GwynBleidD wrote:
> 
> Google will treat translations as duplicated content unless it is fully
> translated. I think best solution will be to add robots.txt file that will
> prevent google from indexing non-translated pages. Aparently there is no
> other solution.

I think there might be, but it may not be trivial,

Note that the problem is not really that Google finds an English page in the 
Spanish translation, but rather that links from that page point into pages 
which really are in Spanish; as long as English is displayed, having  `/es/` 
in the URL is not that bad. The problem is only that then we run into non-
English content.

But what if we could make it so that non-translated content links back to 
English pages?

I'm not sure how feasible this is -- I don't know the innards of sphinx nearly 
well enough -- but I think if it is, it would solve most of the problem.

**Comment by apollo13** [comment]
I think nuking the translated pages from orbit via robots.txt is the easiest technical approach.

**Comment by gbdlin** [comment]
@shaib the main problem is that google is showing URLs in results from pretty much random language, because it treats all urls as english. Second problem is actual non-translated content when someone enters from google, hoping for content translated to his/her language. Both of that problems can be solved using robots.txt.

Third problem is seeing untranslated content after changing language from english to any other one in documentation interface. This is in my opinion only solvable by translating everything and it's better to show something rather than nothing. We can add some information here that page is not fully translated and if you want, you can help translating it here and there.

Documentation isn't hosted on sphinx, it's an django app, so generating robots.txt file shouldn't be a problem. Only problem left is to decide when to switch from not indexing certain page to indexing.

**Comment by m-aciek** [comment]
@gbdlin Google says "Make sure the page language is obvious" ( https://support.google.com/webmasters/answer/182192?hl=en ). I would suggest treshold of 90% or 100% of translated content.

**Comment by timgraham** [comment]
@claudep, it seems you're missing out on this thread. Let us know if you have any ideas or preferences here.

**Comment by claudep** [comment]
The `robots` idea might indeed be the best track to follow. I'm not sure it will be feasible to automate it, but even if I had to manually manage it, I could do it as I'm the one which currently sync periodically translated content from Transifex to djangoproject.com.

**Comment by apollo13** [comment]
@claudep I was thinking about writing a simple view which just disallows everything starting with a language prefix != en -- I think this is the best short-term solution for now

**Comment by claudep** [comment]
I'm volunteering to make something more fine-grained!
Otherwise, it would be an insult for the people having spent days or weeks to translate the docs on their free time (me included!).

**Comment by apollo13** [comment]
@claudep By all means, please do -- didn't mean to insult any one. I just hope this can be automated, otherwise it might be a lot to keep up with.

**Comment by claudep** [comment]
OK, tell me where the robots.txt should lie in the repository and I'll suggest something.

**Comment by apollo13** [comment]
Well, if it is static, you can basically put it anywhere and we will hook it up via Nginx -- if you want it dynamic make it a view in the docs app (should match docs.djangoproject.com/robots.txt).

**Comment by claudep** [comment]
I've just added a script to produce a robots.txt file in https://github.com/django/django-docs-translations/commit/8b160a17501ef1f14589e2f0bfd319d46b1ee787
which currently gives:
```
User-agent: *
Disallow: /el/1.10/internals
Disallow: /el/1.10/ref
Disallow: /el/1.10/releases
Disallow: /el/1.10/topics
Disallow: /es/1.10/howto
Disallow: /es/1.10/internals
Disallow: /es/1.10/misc
Disallow: /es/1.10/ref
Disallow: /es/1.10/releases
Disallow: /es/1.10/topics
Disallow: /fr/1.10/internals
Disallow: /fr/1.10/releases
Disallow: /id/1.10/ref
Disallow: /id/1.10/releases
Disallow: /id/1.10/topics
Disallow: /ja/1.10/faq
Disallow: /ja/1.10/howto
Disallow: /ja/1.10/internals
Disallow: /ja/1.10/misc
Disallow: /ja/1.10/ref
Disallow: /ja/1.10/releases
Disallow: /ja/1.10/topics
Disallow: /pt_BR/1.10/ref
Disallow: /pt_BR/1.10/releases
Disallow: /pt_BR/1.10/topics
```
Do you find acceptable to manually copy that script's result in the djangoproject.com repository, or should we automate more?

**Comment by claudep** [comment]
Oh, and I set the threshold to 90% of translated content to not be listed in robots.txt.

**Comment by apollo13** [comment]
Copying into the static files dir and adding nginx config seems good enough for me. Lets do that at DUTH sprints? Do you think it would make sense to also add disallows for older versions? I do know that they all set canonical to 1.10 and that should cause them to be excluded, but not 100% sure to be honest.

**Comment by m-aciek** [comment]
@claudep I thought of 90% treshold at greater granulation – I mean treshold of 90% per every docs' article. Does implementation of that is achievable, what do you think?

**Comment by apollo13** [comment]
@m-aciek In it's current form of the translation system, this information is not available as far as I can tell (That is po-files do not come with context information about which file a string belongs to etc iirc). While it would be nice to add it at some point, I think it is even way more important to add a simple system now to see how Google behaves

**Comment by claudep** [comment]
What apollo13 said…

**Comment by claudep** [comment]
Attached a robots.txt with content for 1.10, 1.9 and 1.8
[robots.txt](https://github.com/django/djangoproject.com/files/566652/robots.txt)

**Comment by apollo13** [comment]
Ok, added to the repository: https://github.com/django/djangoproject.com/commit/5ce165431568e4da792e57d8777d51df4db3888a will add it to nginx in a second.

**Comment by apollo13** [comment]
Okay, changes deployed -- please give it a few days and then start commenting if you run into issues.

**Comment by apollo13** [comment]
@claudep I'll give it another week, but it might be that we actually have to fix this in the sitemap.xml too: http://www.digett.com/blog/04/15/2014/crawling-vs-indexing-robotstxt-and-sitemapxml

**Comment by claudep** [comment]
OK, I'll see if I can come up with something about sitemap.xml building.

**Comment by apollo13** [comment]
@claudep No need for a rush though, I was just testing with the nice table @ulope provided, and I am getting english results consistently now -- apparently google already picked it up mostly?!

**Comment by rfleschenberg** [comment]
Small test report:

Still getting `es` for: 

* `https://www.google.de/?q=django%20security%20advisories` 
* `Accept-Language:"de,en-US;q=0.7,en;q=0.3"`
* physical location Germany
* not logged in to Google

Getting `el` for `django databases` with the same configuration.

**Comment by apollo13** [comment]
Yeah, I am also getting _el_ on google.de, on .at I get _en_ -- that said, I also missread _el_ for _en_ on a first quick glance in the morning :D

**Comment by apollo13** [comment]
@rfleschenberg Still? I am seeing en in Austria at least.

**Comment by rfleschenberg** [comment]
@apollo13 Looks good now!

**Comment by claudep** [comment]
Hopefully solved!

**Comment by apollo13** [comment]
@claudep Sorry for the double work with regards to sitemaps -- do you think it would still be worth to push, or is the current setup (if it continues working) better?

**Comment by claudep** [comment]
I think having robots.txt in line with the sitemaps content is a good thing in any case, that's why I pushed my patch.

**Comment by apollo13** [comment]
Ok, if Tim did not already I will see to deploying it over the weekend.

**Comment by apollo13** [comment]
@claudep Looking at the google search engine tools I see that
```
Disallow: /el/1.10/internals
```
is in robots.txt but the sitemap.xml still has:
```
<url><loc>https://docs.djangoproject.com/el/1.10/internals/</loc><changefreq>daily</changefreq><priority>0.1</priority></url>
```

Did those get out of sync, or do I manually need to drop any pre-existing docs?

**Comment by claudep** [comment]
Has the latest code been deployed?

**Comment by claudep** [comment]
Oh yes, it should as the `pl` lines are in robots.txt. I'll investigate.

**Comment by apollo13** [comment]
@claudep Errors are getting less and less every day -- lets see :D Currently it complains about https://docs.djangoproject.com/es/1.9/faq/ but the /el/ errors are gone -- I'll try to see if I can rebuild the 1.9 docs on the server.

**Comment by apollo13** [comment]
And after much cache cleaning and deleting the old documents, we have got:
![selection_518](https://cloud.githubusercontent.com/assets/81547/20709856/e12db394-b637-11e6-8b54-287d8a8e7918.png)
Thanks to everyone for their hard work. I'll monitor this a bit in the future, but seems good!

**Comment by claudep** [comment]
\o/

**Comment by apollo13** [comment]
@claudep Could you update the robots.txt for 1.11?

**Comment by claudep** [comment]
Sure, will do. Should an entry be added to the Django release process?

**Comment by apollo13** [comment]
That would be great, I'll deploy the changes in a few minutes.

**Comment by claudep** [comment]
A proposal:
```
diff --git a/docs/internals/howto-release-django.txt b/docs/internals/howto-release-django.txt
index 6a91069..07e54ac 100644
--- a/docs/internals/howto-release-django.txt
+++ b/docs/internals/howto-release-django.txt
@@ -338,6 +338,13 @@ Now you're ready to actually put the release out there. To do this:
    database (this will automatically flip it to ``False`` for all
    others); you can do this using the site's admin.
 
+   Also create new ``DocumentRelease`` objects for each language having an
+   existing entry for the previous release. You should also update the
+   `djangoproject robots.docs.txt`__ file by copying entries from the previous
+   release.
+
+   __ https://github.com/django/djangoproject.com/blob/master/djangoproject/static/robots.docs.txt
+
 #. Post the release announcement to the |django-announce|, |django-developers|,
    and |django-users| mailing lists. This should include a link to the
    announcement blog post. If this is a security release, also include
```

**Comment by apollo13** [comment]
Mhm, the creation of the DocumentRelease objects sounds like something that could be done via an admin action where you specify old and new version?

**Comment by timgraham** [comment]
I've thought that the `DocumentRelease` model might be simpler if language is a many-to-many so we could select the languages on a single page rather than creating a separate model instance for each langauge. Does it sound okay?

**Comment by claudep** [comment]
Yes, looks correct.

**Comment by apollo13** [comment]
@claudep I've been searching for `django inlineformset_factory` and got `ko` results first. I guess we have to add those to `robots.txt` again? Are there any other new translations that need skipping?

**Comment by claudep** [comment]
Sorry, forgot to update robots.txt when adding Korean translations. Repaired in 91831699d6.

**Comment by timgraham** [comment]
Is there any reason that robots.txt couldn't be programatically generated to eliminate the need for manual updates?

**Comment by claudep** [comment]
I'm using a script to generate the excludes for the current stable version (https://github.com/django/django-docs-translations/blob/stable/1.11.x/manage_translations.py#L69), then I manually update the robots.txt file from these results. We could do that dynamically (with some caching), but updates are not so frequent.
