### ISSUE TITLE
Issue attaching logo for corporate members

### ISSUE THREAD

**Issue by adriennefriend** [django/djangoproject.com#628]
A persistent issue with our corporate member sign-ups is that they're having a hard time attaching the logo as part of their application. 

I've had to follow up with several who say that they did include their logo when applying, but somewhere between then pressing attach and me checking it out on the admin, the logo gets lost (or never uploaded). 

Can you think of a way to make the success or failure of posting a logo more obvious? 

The most recent example is Blanc - they said they included the logo with their application, but it did not make it to us. And there have been several others to report the same thing.

It adds an extra step for me, because I then have to reach back out to them, asking "Did you attach your logo when applying? Could you please email it to me?" Only one person said they forgot to - everyone else said they did, but for some reason, we didn't get it.

**Comment by timgraham** [comment]
Have you tried to reproduce the problem?

We could make logo a required field.

**Comment by adriennefriend** [comment]
I have tried and the same issue happened for me. 

Please make logo a required field! I think that would fix it!

**Comment by timgraham** [comment]
Oh, I didn't see a test email with your application? What does happen is that if you have form errors the first time you submit, browsers can't preserve the selected imaged so a prospective member might not notice this. I just submitted an application and the image upload worked fine. Anyway, making logo required is fine.
