### ISSUE TITLE
Update to elasticsearch 2.0

### ISSUE THREAD

**Issue by timgraham** [django/djangoproject.com#629]
I guess we should update to an elasticsearch server that uses version 2.0 at some point. @HonzaKral, at your convenience, could you advise us on how to proceed?

**Comment by HonzaKral** [comment]
Everything should work fine with 2.0 as-is. You just need to change the version of `elasticsearch` python package to `elasticsearch>=2.0.0, <3.0.0`. Then you can upgrade the cluster in found and perform a reindex just to be safe (shouldn't even be needed).

Alternatively create a new 2.x cluster, deploy the 2.x version of `elasticsearch-py` and try indexing into it. My recommendation would be to try it manually first - while pointing to prod DB, upgrade the client and point it to the new 2.x cluster and run the reindex command. If all works, switch production.

Let me know if you want me to be on irc during this, I will be happy to help.

**Comment by timgraham** [comment]
Sounds good. I'm usually working after 1pm UTC. Sometime tomorrow works for me if you're available.  We're not sure about our credentials for found though.

**Comment by timgraham** [comment]
Do we have to install elasticsearch-dsl from source since there isn't a 2.x release yet?

**Comment by HonzaKral** [comment]
oh, yes, I am sorry, i am falling behind. Or you can just use the version you already have, it will work fine.

**Comment by timgraham** [comment]
When trying to upgrade in found: "Only cluster capacity changes are allowed when using old ACLs. Please configure shield."

**Comment by timgraham** [comment]
I enabled shield but can't connect now. The error is `AuthorizationException[action [indices:data/read/search] is unauthorized for user [djangoproject]]`.

Here's the configuration from the UI:
---users---
```
djangoproject: passwordhash
```
---users per role---
```
djangoproject: admin
```
----roles----
```
admin:
  cluster: all
  indices:
    '*': all
```

**Comment by timgraham** [comment]
Found the problem, should be `admin: djangoproject` in the second file.

**Comment by timgraham** [comment]
Cluster is upgrading and working. Thanks Honza!
