### ISSUE TITLE
Tutorial for 1.9 -part 2  missing Choice in admin.register

### ISSUE THREAD

**Issue by diek** [django/djangoproject.com#631]
In the tutorial for 1.9, part 2, there is no reference to adding Choice to admin.py. This appears in the 1.8 version of the tutorial.

**Comment by timgraham** [comment]
It has moved here: https://docs.djangoproject.com/en/1.9/intro/tutorial07/
p.s. the bug tracker for documentation is https://code.djangoproject.com/
