### ISSUE TITLE
Search in Django 1.8 gives no or just one result

### ISSUE THREAD

**Issue by wimfeijen** [django/djangoproject.com#636]
https://docs.djangoproject.com/en/1.8/search/?q=mail

results in:

Only 1 result for mail in version 1.8
Django documentation contents

**Comment by timgraham** [comment]
I see 14 results now. This is likely because of the situation described in https://github.com/django/djangoproject.com/issues/626.

**Comment by wimfeijen** [comment]
Yes it works for me now. It didn't work for several minutes though.

On 12 February 2016 at 17:09, Tim Graham <notifications@github.com> wrote:

> I see 14 results now. This is likely because of the situation described in
> #626 <https://github.com/django/djangoproject.com/issues/626>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/django/djangoproject.com/issues/636#issuecomment-183389833>
> .
>



-- 
Wim Feijen
Eigenaar

Go2People Websites
Nieuwe Herengracht 49
1011 RN Amsterdam

T:  020 737 0378 / 06 1111 3316
W: http://go2people-websites.nl
