### ISSUE TITLE
Two fields, one valid

### ISSUE THREAD

**Issue by davidpsv17** [django/djangoproject.com#641]
Hi,

I have two fields in one model, I want only one valid field in the Admin Form. If one field is valid then the other is not possible to insert data or vice versa. But is necessary put data in one of the two fields for save.

That is possible?

Thanks!

**Comment by timgraham** [comment]
This ticket tracker is for bugs and new feature suggestions for the djangoproject.com website. Please see https://code.djangoproject.com/wiki/TicketClosingReasons/UseSupportChannels for ways to get help with usage questions.
