### ISSUE TITLE
DjangoProject login, new user incorrect confirmation email link 

### ISSUE THREAD

**Issue by sp-ricard-valverde** [django/djangoproject.com#647]
When creating a new user with the DjangoProject login method, I received a confirmation email with an incorrect confirmation link, formatted as follows:

www.djangoproject.comhttps://www.djangoproject[...]

where it can be noticed the duplicated and concatenated domain. The second part of the link, without the first duplicated domain is in fact the correct confirmation link(so in order to validate the new created account you should copy-paste the valid part of that link to the browser).

**Comment by timgraham** [comment]
Did the email look like this: https://github.com/django/djangoproject.com/blob/master/djangoproject/templates/registration/activation_email.txt or something else?
