### ISSUE TITLE
Clarify/soften language around the reasons for CLAs

### ISSUE THREAD

**Issue by freakboy3742** [django/djangoproject.com#651]
The preface to the CLA FAQ contains the following description:

> Every contributor of non-trivial amounts of code (more than just a line or two) to Django will be required to sign such a document. If somebody is unable to sign the document, their contribution (whether it be code, or documentation or string translations) will need to be removed from Django.

While technically true, it's a bit confronting, and doesn't reflect the actual practice where we aim to have CLAs from everyone but don't _technically_ enforce it.

The language should be softened to strongly encourage CLAs without scaring people off completely.

**Comment by timgraham** [comment]
Proposal: "Every contributor of non-trivial amounts of code (more than just a line or two) to Django should sign such a document. This agreement assures that the Django Software Foundation has the appropriate permissions to incorporate contributed patches to Django and to distribute the result."

**Comment by timgraham** [comment]
\cc @frankwiles @Xof, did we ever consult with lawyers about this?

**Comment by frankwiles** [comment]
I'm confident the original language was vetted, it's from Apache per the FAQ.  But no the proposed language hasn't been vetted by anyone to my knowledge. 

If we aren't technically enforcing CLAs for non-trivial contributions I don't see the harm and changing the CLA FAQ to be less strict.  It doesn't hurt our possible future legal battle in any way I can envision.  

If want to compromise in the middle we could simply change "will need to be removed" to "may need to be removed" which would hopefully have the effect of encouraging CLAs, but not insinuating we are constantly enforcing it.

**Comment by timgraham** [comment]
I made the suggested edit.
