### ISSUE TITLE
SSL cert expired

### ISSUE THREAD

**Issue by dirtyvader** [django/djangoproject.com#657]
Hey Django team, could you renew your SSL cert ? ;) expired today

**Comment by mjtamlyn** [comment]
Hi, we are aware of the issue and are working on it.

**Comment by apollo13** [comment]
Fixed, investigating what happened :/

**Comment by dirtyvader** [comment]
It's OK :) It happens to us all

**Comment by apollo13** [comment]
Post-Mortem at https://groups.google.com/forum/#!topic/django-developers/7qzh2n3ZDRc
