### ISSUE TITLE
Search yields the same results regardless of the query

### ISSUE THREAD

**Issue by bmispelon** [django/djangoproject.com#660]
I'm not sure how long this has been happening but it seems that searching for anything always yields the same number of results (360 when searching in the 1.9 version).

For example, the search for [`reinhardt`](https://docs.djangoproject.com/en/1.9/search/?q=reinhardt) and for [`asdf`](https://docs.djangoproject.com/en/1.9/search/?q=asdf) both yield 360 results.

Maybe related to #636?

**Comment by razyr** [comment]
This is still happening.  I do not believe it is related to building indexes or any update process.

If you search for "form", you appear to get back results sorted by perceived relevancy.  The top hit in this example is the API Reference: Forms.  The quality of hits degrades as one would expect, but it continues to list articles which have zero relevancy.

If you search for "aardvark", you get 361 results, none of which have anything to do with aardvarks.  The order of returned results in this case is not predictable and will vary from session to session if you allow some time to lapse between searches.
