### ISSUE TITLE
Improve link to issue tracker in the contributor guide

### ISSUE THREAD

**Issue by shaunagm** [django/djangoproject.com#664]
In the [contributor guide](https://docs.djangoproject.com/ja/1.9/internals/contributing/), the second link in "Report bugs in our ticket tracker", linked under "issue tracker", goes [here](https://code.djangoproject.com/newticket).  If you're not logged in (which many new contributors will not be), you see this:

![screenshot](https://cloud.githubusercontent.com/assets/1179362/15763142/9d42d266-28d6-11e6-9254-fe739fe0a963.png)

I will replace it with a link to [https://code.djangoproject.com/query](https://code.djangoproject.com/query)

**Comment by shaunagm** [comment]
My apologies, I've got the wrong issue tracker.  Fittingly, I need to make the issue using https://code.djangoproject.com/newticket :)

**Comment by timgraham** [comment]
Also raised at https://github.com/django/code.djangoproject.com/issues/64.
