### ISSUE TITLE
Doc versions are incorrectly sorted

### ISSUE THREAD

**Issue by MarkusH** [django/djangoproject.com#665]
The doc version chooser includes the version numbers in the order `1.10   1.7   1.8   1.9   dev` because they are sorted alphabetically. In the `get_all_doc_versions()` templatetag, instead of

```python
return sorted(versions)
```

we can use

```python
return sorted(tuple(map(int, x.split('.'))) for x in versions if x != 'dev') + ['dev']
```

**Comment by timgraham** [comment]
Maybe a bit simpler with `StrictVersion`: https://github.com/django/djangoproject.com/pull/666?
