### ISSUE TITLE
Deprecation cycle timeline graphic

### ISSUE THREAD

**Issue by nicktimko** [django/djangoproject.com#668]
I did a quick rough draft of a deprecation timeline using the release/support table at https://www.djangoproject.com/download/ made a ticket ([#26828](https://code.djangoproject.com/ticket/26828)), but I don't think that is actually a docs page but probably this?

Anyways, here's the thing not really cropped right or touched up fully. Worth finishing to replace that hard-to-read and maybe confusing table? :wink: Don't want to start bike-shedding, but any thoughts on it?

![timeline](https://i.imgur.com/CYFHQhK.png)

**Comment by timgraham** [comment]
It's a nice idea. The main question I have is how it's generated. Is it easy for someone else to update?
(closed [Trac ticket #26828](https://code.djangoproject.com/ticket/26828) as a duplicate.)

**Comment by nicktimko** [comment]
It's an Inkscape SVG, so I'd throw the source file into the repo, but use a PNG for display so it doesn't get shredded by some browsers.

**Comment by nicktimko** [comment]
Comments at #677
