### ISSUE TITLE
Confirmation when leaving the page when unchanged changes

### ISSUE THREAD

**Issue by dorianamouroux** [django/djangoproject.com#679]
Hi,

If I'm writing a ticket (https://code.djangoproject.com/newticket) and I leave or refresh the page, I won't have any popup to ask me if I'm sure I want to leave the page with unchanged change.
I think it can be a good idea to add this feature.

**Comment by timgraham** [comment]
I'm not sure how that feature normally works, however, we use Trac as our ticket tracker so this request would have to go that project.
