### ISSUE TITLE
Styling of documentation in Read the Docs does not match the current website

### ISSUE THREAD

**Issue by digicase** [django/djangoproject.com#681]
The styling of the documentation on Read the Docs is not using the same style as the current Django website. For comparison [here is the current documentation on the website](https://docs.djangoproject.com/en/1.9), and here are [the same docs on Read the Docs](http://django.readthedocs.io/en/1.9.x/
).

The HTML and EPUB download options for the documentation are powered by Read the Docs, and are also using the the old styling.

**Comment by timgraham** [comment]
I don't think it's important, but if someone wanted to try to make that update, the place to update is https://github.com/django/django/tree/master/docs/_theme, not this repository.
