### ISSUE TITLE
RSS feed corrections

### ISSUE THREAD

**Issue by pydanny** [django/djangoproject.com#683]
1\. I dated my blog entry "Code, Code, Code" incorrectly to 2017. I fixed it, but before I did it got picked up by djangoproject.com and remains the top listing. 

![screen shot 2016-07-13 at 12 40 14 pm](https://cloud.githubusercontent.com/assets/62857/16817291/0053003e-48f7-11e6-808c-2c09f0f9534c.png)

2\. The http://brookstravis.com blog is posting all it's content, including non-Django articles to the RSS feed picked up by djangoproject.com. 

![screen shot 2016-07-13 at 12 41 10 pm](https://cloud.githubusercontent.com/assets/62857/16817316/1d6dbdd0-48f7-11e6-8e28-02cf9f354085.png)

3\. None of the Cloudinary posts have anything to do with Django. They are, however, tagged with 'Django'. As well as 'Rails', 'PHP', and more. Basically, they are using the tag system of their RSS feed to spam various project RSS feeds with thinly veiled advertisements for their commercial services.

**Comment by timgraham** [comment]
I resolved both issues. Thanks!

**Comment by pydanny** [comment]
@timgraham Did you see I discovered a third? About Cloudinary?

**Comment by timgraham** [comment]
Just deleted them as well.

**Comment by pydanny** [comment]
As @cloudinary is abusing the Django RSS feed, can they be constrained or blocked until they stop spamming the feed?

**Comment by timgraham** [comment]
I deleted their feed -- are you seeing otherwise?
