### ISSUE TITLE
CVC field should be password type

### ISSUE THREAD

**Issue by akki** [django/djangoproject.com#687]
The CVC field shown on the fundraising page popup (see image)  shows the input value. CVCs are meant to be kept secret and are considered as [security PIN numbers](https://en.wikipedia.org/wiki/Card_security_code), hence that field should be of password type.

I would be happy to make the changes and send a PR but was unable to find the code for the popup.
![visible-cvc](https://cloud.githubusercontent.com/assets/4801628/16896578/10759348-4bb6-11e6-958c-c7c4386ab313.png)

**Comment by Xof** [comment]
The popup is generated by Stripe, our credit card gateway, not by the site, so we don't have control over the HTML of the fields.

**Comment by akki** [comment]
Sorry, didn't know that.
