### ISSUE TITLE
Feed not showing under /community/blogs/

### ISSUE THREAD

**Issue by FrancoisConstant** [django/djangoproject.com#688]
Hello,

I've added my feed on this page a few months ago:
https://www.djangoproject.com/community/add/blogs/

the feed is: http://eatsomecode.com/rss/django/

My posts, including one I've published today are not showing up here:
https://www.djangoproject.com/community/blogs/

I've tried to add it back today but I'm getting an error message saying that this feed already exists. I haven't received any email or see any error message last time. I'm not sure if it's a problem with the feed itself or something else.

Thank you,

**Comment by timgraham** [comment]
I just approved the feed.
