### ISSUE TITLE
Listing of Django usergroups worldwide

### ISSUE THREAD

**Issue by jensneuhaus** [django/djangoproject.com#691]
I would love to see a listing of Django usergroups worldwide on https://www.djangoproject.com/community/ so that people can participate easier. 

Maybe in this part of the webpage?

<img width="393" alt="django_usergroups" src="https://cloud.githubusercontent.com/assets/8494661/17062226/1120875a-5000-11e6-94ea-416d9c2f378c.png">

"Django user groups 
Meet other people working with Django"

On the page itself there should be a listing of countries and cities in that country, which have a usergroup and a link to that one. 

It could also be usergroups dealing with Python?

**Comment by timgraham** [comment]
I think this could fit as a feature request for https://people.djangoproject.com/. (https://github.com/django/djangopeople/issues)
