### ISSUE TITLE
Problems with the Moya blog

### ISSUE THREAD

**Issue by pydanny** [django/djangoproject.com#694]
I find it odd that posts entirely about `Moya` are included in Django's community blog feed. It's a different web framework where the creator blogs and sometimes tags his posts with `django`.

Is it possible to filter out anything he writes that has `moya` tagged?

**Comment by pydanny** [comment]
References:

* https://www.willmcgugan.com/tag/django/
* https://www.willmcgugan.com/tag/moya/

**Comment by timgraham** [comment]
If you want to contact the author and ask that they use the Django tag more strictly, we can do that. Otherwise, we can remove the feed if you feel the content is spam.

**Comment by pydanny** [comment]
The author is @willmcgugan who has written some great Django stuff in the past. If he's moved on, that's fine. He should just let the Django community feed know.

**Comment by willmcgugan** [comment]
I still work with Django professionally, but the posts I tag with 'django' have been only tangentially related recently. If you would prefer I reserve that tag for more Django specific posts, I can do that

**Comment by timgraham** [comment]
Thanks.
