### ISSUE TITLE
Login with invalid 'next' redirects to '/accounts/profile' which 404s

### ISSUE THREAD

**Issue by RaminFP** [django/djangoproject.com#695]
Hi @timgraham,

you use app 'django-registration', on login page with this url https://www.djangoproject.com/accounts/login/?next=/accounts/edit/ we can redirect to valid url path "/accounts/edit/" but if we use https://www.djangoproject.com/accounts/login/?next=//google.com we will redirect to page 'accounts/profile' this page not found, not defined path for redirect 
 
we should use like this : 
```python
redirect_to = bleach.clean(request.POST.get('next'))
if redirect_to:
    define_root_path = '/'
    redirect_to = redirect_to if is_safe_url(redirect_to,request.get_host()) else define_root_path 
``` 

Thanks,

**Comment by timgraham** [comment]
PR: https://github.com/django/djangoproject.com/pull/696

**Comment by RaminFP** [comment]
Thanks @timgraham

**Comment by MichaelJames02** [comment]
I'm having the same issue. I'm using django 2.0

**Comment by timgraham** [comment]
This is the issue tracker for the djangoproject.com website. Please see [TicketClosingReasons/UseSupportChannels](https://code.djangoproject.com/wiki/TicketClosingReasons/UseSupportChannels) for ways to get help with Django usage.
