### ISSUE TITLE
Mobile view for Fundraising page not displaying DSF Supporters names correctly

### ISSUE THREAD

**Issue by kevgathuku** [django/djangoproject.com#704]
The mobile view on the [Donate](https://www.djangoproject.com/fundraising/) page mangles up the names of the DSF Supporters.
Here's a screenshot of what I'm experiencing on the mobile view
<img width="310" alt="screen shot 2016-09-18 at 5 18 30 pm" src="https://cloud.githubusercontent.com/assets/3721994/18616439/76e94fee-7dc4-11e6-940d-acaddaec3536.png">

**Comment by timgraham** [comment]
Confirmed.
