### ISSUE TITLE
Models' default value is not apply in a database.

### ISSUE THREAD

**Issue by timur-sh** [django/djangoproject.com#705]
How can I save the default argument in the database?

> class Car(models.Model):
     name = models.CharField('Name', max_length=255, default='Audi')
     max_speed = models.IntegerField('Max Speed', default=220)

**Comment by timgraham** [comment]
This is the ticket tracker for the djangoproject.com website. Please see https://code.djangoproject.com/wiki/TicketClosingReasons/UseSupportChannels for ways to ask usage questions.
