### ISSUE TITLE
Changing donation card for existing donation

### ISSUE THREAD

**Issue by Xof** [django/djangoproject.com#706]
Right now, we don't implement the Stripe API for changing a subscription card. This isn't trivial, as it will require us keeping track of the emails of repeating donors (by my reading of the API), but we should probably build it out at some point.

**Comment by timgraham** [comment]
Did you find deleting an existing donation and readding it too cumbersome?

**Comment by timgraham** [comment]
I see a "Change card details" button under "Modify your recurring donations" on https://www.djangoproject.com/fundraising/manage-donations/donor-id/. Did you try that?
