### ISSUE TITLE
Add corporate membership renewals

### ISSUE THREAD

**Issue by timgraham** [django/djangoproject.com#710]
Currently corporate memberships expire without any offer to renew.

I'm thinking about sending members an email ~30 days before a membership expires with a link to the onboarding form prepopulated with a member's current info so they can indicate that they want to renew and also make any updates to the info. That'll send an email to us and the treasurer to generate an invoice.

**Comment by Xof** [comment]
Excellent idea.

**Comment by timgraham** [comment]
This is completed.
