### ISSUE TITLE
django.db.fields.CharField.__init__'s min_length  is a lie

### ISSUE THREAD

**Issue by prinsherbert** [django/djangoproject.com#711]
The `min_length` mentioned [here](https://docs.djangoproject.com/ja/1.10/ref/forms/fields/#charfield) is not part of `CharField`'s `__init__` (or the `Field`'s `__init__` to which they are forwarded):

* [CharField relevant code](https://github.com/django/django/blob/master/django/db/models/fields/__init__.py#L1043)
* [Field relevant code](https://github.com/django/django/blob/master/django/db/models/fields/__init__.py#L140)

My `django.__version__` is `'1.10.2'`, and the relevant code in my `site_packages` is similar to what I've linked.

**Comment by timgraham** [comment]
I think you've confused form fields (linked in the documentation) with model fields (linked in the code). For future reference, documentation bugs are reported using [Trac](https://code.djangoproject.com/newticket), not this issue tracker.

**Comment by prinsherbert** [comment]
Ah, yes, thanks!
