### ISSUE TITLE
Django documentation search header and pagination always show "370 results".

### ISSUE THREAD

**Issue by m-aciek** [django/djangoproject.com#713]
No matter a search query. Reference: https://docs.djangoproject.com/en/1.10/search/?q=what+the+heck%3F
![zrzut ekranu z 2016-11-02 20-44-08](https://cloud.githubusercontent.com/assets/9288014/19944712/3f82dc22-a13d-11e6-80a4-ac687bc33c4e.png)
It looks like there is something wrong with Elasticsearch instance.

**Comment by outofthink** [comment]
I meet the same problem

**Comment by mikicaivosevic** [comment]
This is probably problem with elastic search query in [search_resulsts](https://github.com/django/djangoproject.com/blob/66ddfa398dc9432cdcf3c139b47ea4763091cd7f/docs/views.py#L139) method.

**Comment by geeregman** [comment]
Yes I also have always "370".  Also the 1st page is often empty and the rest of the pages are always empty, that is no results are shown and always 37 pages of results...................
In other words......searching documentation does not work.

**Comment by timgraham** [comment]
This might be fixed after upgrading to the latest version of elasticsearch: https://github.com/django/djangoproject.com/pull/723. I'll do the upgrade in at most a couple days.

**Comment by timgraham** [comment]
I did the upgrade and this looks resolved.

**Comment by geeregman** [comment]
tried the search.
Looks like it's working OK now............thanks............
