### ISSUE TITLE
Rename "developer member" to "individual member"

### ISSUE THREAD

**Issue by tobiasmcnulty** [django/djangoproject.com#719]
This was approved by the board and just needs to be implemented on the site. This includes changes to the code and an edit to the `/foundation/` flatpage.

- [ ] code changes
- [ ] flatpage edits

**Comment by timgraham** [comment]
I updated the https://www.djangoproject.com/foundation/ flatpage. If you spotted any other pages, let me me know. I didn't see anything else according to a Google search for: "developer member" site:djangoproject.com

**Comment by tobiasmcnulty** [comment]
That's all I saw as well -- thanks!
