### ISSUE TITLE
Add a bio field to IndividualMember

### ISSUE THREAD

**Issue by timgraham** [django/djangoproject.com#720]
We're thinking about moving https://docs.djangoproject.com/en/dev/internals/team/ from the documentation to the website. Part of that requires a place to store everyone's bio. The `IndividualMember` model might be a good place for that.

We'd eventually like to allow everyone to edit their own bio. I'm not sure if raw HTML or something like reStructuredText would be better. Raw HTML is prone to abuse and the syntax of reStructuredText is difficult to get correct.

**Comment by frankwiles** [comment]
Markdown is a decent compromise between security and ease of use for bio content.

**Comment by timgraham** [comment]
I wasn't sure about adding another dependency. :-)

Do you have a favorite library or technique for that?

**Comment by frankwiles** [comment]
It's not that big of a dependency.  We used https://github.com/jamesturk/django-markupfield on python.org because we needed to support both ReST and Markdown, but it could be used for just Markdown.  

However, this library looks pretty good as well https://github.com/adi-/django-markdownx

**Comment by timgraham** [comment]
I wouldn't mind using django-markupfield and having a choice of reStructuredText (we could copy all the team member's existing bios) vs. markdown, but it annoys me that there's no validation so if invalid reSt is entered, for example, the page renders with an error. Do you know if markdown has a similar issue? It's a slight complication that it adds an extra "markup type" field if we only support markdown.

The live preview of django-markdownx looks nice, but it doesn't have a template tag for rendering markdown (we could implement our own or add another dependency). Also, I don't think it works with `settings.CSRF_COOKIE_HTTPONLY=True` (yet? https://github.com/adi-/django-markdownx/issues/21) that djangoproject.com uses.

**Comment by frankwiles** [comment]
Yeah I think validation is an issue for both.  I don't think we need the live editing as much as just having support for an ML format that isn't HTML right?

**Comment by timgraham** [comment]
Here's a start: https://github.com/django/djangoproject.com/pull/745. This doesn't add a view to allow members to edit their own information.

Frank, I think you were working on or planned to work on allowing members to link their member profile to their `User` account. Did you make any progress there?

**Comment by frankwiles** [comment]
No sadly I haven't made any progress yet. :(

**Comment by timgraham** [comment]
Could you remind me of the strategy you proposed?

I'm thinking to add `user = models.OneToOneField(User, blank=True, null=True)` to `IndividualMember`. A view will allow a logged in djangoproject.com user to link their account to an `IndividualMember` profile. If the email addresses of `User` and `IndividualMember` match, the link happens right away. If they don't match, a confirmation email is sent to `IndividualMember.email` with a URL to visit to confirm the link.

**Comment by carltongibson** [comment]
This ties-in with #1171 (and general effort to improve sponsorships/fundraising) — Allowing folks to login and edit their details, as well as donations (#1052) is all of a one.

**Comment by timgraham** [comment]
I think this is a wontfix. The bio/website fields were added, but then removed because not enough members filled them out and the DSF Board thought it was awkward.
