### ISSUE TITLE
Command for Windows to activate virtualenv is wrong

### ISSUE THREAD

**Issue by mandazi** [django/djangoproject.com#731]
On the documentation page here:
https://docs.djangoproject.com/en/1.10/intro/contributing/

It says for Windows to activate the virtualenv to run this:
`$ source ~/virtualenvs/djangodev/Scripts/activate`

![image](https://cloud.githubusercontent.com/assets/340385/21998333/2b0e1612-dc02-11e6-9559-ac4b718a5897.png)

That didn't work for me. I found this stackoverflow answer [here](http://stackoverflow.com/questions/8921188/issue-with-virtualenv-cannot-activate) which said:

> On Windows, virtualenv creates a batch file, so you should run venv\Scripts\activate.bat instead (per the virtualenv documentation on the activate script).

That worked for me on Windows.

The documentation should clarify this for Windows users.

**Comment by timgraham** [comment]
Which shell are you using? The tutorial works for me using Git bash.

By the way, the correct place to report issues with the documentation is https://code.djangoproject.com/newticket.
