### ISSUE TITLE
No module named NullHandler

### ISSUE THREAD

**Issue by Anairda88** [django/djangoproject.com#732]
Hello Team!,

I really hope you could help me with this error:
_Unable to configure handler 'null': Cannot resolve 'django.utils.log.NullHandler': No module named NullHandler_

I am using Django 1.10 on Ubuntu 14.04 with python 2.7
Even though I have been looking up for information to solve the error; I haven`t found a solution that works. 

Thanks a lot in advance

**Comment by timgraham** [comment]
This is the bug tracker for djangoproject.com. Please see https://code.djangoproject.com/wiki/TicketClosingReasons/UseSupportChannels for ways to get help.
