### ISSUE TITLE
Missing favicon.ico

### ISSUE THREAD

**Issue by apollo13** [django/djangoproject.com#736]
At some point the server config seems to have changed (maybe with the upgrade) and we were missing the favicon. I added it to: https://github.com/django/djangoproject.com/blob/master/djangoproject/static/favicon.ico and then I realized it is already in https://github.com/django/djangoproject.com/blob/master/djangoproject/static/img/favicon.ico

I guess we can remove one ;) Which one is the right one (md5sum is different?) and is there any reason to prefer it in img/ (then I will adjust the ansible config accordingly)

**Comment by timgraham** [comment]
It looks to me like `img/favicon.ico` is the one from the 2014 redesign. It's the same as `icon-touch.png`, for example. Keeping it in `img/` seems fine to me.

**Comment by apollo13** [comment]
Mhm, @adamchainz complained about it not beeing there, makes me wonder since
```
    <link rel="shortcut icon" href="/s/img/favicon.6dbf28c0650e.ico">
```
is there and actually works. do some browssers ignore link rels?

**Comment by timgraham** [comment]
I'm not sure about the details. https://mathiasbynens.be/notes/rel-shortcut-icon is a few years old but suggests that `/favicon.ico` should always be there.

**Comment by adamchainz** [comment]
I was on `code.djangoproject.com` which has:

```html
<link rel="icon" href="/favicon.ico" type="image/x-icon">
```

**Comment by apollo13** [comment]
Ah, I didn't watch closely enough :D

**Comment by apollo13** [comment]
Reverted my checkin and fixed nginx config.

**Comment by adamchainz** [comment]
🥇
