### ISSUE TITLE
Docs index failure: Data too large, data for [<transport_request>] would be larger than limit

### ISSUE THREAD

**Issue by timgraham** [django/djangoproject.com#739]
This started yesterday after I upgraded the elasticsearch cluster from 5.1.x to 5.2.0:
```
POST https://7cd8f7a21dbf68934d42d468910c155e-us-east-1.foundcluster.com:9243/_bulk [status:503 request:0.295s]
Traceback (most recent call last):
...
    output = self.handle(*args, **options)
  File "/home/www/www/src/docs/management/commands/update_index.py", line 21, in handle
    for ok, item in index_results:
  File "/home/www/www/src/docs/search.py", line 81, in index_all
    for ok, item in streaming_bulk(client, actions_generator(), chunk_size=100, **kwargs):
  File "/home/www/www/venv/lib/python3.5/site-packages/elasticsearch/helpers/__init__.py", line 162, in streaming_bulk
    for result in _process_bulk_chunk(client, bulk_actions, raise_on_exception, raise_on_error, **kwargs):
  File "/home/www/www/venv/lib/python3.5/site-packages/elasticsearch/helpers/__init__.py", line 134, in _process_bulk_chunk
    raise BulkIndexError('%i document(s) failed to index.' % len(errors), errors)
elasticsearch.helpers.BulkIndexError: ('38 document(s) failed to index.', [{
  'index': {'status': 503, '_type': 'document',
'error': {'bytes_wanted': 740915167,
'type': 'circuit_breaking_exception',
'reason': '[parent] Data too large, data for [<transport_request>] would be larger than limit of [739416473/705.1mb]',
'bytes_limit': 739416473},
'_index': 'docs-2017-02-14t10:00:10.775887',
'_id': '6371665'}}, ...
```
\cc @honzakral

**Comment by HonzaKral** [comment]
This looks like the chunks being sent via teh `bulk` API are too big so that the circuit breaker fires to try and protect the cluster. The solution is to lower the number of documents used in the `bulk` call in https://github.com/django/djangoproject.com/blob/cd882aa4bd453dfef397f7ccc6eeef1e4e7a1915/docs/search.py#L81 and/or use size-based chunking (`max_chunk_bytes=10*1024*1024`)

**Comment by timgraham** [comment]
The error still happens after reducing `chunk_size` to 1. My naive interpretation of the error message suggests that a document is larger than 705MB which I don't think we have any of. Continuing investigation...

**Comment by timgraham** [comment]
There might be a larger problem with our elasticsearch cluster. Upgrading to 5.2.1 is failing with some messages in the logs such as:

[2017-02-15T15:11:34,923][WARN ][rest.suppressed ] path: /_snapshot/found-snapshots, params: {repository=found-snapshots} org.elasticsearch.transport.RemoteTransportException: [tiebreaker-0000000070][172.17.0.7:19929][cluster:admin/repository/put] Caused by: org.elasticsearch.repositories.RepositoryVerificationException: [found-snapshots] [[ALPN1p_UQE2nHT4ud5ZsGA, 'RemoteTransportException[[172.17.0.30:19661][internal:admin/repository/verify]]; nested: CircuitBreakingException[[parent] Data too large, data for [] would be larger than limit of [739416473/705.1mb]];']] at

**Comment by HonzaKral** [comment]
it looks like overall the cluster is running out of memory which is causing the circuit breaker exceptions, looking into what it could cause it now

**Comment by HonzaKral** [comment]
@timgraham  it looks like the cluster got into an unstable state where almost any request will send it over the edge with the circuit breaker, we are taking a heap dump now to diagnose the issue and will reboot it to wake it up.

The solution should be to really make sure that only one index copy is left in the cluster (that the indices are removed correctly after reindex) and ideally also set the number of shards to 1 in an index template.

I am sorry I cannot do anything else today but I will be sprinting on at PyCon Pune over the weekend so I can have a look at the code and help if possible.

**Comment by timgraham** [comment]
Thanks, this error is gone after removing old indexes.

**Comment by timgraham** [comment]
Actually, we're still have trouble with the cluster. For example this code sometimes fails:
```
>>> from elasticsearch_dsl.connections import connections
>>> es = connections.get_connection('default')
>>> es.cat.indices(index='docs' + '*', format='json', h='index')
TransportError(503, 'circuit_breaking_exception', '[parent] Data too large, data for [<http_request>] would be larger than limit of [739416473/705.1mb]')
```
There are only two indexes and memory pressure is at 40% and 10% on the two nodes, so it doesn't look like memory should be a problem, but maybe I'm looking at the wrong metrics to understand this. Please investigate at your convenience. Thanks!

**Comment by timgraham** [comment]
I restarted the elasticsearch cluster and search is working, at least for now.

**Comment by timgraham** [comment]
The errors are back < 24 hours later and solved by another restart. Could there be a memory leak? I saw some discussion of memory issues at https://cloud-status.elastic.co/.

**Comment by timgraham** [comment]
Another restart was required this morning. I created https://discuss.elastic.co/t/cluster-runs-for-several-hours-before-failing-with-data-too-large-errors/76108 to try to get some help from elastic engineers.

**Comment by HonzaKral** [comment]
This has been identified as a bu in elasticsearch, new version is coming soon with a fix as `5.2.2`, it was indeed a memory leak. The information gathered for your cluster was very helpful in diagnosing the issue. My apologies for the delay and the issue itself, hopefully it will be resolved soon.

**Comment by bekiryazici** [comment]
@timgraham, Is there a solution you can share with us?

**Comment by timgraham** [comment]
For us, the issue was a memory leak in Elasticsearch 5.2.0 and 5.2.1.
