### ISSUE TITLE
A search in french doesn't give any result

### ISSUE THREAD

**Issue by blankoworld** [django/djangoproject.com#753]
# How to reproduce

  * Go here: https://docs.djangoproject.com/en/1.8/
  * use search bar with this word: **default_app_config**
  * You get 1 result
  * Go here: https://docs.djangoproject.com/en/1.8/
  * Use at the bottom right the button "Language: en", choose **fr**
  * use search bar with this word: **default_app_config**
  * No result appears

# Expected

Same result as first test with english documentation: 1 result explaining how to use "default_app_config".

It also happens with some other words. Try it.

# Information

Not sure about what could be interesting to have as data, but here is my configuration:

  * Ubuntu 16.04
  * Firefox 52.0

Thanks for advance about any explanation about this curious thing ;)

**Comment by doriclazar** [comment]
This issue has been fixed since 1.10 version.

**Comment by pauloxnet** [comment]
After migration to Django 2.0 of djangoproject.com I will be able to apply some commits to hadle multilingual full-text search for documentation.
https://github.com/django/djangoproject.com/pull/794

**Comment by timgraham** [comment]
Only the stable versions of the translated versions of the documentation are updated (https://github.com/django/djangoproject.com/issues/627). That means that `Document` objects for those versions aren't automatically updated. We could run a one-time script to fix that.

**Comment by pauloxnet** [comment]
The multilingual search is working for the latest stable version.
Try it:
https://docs.djangoproject.com/fr/4.1/search/?q=default_app_config

**Comment by timgraham** [comment]
I wonder why it gives only one result for french, but four results for english (https://docs.djangoproject.com/en/4.1/search/?q=default_app_config)?
