### ISSUE TITLE
fundraising: possible issues with updating customer source and bitcoin

### ISSUE THREAD

**Issue by Parbhat** [django/djangoproject.com#759]
There are some possible issues with updating customer source in the line https://github.com/django/djangoproject.com/blob/master/fundraising/forms.py#L180

- Updating `customer` source this way will make it the customer default source, and delete the old customer default if one exists. If the customer is subscribed to a monthly donation of $50 using the card. If the customer donate again with `bitcoin` using the same email, then the customer card will be deleted and bitcoin will be the `default` source. `Bitcoins` can only be used once and can not be used for subscriptions. The customer next invoice will fail as the user has no reusable payment source.

- Bitcoins should also be handled differently as they can be used only for onetime donations. If a new donor is using `bitcoin` method and choose to donate monthly, the subscription will fail. As the customer's active source must be reusable.

**Possible solution**:
Along with `stripe_token`, a `type` value can also be sent in the request. If the `type` is card, follow the current behaviour. If the `type` is`bitcoin`, only do one time charge. A note can also be added in the front-end about bitcoin onetime usability.

**Comment by timgraham** [comment]
If you have some experience with this and can propose a patch, that would be great.

**Comment by Parbhat** [comment]
Great. Will work on the patch.

**Comment by Parbhat** [comment]
@timgraham PR for the issue - #760
