### ISSUE TITLE
I borked the RSS feed

### ISSUE THREAD

**Issue by pydanny** [django/djangoproject.com#762]
I made duplicates entries in the Django feed: https://www.djangoproject.com/community/blogs/ The reason is that I upgraded my blog software and that caused the issues that you see.

There should only be these two articles:

* Python F-Strings Are Fun!
* Two Scoops of Django 1.11 is Out!

**Comment by timgraham** [comment]
Which URLs would you like to be kept? pydanny.com or www.pydanny.com?

**Comment by timgraham** [comment]
I removed the entries with "www".
