### ISSUE TITLE
Roadmap table incorrect misses 1.8

### ISSUE THREAD

**Issue by samuelcolvin** [django/djangoproject.com#763]
https://www.djangoproject.com/weblog/2015/jun/25/roadmap/ the table at the top makes no reference to 1.8.

However further down the page it says "Django 1.8 LTS security support ends April 2018". Surely if 1.8 is still supported it should be included in the table?

**Comment by timgraham** [comment]
Please use the table at https://www.djangoproject.com/download/#supported-versions. At the time of that blog post, 1.8 was already released, hence it's not part of the future roadmap.

**Comment by samuelcolvin** [comment]
Ok, might be good to have some kind of prominent link on that blog to the support versions page, I always seem to end up on that page when trying to find out when versions expire, I've seen others find the same page.
