### ISSUE TITLE
404 page doesn't have search field

### ISSUE THREAD

**Issue by iustitia** [django/djangoproject.com#767]
While reading the documentation there is useful field for search, just above "Support Django!" section. However when getting to 404 page, the field is not displayed. 

IMHO, the search field is widely used when getting to 404 page, so might be useful to add it.

**Comment by timgraham** [comment]
The 404 page covers the entire website, not just the documentation, so adding the docs-specific search bar doesn't seem right. Probably it could be done in a complicated fashion, but we've survived without it.
