### ISSUE TITLE
Show supported Python versions in downloads table

### ISSUE THREAD

**Issue by Flimm** [django/djangoproject.com#768]
In the [downloads page for Django](https://www.djangoproject.com/download/), there's a beautiful table that lists the supported and unsupported Django versions. It looks like this:

![screen shot 2017-05-24 at 17 42 19](https://cloud.githubusercontent.com/assets/355454/26415173/7e852a22-40a9-11e7-9622-b1fdefeaa86f.png)

It would very useful if an additional column, titled "Python versions", were added. That way, it would be easy to update our `tox.ini` and `.travis.yml` files to include the right combination of Django versions and Python versions. It could look like this modified screenshot:

![screen shot 2017-05-24 at 17 48 50](https://cloud.githubusercontent.com/assets/355454/26415209/9cbf2100-40a9-11e7-8aa2-29353546aeca.png)

**Comment by timgraham** [comment]
This information is documented at https://docs.djangoproject.com/en/dev/faq/install/#what-python-version-can-i-use-with-django. Not sure if duplicating it in this table is appropriate but perhaps a link could be added.

**Comment by Flimm** [comment]
That's a handy table, thank you! I'm OK with closing this issue now, unless someone wants to add that link.
