### ISSUE TITLE
Mistake in docs about Django Forms label

### ISSUE THREAD

**Issue by mark-selyaeff** [django/djangoproject.com#769]
https://docs.djangoproject.com/en/1.11/ref/forms/fields/#label
Here after `print(f)` input with name='url' will not be required, because
`url = forms.URLField(label='Your website', required=False)`

**Comment by timgraham** [comment]
Fixed in https://github.com/django/django/commit/17ed0d36bc3c380b7d8a0a30ceda09d98ab74fd4.

For future reference, the bug tracker for Django's documentation is https://code.djangoproject.com/. This tracker is for www.djangoproject.com.
