### ISSUE TITLE
How to interpret "Returns None if there is no suggestion" in Multiple databases?

### ISSUE THREAD

**Issue by jacktan1991** [django/djangoproject.com#770]
<img width="707" alt="2017-06-21 5 04 25" src="https://user-images.githubusercontent.com/7688739/27376096-b81e413c-56a3-11e7-91a9-90870e41a859.png">

"no suggestion" here means 'default' db will be used?

**Comment by timgraham** [comment]
Hi, this is a bug tracker for the djangoproject.com website. Please use [our support channels](https://code.djangoproject.com/wiki/TicketClosingReasons/UseSupportChannels) for usage questions.

I'll just answer your question though: "no suggestion" means the router won't be used. The next router will be consulted or, if all routers have been consulted, then the default database is used.
