### ISSUE TITLE
Django misbehaves with logging module

### ISSUE THREAD

**Issue by futureshine** [django/djangoproject.com#778]
I set a handler as follows in `settings.py`:
```python
'handlers': {
        'test_log': {
            'class': 'logging.handlers.RotatingFileHandler',
            'formatter': 'verbose',
            'filename': "test.log",
            'maxBytes': 1024,
            'backupCount': 5
        },
    },
```
But when the `test.log` file reaches the maximum, here 1KB, it throws
```python
WindowsError: [Error 32] 
```
After debugging, I found that there were two processes holding reference to this file, which made it cannot be renamed to `test.log.1` in `logging/handlers` 142 line:
```python
os.rename(self.baseFilename, dfn)
```

Best regards!

**Comment by timgraham** [comment]
The bug tracker for Django is https://code.djangoproject.com/. This tracker is for www.djangoproject.com. 

I think we'll need more specific steps to reproduce (a sample project, perhaps) as I can't reproduce a problem with Windows 10 / Python 3.6. Of course if you can provide a tested patch with a fix, all the better.
