### ISSUE TITLE
Add a book/resources section

### ISSUE THREAD

**Issue by pydanny** [django/djangoproject.com#784]
Having this will mean less repetitive questions of the same thing again and again on mailing lists, slack channels, quora, reddit, and every other forum. Having it will make answering Django questions easier.

Yes, there's a venerable one buried in the wiki, but who goes there in 2017? Also, there's no control so anyone can add anything.

Anyway, proposed requirements:

* [ ] Easily found but not dominating in the navigation
* [ ] Has a system to allow vetting of resources by admins to prevent spam or bad content
* [ ] Allows for affiliate links in the URLs so the DSF can make a little extra money to be donated to good causes
* [ ] At a minimum includes thumbnail, title, creator(s) and link
* [ ] Could also include short description (300 words or less)
* [ ] Includes flag to mark items as deprecated due to supporting old Django versions
* [ ] Has category(ies) field marking things as tutorial, reference guide, cook book, et all

References for sample content:

* https://www.twoscoopspress.com/pages/current-django-books
* https://www.twoscoopspress.com/pages/django-tutorials

**Comment by timgraham** [comment]
I think you should first raise the idea on the dsf-members mailing list to see if there's consensus about it. The main issue I see is finding people to curate and maintain the list. Basically, we'd be relying on DSF volunteers to provide advertising for authors. Or else, we could charge a fee and hire someone to maintain it. Not sure if the DSF wants to get into that business.

**Comment by pydanny** [comment]
As I do it already, I'll help maintain this resource. Even better, this will allow others to have their input, meaning that the canonical list isn't just my list of preferred items.

That said, I'll send an email to dsf-members

**Comment by pydanny** [comment]
Just discovered I got removed from dsf-members. I had been wondering why I never got messages anymore. Anyways, hopefully someone can post this issue into that list.

**Comment by claudep** [comment]
If you volunteer to maintain the list, I think that's a good idea.
How would you imagine suggestions by people: a form, an email contact, a mailing list?
There is also the question of non-English books.

**Comment by pydanny** [comment]
Forms to submit content and then use the Django admin to administer. This
should be  trivial to do with Django

--Danny

**Comment by tBaxter** [comment]
I would propose:

1. In addition to the requirements above, adding a "language" field.
2. Consider adding something representing cost. Perhaps the restaurant-style $ $$ $$$ style markers. While they're US-centric, I think they'd be easily understood and sidestep the issue of putting actual costs in, which fluctuate too much.
3. I think a simple form to submit is adequate, couple with a "for review" flag. The "for review" flag could also be useful for community vetting. Objects can be voted up and down. Below a certain point, they would go back into "for review" status.

**Comment by pydanny** [comment]
> The "for review" flag could also be useful for community vetting. Objects can be voted up and down. Below a certain point, they would go back into "for review" status.

I disagree 100% with a review or vote system because they can be gamed. Instead, have the DSF board periodically assign 2-3 dsf members to act as moderators.

**Comment by frankwiles** [comment]
@pydanny I show you active on dsf-members but now that I look I see you joined up on August 16th so ummm nevermind.  Nothing to see here. In the future if you fall off for some reason just let me know!

**Comment by timgraham** [comment]
It seems this isn't happening.

**Comment by carltongibson** [comment]
I agree this isn't happening. 

There's a recurrent discussion about how to better assist/publicise/... content in the Django realm. A discussion on the DSF Members list to establish a _What we might do_ (circa 2022) would still be worthwhile I think, if someone motivated comes this way.
