### ISSUE TITLE
Document configuration with MariaDB

### ISSUE THREAD

**Issue by dns2utf8** [django/djangoproject.com#786]
Hi all

As far as I understand MariaDB is a [drop-in-replacement](https://mariadb.com/kb/en/mariadb/mariadb-vs-mysql-compatibility/) for MySQL.
If this is true? Would you mind including it with the docs?
The question came up because the latest [debian 9 has replaced MySQL with MariaDB](http://www.tuxmachines.org/node/102162).

Regards

**Comment by timgraham** [comment]
This is the bug tracker for the djangoproject.com website. The tracker for Django and its documentation are located at https://code.djangoproject.com/. Official support for MariaDB was [discussed](https://groups.google.com/d/topic/django-developers/31j1dNOZ7zc/discussion) but there's been no action.
