### ISSUE TITLE
Can you please elaborate 3 step where I need to create secret.json file

### ISSUE THREAD

**Issue by ankushbadlas** [django/djangoproject.com#800]
I am getting the following error 

 conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
django.db.utils.OperationalError: FATAL:  password authentication failed for user "djangoproject"
FATAL:  password authentication failed for user "djangoproject"

I followed all steps excluding step 3. So please help me how I configure that project successfully on local server(ubuntu).

**Comment by timgraham** [comment]
What's unclear?

**Comment by ankushbadlas** [comment]
Tim, I configure the djangoproject on my local system. which give me the database connection error. So please let me know what I should do to work on it in the correct way.

**Comment by ankushbadlas** [comment]
Tim, Please give me the idea how can I configure it on my local system?

I installed python3.0 and django 1.11 in my local system.

**Comment by timgraham** [comment]
Is this your first time using Django and PostgreSQL? Why did you omit step 3 in the instructions?

**Comment by ankushbadlas** [comment]
Yes Tim, This is the first time to use Django and Postgresql. I am not getting where I need to create the database connection. Please help me to short out this issue.

**Comment by timgraham** [comment]
Please do step 3 so that Django has the proper password to connect to PostgreSQL.

**Comment by ankushbadlas** [comment]
Yes, I am not able to do that step. I am confusing with this step.

**Comment by timgraham** [comment]
What's your question about it?

**Comment by ankushbadlas** [comment]
![screenshot from 2017-11-24 18-59-00](https://user-images.githubusercontent.com/7335485/33212526-94607d16-d149-11e7-87df-9ba9c9e55e80.png)
![screenshot from 2017-11-24 18-59-52](https://user-images.githubusercontent.com/7335485/33212539-b001108a-d149-11e7-91cb-a2602c513167.png)

**Comment by ankushbadlas** [comment]
Please see the path where I create secret.json file. Please explain me about the following line:

Add export DJANGOPROJECT_DATA_DIR=~/.djangoproject (without the backticks) to your ~/.bashrc (or ~/.zshrc if you're using zsh) file and then run source ~/.bashrc (or source ~/.zshrc) to load the changes.

**Comment by ankushbadlas** [comment]
![screenshot from 2017-11-24 19-02-50](https://user-images.githubusercontent.com/7335485/33212643-2622f6e8-d14a-11e7-9794-964356bc452b.png)

this is common.py file under settings directory

**Comment by timgraham** [comment]
In that case, you should use `export DJANGOPROJECT_DATA_DIR=~/Desktop/djangoproject/djangoproject` in the `~/.bashrc` file.

**Comment by ankushbadlas** [comment]
![screenshot from 2017-11-24 19-04-51](https://user-images.githubusercontent.com/7335485/33212736-661cf988-d14a-11e7-8497-43b668becbc6.png)


please see this screenshot which I am getting authentication error.

**Comment by ankushbadlas** [comment]
In that case, you should use export DJANGOPROJECT_DATA_DIR=~/Desktop/djangoproject/djangoproject in the ~/.bashrc file.

??? How?

**Comment by timgraham** [comment]
If you're using a GUI text editor, use control-h in the file browser to show hidden files (that start with a dot).

**Comment by timgraham** [comment]
The tilda in the path name means to use your home directory, e.g. `/home/<username>/`.

**Comment by ankushbadlas** [comment]
Tim  Sir, not getting you exactly.

**Comment by timgraham** [comment]
The `.bashrc` file is located in `/home/<username>/.bashrc`, not in the djangoproject folder.

**Comment by ankushbadlas** [comment]
![screenshot from 2017-11-24 19-20-37](https://user-images.githubusercontent.com/7335485/33213178-9297d13e-d14c-11e7-9af4-7ebec7c38da5.png)

Please check this

**Comment by timgraham** [comment]
Yes, I see it there, row 6, column 5.

**Comment by ankushbadlas** [comment]
![screenshot from 2017-11-24 19-26-14](https://user-images.githubusercontent.com/7335485/33213383-5b7dd3e6-d14d-11e7-8607-837a0bf864d7.png)

Yes, I added the lines here you can see.

**Comment by timgraham** [comment]
Missing `export` at the start of the new line.

**Comment by ankushbadlas** [comment]
conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
django.db.utils.OperationalError: FATAL:  password authentication failed for user "djangoproject"
FATAL:  password authentication failed for user "djangoproject" 

I am getting again same error

**Comment by timgraham** [comment]
You didn't use `export DJANGOPROJECT_DATA_DIR=~/Desktop/djangoproject/djangoproject` as I suggested before.

Maybe you can find a helper in your area who knows Django? It's a bit tedious to debug this remotely.
