### ISSUE TITLE
Textbox resizing is semi-broken when creating new ticket

### ISSUE THREAD

**Issue by Zac-HD** [django/djangoproject.com#803]
Now this is a proper yak shave: I'm reporting a bug in the bug-reporting system that I'm using to report the issue that's blocking my work on the first issue.  Ahem.

If you go to create a new issue at https://code.djangoproject.com/newticket, the "description" box has a lovely note next to it that you can use wiki markup.  If you make the textbox itself narrower, the note stays in position.  But when you make it wider again, the note *retains all the added space*.

Terribly crude image:

![image](https://user-images.githubusercontent.com/12229877/33525406-f9bcb978-d882-11e7-807d-3d1ef11cd759.png)

**Comment by timgraham** [comment]
I can reproduce this at https://trac.edgewall.org/ so it doesn't seem to be specific to Django's Trac install (which has a separate bug tracker at https://github.com/django/code.djangoproject.com/).
