### ISSUE TITLE
Docs only partially translated for 2.0 French

### ISSUE THREAD

**Issue by claudep** [django/djangoproject.com#805]
Strangely, many French translated docs pages (mainly topics/refs pages) are no longer translated.
Example: https://docs.djangoproject.com/fr/2.0/ref/validators/

Could it be a cache issue? Or maybe the docs build log on the server can give some hints?
I tested the build locally and I'm not getting any special issue.

**Comment by claudep** [comment]
Seems to be solved now, might have been a temporary issue.

**Comment by claudep** [comment]
I notice that issue again today. As we can see on this capture, some parts of topics are translated while other parts remain in English.

![capture d ecran de 2018-02-08 17-38-47](https://user-images.githubusercontent.com/143192/35985549-3378c3e8-0cf7-11e8-8f32-fe0a8717095f.png)

**Comment by timgraham** [comment]
And now it looks good again? (I think that screenshot is from https://docs.djangoproject.com/fr/2.0/topics/).

**Comment by claudep** [comment]
Yes, it does. Do you have a clue about the possible culprit?

**Comment by timgraham** [comment]
Nope, I haven't looked in much detail at how the translated documentation works.

**Comment by claudep** [comment]
I suspect sphinx-build (from the `update_docs` management command) is crashing at some point. But random crashes are hard to debug :-(

**Comment by claudep** [comment]
And now it happens again. Sighhhh :-(

**Comment by claudep** [comment]
Indonesian is not affected right now, so it might be language-specific.

**Comment by claudep** [comment]
Would it be possible to receive (temporary) shell access to try debugging the issue?

**Comment by claudep** [comment]
I just committed warning fixes (from locally-run build) to the French files. Generally, warnings should not prevent a build, but who knows… We should check at next doc change.

**Comment by claudep** [comment]
Looks like last build was successful.

**Comment by claudep** [comment]
Failing again, seemingly randomly.

**Comment by tobiasmcnulty** [comment]
Is this still occurring? I've been looking at this in preparation for moving docs to a CDN and would be happy to help debug. If you can point me to a broken page I can poke around on the server.

As an aside, I noticed `compilemessages` was not being run as part of our deploy process and recently added that..but I don't think it's related to this issue (as far as I can tell the main difference you will see now is that "Version de la documentation :" is translated when looking at French, whereas before it was not).

**Comment by claudep** [comment]
It didn't happen lately, but those sort of random behavior are so hard to debug. Hopefully it's solved. Thanks for helping!

**Comment by m-aciek** [comment]
It has happened again for Polish translation for topics: https://docs.djangoproject.com/pl/2.2/topics/. Compare with 2.1: https://docs.djangoproject.com/pl/2.1/topics/.

Topics resource is not missing in django-docs-translations on 2.2 branch: https://github.com/django/django-docs-translations/tree/stable/2.2.x/translations/pl/LC_MESSAGES.
