### ISSUE TITLE
'Django at a glance' doc page assumes reader has a project set up

### ISSUE THREAD

**Issue by cyberabi** [django/djangoproject.com#806]
The 'Django at a glance' page assumes the reader previously ran `django-admin startproject mysite` but nowhere in the flow up to this point is the reader instructed to do so; mid-page the reader is instructed to run `python manage.py migrate` which will fail without this prior step; the prev link on the page goes to "Getting Started" which does not provide this instruction; the instruction does not occur until mid-page on "Writing your first Django app, part 1" which is two steps later in the flow.  This creates a negative initial experience with Django.

As a fix consider adding instruction on this page that readers first perform a minimal install and run the specified command to create a project, or a note that the instructions on this page assume a minimal install with a link to how to perform it.

**Comment by timgraham** [comment]
I'm not sure if that's needed given the caveat at the top of the page: "The goal of this document is to give you enough technical specifics to understand how Django works, but this isn’t intended to be a tutorial".

In my opinion, the reader isn't meant to follow along with those steps, but rather to read them to get a high-level overview. Anyway, bugs for the documentation actually go to https://code.djangoproject.com/ -- this ticket tracker is for the djangoproject.com website.
