### ISSUE TITLE
django admin search fields: FieldError at /admin/tropo/outcalltransfer/

### ISSUE THREAD

**Issue by minhajresgef** [django/djangoproject.com#808]
when I use a foreign key field id from current table, it throws the exception.
explained:
model A has field b which is a one to one foreign key relation to Model B. Model B has a field c which is another one to one relation to Model C.
Now when I use in Model A admin, search_fields=('b__c_id',) 
and then search for a needle in the model admin interface searchbox, it throws exception

FieldError at /admin/tropo/outcalltransfer/
Related Field got invalid lookup: icontains

But no problem for search_fields=('b__c__id',) 

Why?
for foreign key relations, table for B already has c_id right?

**Comment by timgraham** [comment]
This is the issue tracker for the djangoproject.com website.  To report bugs in Django, use https://code.djangoproject.com/. I guess it's a valid issue. Either a modeladmin validation error should be reported for the first case or the search query should be accepted.
