### ISSUE TITLE
502 Bad Gateway on long search strings

### ISSUE THREAD

**Issue by jwokaty** [django/djangoproject.com#811]
On https://docs.djangoproject.com, if I enter a string of at least 1551 characters into the search and hit enter, I get 502 Bad Gateway Nginx.

**Comment by pauloxnet** [comment]
I confirm it. I tried with a longer string getting a "414 Request-URI Too Large"

**Comment by RezaGhanbari** [comment]
I think this is related with GET request uri size restrictions [http://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html#sec10.4.15](http://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html#sec10.4.15)

**Comment by timgraham** [comment]
I guess the restriction is fine. How many characters do you need and why?
