### ISSUE TITLE
French documentation isn't translated

### ISSUE THREAD

**Issue by tamwile** [django/djangoproject.com#815]
# How to reproduce :

- Go to https://docs.djangoproject.com/fr/2.0/
- We have the same result if we go to https://docs.djangoproject.com/en/2.0/intro/ , then use the bottom right button "Language: fr" 

# Expected

The documentation in french.

# Information

- Browser: Mozilla Firefox 58.0.2 (64 bits)
- This bug doesn't appear with other languages
- I haven't this issue last week

**Comment by timgraham** [comment]
We're tracking this issue in https://github.com/django/djangoproject.com/issues/805.
