### ISSUE TITLE
Link to password reset form

### ISSUE THREAD

**Issue by rfleschenberg** [django/djangoproject.com#818]
People have trouble finding https://www.djangoproject.com/accounts/password_reset/.

Can we link to that somewhere?

**Comment by arunikayadav42** [comment]
Is anybody working on this issue or can I get started with it?

**Comment by rfleschenberg** [comment]
@arunikayadav42 As far as I am concerned, please go ahead!

**Comment by frankwiles** [comment]
As far as I can tell the only place to login is the admin and it has it prominently: 

<img width="425" alt="Screen Shot 2019-06-15 at 9 26 30 AM" src="https://user-images.githubusercontent.com/144159/59552679-b8600680-8f4f-11e9-8cba-0587a15868f6.png">

Suggest closing this.

**Comment by felixxm** [comment]
Agreed.

**Comment by rfleschenberg** [comment]
The problem here is not the admin, but Trac. On https://code.djangoproject.com/ there is a link labeled "DjangoProject Login" to https://code.djangoproject.com/login. If you forget your password for that account, it is not obvious where to request a reset.

**Comment by felixxm** [comment]
@rfleschenberg Thanks for explanation. I added a new issue in the code.djangoproject.com repository: https://github.com/django/code.djangoproject.com/issues/95.
