### ISSUE TITLE
django-admin makemessages --no-obsolete doesn't seem to be working

### ISSUE THREAD

**Issue by kishorpawar** [django/djangoproject.com#819]
First of all, I am expecting `--no-obsolete` would comment out `msgid` and `msgstr` if `gettext` is deleted, right?

How I am testing is:

1. I wrote `gettext("some string here")` in view  
2. I ran `makemessages` command  
3. It wrote a `.po` file as expected  
4. Then I deleted `gettext()` line from view and saved file, verified `runserver` working.  
5. I ran `makemessages --no-obsolete` and it has not made any changes to `.po` file.  

`.po` file content extract . 

    #. Translators: This message is a test of wrap line
    #: servers/views.py:31
    msgid "Do let me know if it works."
    msgstr ""

**Comment by timgraham** [comment]
This is the issue tracker for the djangoproject.com website. Please see [TicketClosingReasons/UseSupportChannels](https://code.djangoproject.com/wiki/TicketClosingReasons/UseSupportChannels) for ways to get help with Django usage. The ticket tracker for Django itself is https://code.djangoproject.com/.
