### ISSUE TITLE
models that are not tables but not abstract

### ISSUE THREAD

**Issue by amineparis** [django/djangoproject.com#820]
I have this recurrent need that I handle entities that are not tables but calculated entities from other models. 

**Consider this example :** 
an entity that I call `task` that is calculated using the model `suggestion` a task may be to approve a suggestion, to pilot a suggestion, to close a suggestion. the task model can't be in the database but it is handled exactly like a model (it has fields that are calculated from other models, it should have views, serializers using DRF).

**Problem**
Since there is no way in django to handle this kind of entities as models I need to make exception to make it follow same process as other models except the fact that it is not in the database.

It would be great to find a way to integrate this in the next django version

**Comment by shaib** [comment]
Hi,

This is the repository for the Django's project *website*, not Django itself. For advice on using Django, please see https://docs.djangoproject.com/en/2.0/faq/help/
