### ISSUE TITLE
[BUG?] Django ORM Group by on two keys in Single Table

### ISSUE THREAD

**Issue by ok9897** [django/djangoproject.com#822]
class ConcurrentUser(models.Model):
    logtime = models.DateTimeField(primary_key=True)
    country = models.CharField(max_length=10)
    pcu = models.IntegerField(blank=True)
    update_ts = models.DateTimeField(blank=True)

I wanted data to group by 'country' and 'logtime'. and made ORM sentence, like below.
'''
res = res_tmp.values('country', 'logtime').annotate(hourly_sum=models.Sum(core_v))\
                    .values('country', 'logtime', 'hourly_sum').order_by('-hourly_sum')
'''

But, query is converted to the SQL sentence, below, by Django ORM.
'''
SELECT `country`, `logtime`, SUM(`pcu`) AS `hourly_sum` FROM `concurrent_user`
GROUP BY `logtime` ORDER BY `hourly_sum` DESC
'''

Why does Django Annotation ignore 'country' key in values() when making group_by query? 
How can I fix this problem with Django ORM?

**Comment by felixxm** [comment]
This is the repository for the Django's project website, not Django itself. Please see [FAQ: Getting Help](https://docs.djangoproject.com/en/2.0/faq/help/#how-do-i-do-x-why-doesn-t-y-work-where-can-i-go-to-get-help).
