### ISSUE TITLE
SET SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED

### ISSUE THREAD

**Issue by LyAllence** [django/djangoproject.com#824]
*** SET SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED**

** python **: 3.6
** django **: 2.0.4
** mysql **:Ver 14.14 Distrib 5.1.26-rc, for Win32 (ia32)
** pymysql **: 0.8

## problem
When i use "python manage.py migrate", I get a this message.

## my code
mysite/mysite/__init__.py
`import pymysql

pymysql.install_as_MySQLdb()
`

/mysite/mysite/setting.py
`        'ENGINE': 'django.db.backends.mysql',

        'NAME': "django",

        'USER': 'root',

        'PASSWORD': '120800',

        'HOST': '127.0.0.1',

        'PORT': '3306',

        'OPTIONS': {'isolation_level': 'read committed'},
`

**Comment by timgraham** [comment]
This is the issue tracker for the djangoproject.com website. Please see [TicketClosingReasons/UseSupportChannels](https://code.djangoproject.com/wiki/TicketClosingReasons/UseSupportChannels) for ways to get help with Django usage.
