### ISSUE TITLE
CORS Problem - Method PATCH is not allowed by Access-Control-Allow-Methods

### ISSUE THREAD

**Issue by shariquesha** [django/djangoproject.com#833]
I am using Agular5 and Django Rest Frame work . All methods work fine with cors , like GET,POST,PUT , but I am getting Method PATCH is not allowed by Access-Control-Allow-Methods in preflight response. I have read about this on stackoverflow that this problem is related to CORS header.

I found a solution a on stackoverflow where it was said that I have to explicitly allow Control Allow Methods in django. So I made a middleware.py file and included it in MIDDLEWARES in settings.py file , my middleware.py content is as follow
`class MyMiddleware:

    def __init__(self, get_response):
        self.get_response = get_response

    def __call__(self, request):
        response = self.get_response(request)
        response['Access-Control-Allow-Methods'] = 'GET, POST, PUT, PATCH, DELETE, OPTIONS'
        return response`

But still I am getting this error .what should I do I am stuck at it .

**Comment by shaib** [comment]
Hi @shariquesha ,

I'm sorry, but this is where we track problems with the djangoproject.com website -- it is not a place for general questions about using Django. I suggest you try writing to the django-users mailing list or the #django IRC channel; you can find links and details at https://docs.djangoproject.com/en/2.0/faq/help/ 

When you write there, it could be helpful if you could provide the request and response headers which are transmitted when you see the problem.
