### ISSUE TITLE
'WSGIRequest' object has no attribute 'user'

### ISSUE THREAD

**Issue by markolofsen** [django/djangoproject.com#834]
I can't open /admin/ and got an message `'WSGIRequest' object has no attribute 'user'`

Django 2.0.6
In settings I'm using MIDDLEWARE_CLASSES

**Comment by timgraham** [comment]
This is the issue tracker for the djangoproject.com website. Please see [TicketClosingReasons/UseSupportChannels](https://code.djangoproject.com/wiki/TicketClosingReasons/UseSupportChannels) for ways to get help with Django usage.

You should read the Django 2.0 release notes. Support for `MIDDLEWARE_CLASSES` is removed.
