### ISSUE TITLE
RPC documentation page formatting issues

### ISSUE THREAD

**Issue by dotgourav** [django/djangoproject.com#836]
The formatting on the page is broken: [URL](https://code.djangoproject.com/rpc)

Tested on Firefox and Chrome.

Screenshot:
![screenshot-2018-7-7 remote procedure call rpc django](https://user-images.githubusercontent.com/2922351/42409369-164b3e16-81f7-11e8-94b5-200802073467.png)

**Comment by ser-gent** [comment]
It's beacause of text-indent: "-4em" in the <td></td> tag

**Comment by carltongibson** [comment]
AFAICS that page isn't directly editable, so this would be an issue with Trac itself, hopefully resolved in a future version when we can update. (I don't know if there's an upstream issue)
