### ISSUE TITLE
Announce LTS better

### ISSUE THREAD

**Issue by beruic** [django/djangoproject.com#838]
At my company, long term support is important, and we therefore primarily use the LTS version of Django. However the djangoproject.com web site fails in announcing the LTS version, and only really advertises the newest version.
It seems a bit odd to have an LTS version (which is great BTW), but not being proud enough of it to announce it equal to the newest version.

**Comment by arunikayadav42** [comment]
Is anybody working on this issue or can I get started with it?

**Comment by carltongibson** [comment]
Before jumping on this, I'd at least enquire on Django-developers **if** this is something actually desired. (I'd bet it's been discussed before.) 

Personally, I think the LTS is wrong for most people. It sounds great but then you always end up wanting the new features and the new support: you're better off getting on the latest version and updating. (Yes, for some deployments that's not true.)

**Comment by arunikayadav42** [comment]
Hey @carltongibson I am pretty excited to contribute to the django society but havent been able to find the right kind of project to contribute to..i know the basics of django and wish to delve further into learning django rest framework.If you could help me out it will be great.

**Comment by carltongibson** [comment]
Hi @arunikayadav42, welcome aboard! 🎉

I should have a standard answer to that. Send me an email — linked on my profile — telling me if your looking to learn or contribute (or both). I'll write up something over the holidays. 

In want of that, the canonical point of departure for contributing is: https://docs.djangoproject.com/en/dev/internals/contributing/

🙂

**Comment by carltongibson** [comment]
OK, having reviewed it, I'm going to close this. 

For me, the LTS **isn't right** for most users. For those for whom it is, it's clearly enough stated which versions are supported, and which are LTS, and so on.

**Comment by shaib** [comment]
Actually, if you look at the website right now, you need to go to some length to realize that the latest version is, in fact, LTS, and not just the latest one.
I'm not sure we should "announce [the latest LTS] equal to the newest version" as the OP asked, but I think we should be writing "(LTS)" next to any LTS version.

**Comment by carltongibson** [comment]
Hey @shaib. 🙂

I am looking at it right now. I was yesterday too. **I** think (emphasis on the `I` there) that the _Supported Versions_ section is plenty clear enough. 

Roughly, why would I leave it as it is? Because choosing to use the LTS is an advanced decision, and if you can't pick up which version you want from the _Supported Versions_ section—or more if you can't even get that far—then just want the one at the top. (Do feel free to disagree; emphasis on the `I, recall :)

I guess we could do an `{% if current.is_lts %} (LTS){% endif %}` on [this line here]({% if previous.is_lts %} (LTS){% endif %}) but there aren't any more places before the _Supported Versions_ section (I think).

**Comment by shaib** [comment]
Adding that template fragment sounds good to me, but it's not the only place; I'd also add something similar [here](https://github.com/django/djangoproject.com/blob/30464e69c3cbcb19303a716ebc22c517b52f0e83/djangoproject/templates/releases/download.html#L199), because IMO without it the sidebar is implying that the latest version is not LTS.

**Comment by beruic** [comment]
@shaib Also, if the current version is not LTS, it would be nice with a link to the newest LTS.

**Comment by beruic** [comment]
It would also be nice if the button on the front page did not look like a direct download link, but made it clear that it is leading to the download section, which (sometimes) offer both a current version and an LTS version.

E.g.:

     ---------------------------
    |    **Go to downloads**    |
    | latest release: 2.2.4 LTS |
     ---------------------------

and perhaps in the future:

     ----------------------- 
    |  **Go to downloads**  |
    | latest release: 3.0.0 |
    | latest LTS:     2.2.9 |
     -----------------------

**Comment by carltongibson** [comment]
OK, so again, I'm -1 on increasing the visibility of the LTS like this. It's not appropriate for most users, and we're adding a decision point **right at the beginning** of _Which version should I use?_ when we **should** (as we currently are) be guiding them straight to the correct answer there: _Use the latest supported version_. 

By the time folks are ready to decide whether they want the LTS, the _Supported Versions_ section is there, and waiting, and quite clear.

**Comment by shaib** [comment]
FWIW I completely agree with @carltongibson here. I argued for marking a version as LTS whenever it is already displayed (because I think doing otherwise may cause confusion about whether it is LTS or not), but I do not think we should raise the visibility of any version that isn't the latest one.

**Comment by beruic** [comment]
@carltongibson I see your point, and after some thought, I agree.
I would, however, still like the button to resemble my first example, so it is clear that it leads to the download section, instead of looking like it could be a direct link to a download.

**Comment by beruic** [comment]
Please review the change I just posted. I will create a PR if you agree.

**Comment by carltongibson** [comment]
Hi @beruic. I created #933.

**Comment by beruic** [comment]
@carltongibson Yes, I saw it. My change is for the download button: https://github.com/beruic/djangoproject.com/commit/3e80774aa8ee8df832fe660d1583020a84ce727b
