### ISSUE TITLE
when using runserver, new /static/ directories are not picked up until you stop and start the server

### ISSUE THREAD

**Issue by KimSJ** [django/djangoproject.com#840]
Whilst development server is running, create a new app. add the usual ./static/appname/file.xxx sort of stuff. The file will not be served until you restart (using `python manage.py runserver`). The automatic restart doesn't seem to be complete enough.

Worth a mention in the `https://docs.djangoproject.com/en/2.1/howto/static-files/` page.

**Comment by timgraham** [comment]
This is the issue tracker for the djangoproject.com website. Please use [Trac ticket](https://code.djangoproject.com/) to reproduce documentation issues.

As an aside, I can't reproduce the problem you describe.
