### ISSUE TITLE
Error when I access the path in django 2.1

### ISSUE THREAD

**Issue by StevenMedina** [django/djangoproject.com#841]
Hello, I did an update of a project for django 2.1 from 2.0.8 but when I try to access I have 2 errors

![slack](https://user-images.githubusercontent.com/9811859/44412890-982e0980-a52f-11e8-81df-e82b2534dc8f.png)
![1__docker-compose_up__docker-compose_](https://user-images.githubusercontent.com/9811859/44412819-72086980-a52f-11e8-8f17-38ced320c46f.png)
![attributeerror_at__](https://user-images.githubusercontent.com/9811859/44412928-b0058d80-a52f-11e8-92bf-e2a68c6934d8.png)

Could you help me please, thanks

**Comment by timgraham** [comment]
This is the issue tracker for the djangoproject.com website. Please see [TicketClosingReasons/UseSupportChannels](https://code.djangoproject.com/wiki/TicketClosingReasons/UseSupportChannels) for ways to get help with Django usage. Maybe you're using some component that's not compatible with Django 2.1 but without steps to reproduce the problem it's impossible to say.
