### ISSUE TITLE
Community blog isn't updating

### ISSUE THREAD

**Issue by pydanny** [django/djangoproject.com#842]
This doesn't seem to be picking up posts: https://www.djangoproject.com/community/blogs/

I know this because today I posted a Django article and it still hasn't appeared. 

* Article: https://www.pydanny.com/using-executable-code-outside-version-control.html
* Feed with article: https://www.pydanny.com/feeds/django.atom.xml

**Comment by timgraham** [comment]
It may have been a mistake on your end. That post is in the djangoproject.com database with a date of August 3.

**Comment by pydanny** [comment]
Ah... when I first posted that article it had the wrong date. I corrected it a few minutes later but I guess I didn't do it fast enough. Is that something you can fix on your end?

**Comment by timgraham** [comment]
Done.
