### ISSUE TITLE
Outputting PDFs with Django

### ISSUE THREAD

**Issue by alhman** [django/djangoproject.com#846]
We recently released our tool ReportBro v1.0 which consists of a javascript plugin ( https://github.com/jobsta/reportbro-designer ) to design report templates and a Python package ( https://github.com/jobsta/reportbro-lib ) to create pdf and Excel files using those templates. It's very easy to integrate into Python web applications - we have a Django demo application showing how to create pdf reports.

In case you find our tool useful it would be great if you could add it to the documentation about pdf ( https://docs.djangoproject.com/en/2.1/howto/outputting-pdf/ ) or another page in the howto section.

**Comment by timgraham** [comment]
We generally don't endorse third party libraries in the Django documentation. Feel free to add your project to https://djangopackages.org/.

**Comment by alhman** [comment]
ok, thank you!
