### ISSUE TITLE
File a bug link on Wiki page- it's black

### ISSUE THREAD

**Issue by Deyspring** [django/djangoproject.com#848]
The visited link for "file a bug" on the wiki page is very dark green #156641, which is almost identical to the surrounding black text making it impossible to see that it is a link.

**Comment by timgraham** [comment]
Moved to https://github.com/django/code.djangoproject.com/issues/88.

**Comment by mayoroftuesday** [comment]
This is actually an issue with code.djangoproject.com. Copying to https://github.com/django/code.djangoproject.com/issues/88.

Recommend we close this one.
