### ISSUE TITLE
Better UX for website newticket page

### ISSUE THREAD

**Issue by Deyspring** [django/djangoproject.com#849]
The UX for the website newticket page is very confusing. 
https://code.djangoproject.com/newticket

I would suggest something like the following changes be made: 
Visited links _should not_ be a dark green that is almost black. 
Layout should be as follows with text changes for clarity: 

**### Bug Tickets**  # Big title 
Please read this first # Large heading
	Don’t report security issues here! Contact <url here> # smaller heading, not black 
	Don’t use this form for general questions. Check the FAQ # smaller heading, not black 

Issues # Large heading
	Django Project Code Issues # smaller heading 
		Use the below form to create new tickets and for best response: 
- Follow bug reporting guidelines<link>
- Follow patch submition guidelines<link>
- Go through the bug checklist<link>
- Use Preview<link> to check your formatting. 

Django Website Issues #Large heading 

- For issues with the website report here: 
- <<em>> www <em.>.django.com<</em>>  ##!! www must be very emphasized ##
- For issues with the website <em> code tracker</em> report here:	
- <<em>> code<em>. django.com</em> ##! www must be very emphasized to tell the difference from the above link 

Bugs with Translation? Report on Transifex <link>#Large heading

**Comment by timgraham** [comment]
Moved to https://github.com/django/code.djangoproject.com/issues/87.
