### ISSUE TITLE
How to add placeholder UserCreationForm django?

### ISSUE THREAD

**Issue by gnoo0** [django/djangoproject.com#852]
I'm trying to add a placeholder to the username field in the UserCreationForm but i can't understand how to do it. I have already change the forms.py file in this way /lib/site-packages/django/contrib/auth/forms.py.

I add a placeholder to password1 and password2 fields and work like this:
![captura de ecra_2018-11-11_11-55-40](https://user-images.githubusercontent.com/43119920/48312569-c9572c80-e5a8-11e8-9ed1-5dd00a13563d.png)

I can see probably the username field is coming from class meta:

![captura de ecra_2018-11-11_11-56-58](https://user-images.githubusercontent.com/43119920/48312583-ebe94580-e5a8-11e8-9d24-eebd9980ccf9.png)

from this class but i'm not sure about that
![captura de ecra_2018-11-11_11-57-52](https://user-images.githubusercontent.com/43119920/48312590-0c190480-e5a9-11e8-8202-1d1246b0a578.png)

I don't understand how add a placeholder to username field.

thanks..

**Comment by felixxm** [comment]
This is the repository for the Django's project website, not Django itself. Please see [FAQ: Getting Help](https://docs.djangoproject.com/en/2.1/faq/help/#how-do-i-do-x-why-doesn-t-y-work-where-can-i-go-to-get-help).

**Comment by gnoo0** [comment]
Ok sorry about that
