### ISSUE TITLE
pyhton manage.py migrate not working

### ISSUE THREAD

**Issue by Pokiha1** [django/djangoproject.com#854]
Dear every one, 
i'm new in the Django cms environment, and I need your help ! ( please :) )

When I tried to "install" the cms is not working, I had a long list of error message 

> `(venv) project@project-web:~/work.project.www$ python manage.py migrate
Traceback (most recent call last):
  File "manage.py", line 10, in 
    execute_from_command_line(sys.argv)
  File 
"/home/project/venv/local/lib/python2.7/site-packages/django/core/management/__init__.py", 
line 364, in execute_from_command_line
    utility.execute()
  File 
"/home/project/venv/local/lib/python2.7/site-packages/django/core/management/__init__.py", 
line 338, in execute
    django.setup()
  File 
"/home/project/venv/local/lib/python2.7/site-packages/django/__init__.py", 
line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File 
"/home/project/venv/local/lib/python2.7/site-packages/django/apps/registry.py", 
line 116, in populate
    app_config.ready()
  File 
"/home/project/venv/local/lib/python2.7/site-packages/django/contrib/admin/apps.py", 
line 23, in ready
    self.module.autodiscover()
  File 
"/home/project/venv/local/lib/python2.7/site-packages/django/contrib/admin/__init__.py", 
line 26, in autodiscover
    autodiscover_modules('admin', register_to=site)
  File 
"/home/project/venv/local/lib/python2.7/site-packages/django/utils/module_loading.py", 
line 50, in autodiscover_modules
    import_module('%s.%s' % (app_config.name, module_to_search))
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File 
"/home/project/venv/local/lib/python2.7/site-packages/cms/admin/__init__.py", 
line 11, in 
    plugin_pool.plugin_pool.discover_plugins()
  File 
"/home/project/venv/local/lib/python2.7/site-packages/cms/plugin_pool.py", 
line 33, in discover_plugins
    invalidate_cms_page_cache()
  File 
"/home/project/venv/local/lib/python2.7/site-packages/cms/cache/__init__.py", 
line 69, in invalidate_cms_page_cache
    version = _get_cache_version()
  File 
"/home/project/venv/local/lib/python2.7/site-packages/cms/cache/__init__.py", 
line 20, in _get_cache_version
    _set_cache_version(1)
  File 
"/home/project/venv/local/lib/python2.7/site-packages/cms/cache/__init__.py", 
line 33, in _set_cache_version
    get_cms_setting('CACHE_DURATIONS')['content']
TypeError: 'int' object has no attribute '__getitem__'
(venv) project@project-web:~/work.project.www$
`

OS: Ubuntu / Debian
Version of python: 2.7

In advance , 
Thank's so much

**Comment by ubernostrum** [comment]
This repository is for the code that powers the djangoproject.com web site.

For questions about how to use Django, or help with problems when learning Django, please use [the django-users mailing list](https://groups.google.com/forum/#!forum/django-users).
