### ISSUE TITLE
404 url in docs.djangoproject.com/en/dev/ref/models/querysets/

### ISSUE THREAD

**Issue by omi10859** [django/djangoproject.com#856]
Over here https://docs.djangoproject.com/en/dev/ref/models/querysets/ under "When QuerySets are evaluated" in "- Slicing" url to "Limiting QuerySets" is set  wrong(404 page not found)

**Comment by timgraham** [comment]
I don't see a problem. The linked URL is https://docs.djangoproject.com/en/dev/topics/db/queries/#limiting-querysets, right?

**Comment by omi10859** [comment]
wow... it seems to be working now
