### ISSUE TITLE
https://docs.djangoproject.com/en/dev/releases/1.11/ - add to the docs

### ISSUE THREAD

**Issue by uri-rodberg** [django/djangoproject.com#857]
https://code.djangoproject.com/ticket/30078

1. https://docs.djangoproject.com/en/dev/releases/1.11/ should contain something like "running Django 1.11.* with Python 3.7 with deprecation warnings enabled will raise a DeprecationWarning." or similar.

2. Change from 1.11.17 to 1.11.18.

3. Change "will end in April 2018." to "ended in April 2018."

Same for all versions of this doc such as https://docs.djangoproject.com/en/1.11/releases/1.11/.

**Comment by felixxm** [comment]
This is the repository for the Django's project website, not Django itself. Please see [FAQ: Getting Help](https://docs.djangoproject.com/en/2.1/faq/help/#how-do-i-do-x-why-doesn-t-y-work-where-can-i-go-to-get-help).

**Comment by uri-rodberg** [comment]
> This is the repository for the Django's project website, not Django itself. Please see [FAQ: Getting Help](https://docs.djangoproject.com/en/2.1/faq/help/#how-do-i-do-x-why-doesn-t-y-work-where-can-i-go-to-get-help).

I asked to modify https://docs.djangoproject.com/en/dev/releases/1.11/. Isn't it the right project?

**Comment by felixxm** [comment]
You asked to modify Django's documentation which is only hosted by djangoproject.com. Any issues related with documentation should be reported on [Trac](https://code.djangoproject.com/). Please continue discussion in the ticket [30078](https://code.djangoproject.com/ticket/30078).

**Comment by uri-rodberg** [comment]
> You asked to modify Django's documentation which is only hosted by djangoproject.com. Any issues related with documentation should be reported on [Trac](https://code.djangoproject.com/). Please continue discussion in the ticket [30078](https://code.djangoproject.com/ticket/30078).

Added new ticket https://code.djangoproject.com/ticket/30082 - this is only about the documentation.
