### ISSUE TITLE
no error when multipart contentlength > FILE_UPLOAD_MAX_MEMORY_SIZE

### ISSUE THREAD

**Issue by vovavovavovavova** [django/djangoproject.com#861]
Good day.

Reproducing problem : 

1) settings.py 

FILE_UPLOAD_MAX_MEMORY_SIZE = 203 * (1024**2)

2) make post request to view method, uploading file over this size (203+ Mb)
3) Expected behaviour : Exception / deny response

4) actual behaviour : file uploads into temp directory (when it should not). If i don't write manual size checking  _**in my view**_, it will upload and will do actions they shouldn't! If i do write manual size check _**in my view**_, file will be uploaded in temp anyway!

5) question : how can i prevent accepting files over max size, avoiding it reading, via Django without apache/ngnix etc?

**Comment by timgraham** [comment]
This is the issue tracker for the djangoproject.com website. Please see [TicketClosingReasons/UseSupportChannels](https://code.djangoproject.com/wiki/TicketClosingReasons/UseSupportChannels) for ways to get help with Django usage.
