### ISSUE TITLE
Google search results are showing French translations for English language links

### ISSUE THREAD

**Issue by rhelms** [django/djangoproject.com#868]
Recently in my google searches for django things, French translations have been showing for English links.

For example, this search (https://www.google.com/search?client=ubuntu&channel=fs&q=django+refresh_from_db&ie=utf-8&oe=utf-8) resulted in https://docs.djangoproject.com/en/2.1/ref/models/instances/ being the displayed URL, but French is displayed.

Luckily, django methods are all in English, but could be an issue if I was searching for django concepts that did have a method associated.

![2019-02-20-094421_1916x1053_scrot](https://user-images.githubusercontent.com/815879/53055707-6b65a980-34f4-11e9-9c6f-5c58f145290d.png)

**Comment by timgraham** [comment]
@tobiasmcnulty - could this be related to your recent changes?

**Comment by tobiasmcnulty** [comment]
That's...odd. I don't think anything I've changed could be causing that, but it's certainly possible I could be proven wrong.

Could this be the inverse of #805?

I did notice a potential, related issue while working on language activation in the umerged PR #862. Specifically, the site does not activate English if that's the language the user is requesting, so it would inherit whatever language was set previously for that uswsgi thread or by `LocaleMiddleware`. But, I didn't think this applied to the documentation itself, just the strings on the site.

**Comment by claudep** [comment]
That could be a bug in Google too!

**Comment by m-aciek** [comment]
May it be connected somehow with also mysterious #627?

**Comment by m-aciek** [comment]
I think this has a chance to be solved with #862 PR. Google might have been fooled by headers telling that pages were localized when they weren't (so it thought French title is an English title then, and use it as more fresh (recently changed)).

**Comment by tobiasmcnulty** [comment]
The `LocaleMiddleware` removal for docs.djangoproject.com has been deployed (#862), so please keep an eye out for any changes. I've also noticed a few search results coming back in French (but linking to the English URLs), so hopefully this helps (though I'm still not seeing how it will, unless Google is indeed doing something odd...).

**Comment by nitinnain** [comment]
Google search for "Django Tutorial Admin" shows the Search Snippets in Indonesian. 

See attached screenshot. 
The text "Menulis aplikasi Django kedua anda, bagian 2" is in Indonesian. 
Notice that the URL is for "en" (English), but the Google Search snippet shown is for the "id" (Indonesian) webpage. Here are the two pages.
EN: https://docs.djangoproject.com/en/2.1/intro/tutorial02/
ID: https://docs.djangoproject.com/id/2.1/intro/tutorial02/

- I have never setup Indonesian on my browser.
- I checked on two different computers (One computer at India and another at US, both showed the same error, even though they are entirely different machines and configured with English.)


**Debugging Hint:**

Open Page Source for this https://docs.djangoproject.com/en/2.1/intro/tutorial02/ in your browser,
and look fo `rel="alternate"` or  `hreflang=`

These attributes control the language in which the page is displayed in the browser. I didn’t see anything obviously wrong on the HTML page itself. 

The title "Menulis aplikasi Django kedua anda, bagian 2" 
is in Indonesian. Notice "id" in the URL here:
https://docs.djangoproject.com/id/2.1/intro/tutorial02/

<img width="653" alt="django google search snippet error" src="https://user-images.githubusercontent.com/2798690/53386196-44512100-39a7-11e9-997f-f43a1714803e.png">

**Comment by charettes** [comment]
This is really weird, I get a `/fr/` URL in Indonesian with the same search with a `Accept-Language` favouring `fr-CA`

![](https://zappy.zapier.com/79DB0327-2DA2-4C0C-B419-032626AA6068.png)

**Comment by claudep** [comment]
Does anyone know someone at Google we could report this issue to?

**Comment by m-aciek** [comment]
Do we have Google Search Console [1] set up for docs.djangoproject.com? Is
it showing any hints or errors? We should inspect also our sitemap, if it
is correct.

Regards,
Maciej

[1] https://search.google.com/search-console/about

wt., 26.02.2019, 08:24 użytkownik Claude Paroz <notifications@github.com>
napisał:

**Comment by kezabelle** [comment]
Chiming in to point out, in case it hasn't been noted already: the cached copy for "Django Tutorial Admin" in Indonesian (with the English link) has `<html lang="id">` (which is set in the `base_docs.html` by `{% block html_language_code %}{{ lang|default:"en" }}{% endblock %}` and ultimately by a call to `activate(lang)`)

**Comment by m-aciek** [comment]
I found an article about i18n and Google [1]. We do not follow its
guidelines for sitemaps (link rel alternate & hreflang).

Maciej

[1] https://support.google.com/webmasters/answer/189077

wt., 26.02.2019, 09:28 użytkownik Keryn Knight <notifications@github.com>
napisał:

**Comment by tobiasmcnulty** [comment]
Interestingly the Google search link that originally prompted this issue now shows English again. But yes, I see Indonesian text when Googling "Django Admin Tutorial" now, too:

https://www.google.com/search?q=django+tutorial+admin

It feels very much like a caching issue, but I don't see where it could be occurring 😦 

It looks like @aaugustin may have verified the domain with Google Webmaster Tools about 6 years ago (https://github.com/django/djangoproject.com/commit/a0907ff742c81b676f602d1e17d820152f95d22e);  would you be able to grant me access to this if you still have it @aaugustin ?

**Comment by timgraham** [comment]
I have access to the Google Search Console but I don't see how I can give access to others. Here's hthe report for https://docs.djangoproject.com/en/2.1/intro/tutorial02/

![screenshot from 2019-02-26 09-35-48](https://user-images.githubusercontent.com/411869/53420599-14efe380-39aa-11e9-9d32-a33cb2922f5a.png)

This is the information about "Google-selected canonical" https://support.google.com/webmasters/answer/9012289#google-selected-canonical

**Comment by m-aciek** [comment]
In docs' metatags we set canonical per page (for example `.../id/2.1/intro/tutorial02`'s canonical is `.../id/2.1/intro/tutorial02`). IMO it can interfere badly with rel='alternate' links. Like if something have alternate links, those alternatives should have only one canonical.

Possible solution then would be to set canonicals for all languages to `en` versions of documentation pages.

**Comment by nitinnain** [comment]
Just saw French on another search 
*(I had reported Indonesian earlier. I see Google search snippets in both languages depending on search query):*
![Google "Django Admin Actions"](https://user-images.githubusercontent.com/2798690/53427368-d80a0800-3a0e-11e9-95e3-26ea44261d09.png)

**The problem doesn't occur up on [DuckDuckGo](https://duckduckgo.com/)!**

**Comment by m-aciek** [comment]
Another article seems to support my thesis: https://developers.google.com/search/mobile-sites/mobile-seo/separate-urls. rel:canonical and rel:alternate are treated equally. AFAIC we should make canonical point to English versions.

**Comment by m-aciek** [comment]
I've just opened draft pull request #871.

**Comment by tobiasmcnulty** [comment]
It is indeed odd that google chose the 'id' version of that page as canonical, but I'm not sure #871 is the appropriate fix:

<img width="704" alt="screenshot 2019-02-26 21 12 28" src="https://user-images.githubusercontent.com/160132/53460524-6c726b80-3a0b-11e9-8a34-e2ab82f41a93.png">

From: https://support.google.com/webmasters/answer/139066?hl=en

**Comment by tobiasmcnulty** [comment]
To throw another theory out there, I think we are misusing `x-default`:

https://webmasters.googleblog.com/2013/04/x-default-hreflang-for-international-pages.html

This page seems to suggest that use of `x-default` should be limited to pages that have no specific language (it's not a "default language"). We appear to render it on all docs pages with a link to the English version of the page, so perhaps that's confusing Google?

https://github.com/django/djangoproject.com/blob/master/djangoproject/templates/docs/doc.html#L26-L30

We also only render `<link rel="alternate" ..>` for the canonical version of the docs:

https://github.com/django/djangoproject.com/blob/master/docs/views.py#L52

It would seem appropriate to render that for all versions?

**Comment by m-aciek** [comment]
FTR: issue #621 started with the same topic and started SEO for djangoproject.com.

**Comment by tobiasmcnulty** [comment]
Good find @m-aciek .

@apollo13 It looks like my PR #872 partly reversed what you did here: https://github.com/tobiasmcnulty/djangoproject.com/commit/d6a966f6506a6c15b5f823edfb31491616989dca#diff-edc52c8f3a604a128e8f302806fb9262

Any memory of what the reason was for that and/or do you have any objections to showing the hreflang tags on all docs versions (not just the canonical one)?

**Comment by tobiasmcnulty** [comment]
If this doesn't work, another thing we might try is refactoring the sitemap to use hreflang-style link declarations as described here: https://support.google.com/webmasters/answer/189077?hl=en

Right now it looks like each language gets its own sitemap.

**Comment by apollo13** [comment]
Puh, I will give it a look in the afternoon. The main thing is that documentation on what Google interprets how is rather sparse. So I tried (over a few weeks) what worked best at that time and then committed that. That doesn't mean it is the best approach nowadays though.

**Comment by apollo13** [comment]
@tobiasmcnulty I was mainly following https://github.com/django/djangoproject.com/issues/621#issuecomment-216253813 when coming up with which rels should point where… I'll see that I can give you access to the google search tools.

**Comment by tobiasmcnulty** [comment]
Thanks @apollo13 I see your commit implemented exactly what that page recommends. I guess we can see how it behaves with the hreflang tags on all pages for a bit and then revert if there's a regression.

@timgraham @m-aciek I found this link which seems to suggest that making English (or any one language) the canonical version of the page is not correct (see the the "Most common mistakes implementing hreflang and canonical tags" heading): https://www.portent.com/blog/seo/implement-hreflang-canonical-tags-correctly.htm

But again, who knows if these 3rd parties have it correct or not. 😕

**Comment by tobiasmcnulty** [comment]
Here's a list of the current (last updated by Google on 2/25/19) URLs that Google chose as canonical instead of the ones we suggested. None of them looks particularly worrisome: https://docs.google.com/spreadsheets/d/16oYtNJVhqAVH7wyIza10z1Pv4NhpSbx8g0QG9EpDGQE/edit#gid=0 (we don't happen to have a snapshot of this from a week or so ago, do we?)

Also, I've taken a snapshot of the full current index coverage report here, with some commentary and links to other, related issues: https://docs.google.com/spreadsheets/d/1l86YAEcw5CbvivuY-ZN81oy75Nh7T9g0eJX0sZ8Jww0/edit#gid=0

In particular #878 may be relevant to this issue.

**Comment by tobiasmcnulty** [comment]
Still not fixed 🙁 

<img width="795" alt="Screenshot 2019-03-18 20 55 05" src="https://user-images.githubusercontent.com/160132/54572906-2c762700-49c0-11e9-8edf-a956c16d9b7c.png">

**Comment by apollo13** [comment]
Hrmpf :( If google would document how that stuff is supposed to work :( I mean it worked for years :/

**Comment by WoLpH** [comment]
Indeed, this was scraped 2 days ago and in French: https://webcache.googleusercontent.com/search?q=cache:uxFlZ6Hw5RMJ:https://docs.djangoproject.com/en/2.1/topics/db/examples/many_to_many/+&cd=1&hl=en&ct=clnk&gl=nl

Not sure if it's somehow possible to purge this from the Google results using the webmaster tools, but the tags look mostly ok right now. The only thing that's wrong is that there is a `pt-BR` for example, but not `pt`

**Comment by timgraham** [comment]
I'd think we'd have some recent activity since 2019 if this were still an issue, so closing, at least for now.
