### ISSUE TITLE
Regarding django signal post_save

### ISSUE THREAD

**Issue by Murugaraju** [django/djangoproject.com#891]
Hi Team,

The below code snippet method need to be executed for every save or update of the Expiry model instance, I ran the dajngo server, parallel I used shell take an instance of model and execute save method, it does not print the statement in django server console to see.

```
from django.db.models.signals import post_save,pre_save
from django.dispatch import receiver
from api.models import *
@receiver(post_save,sender=Expiry)
def chann_working(sender,instance, **kwargs):
   print("I am printing")
```

**Comment by felixxm** [comment]
This is the issue tracker for the djangoproject.com website. Please see [TicketClosingReasons/UseSupportChannels](https://code.djangoproject.com/wiki/TicketClosingReasons/UseSupportChannels) for ways to get help with Django usage.
