### ISSUE TITLE
static.djangoproject.com down?

### ISSUE THREAD

**Issue by WoLpH** [django/djangoproject.com#895]
I'm currently not seeing any static files on djangoproject.com and it seems that's due to static.djangoproject.com being unable to resolve.
A quick downdetector shows me that I'm not alone: https://downforeveryoneorjustme.com/static.djangoproject.com

Did anything change in the DNS config or is it temporary?

**Comment by WoLpH** [comment]
A partial nevermind.... after a bit more searching it appears that it ended up in a blocklist.

WARNING BIG FILE! https://raw.githubusercontent.com/EnergizedProtection/block/master/spark/formats/hosts

**Comment by timgraham** [comment]
The recent changes are described at https://groups.google.com/d/topic/django-developers/UovZxrUPWLU/discussion.

**Comment by WoLpH** [comment]
I've reported the block yesterday and it seems to have been removed again today so it should be good.

Perhaps it was someone's attempt at an april fools joke to block a load of domains, I've seen more sites with issues.
