### ISSUE TITLE
Donation is not working

### ISSUE THREAD

**Issue by cgl** [django/djangoproject.com#905]
When I try to use the stripe form to make a donation, payment failed with this message:

We're sorry but something went wrong while processing your card details. No charge was done. Please try again or get in touch with us.

I tried to reproduce the error locally but it works as expected locally.

**Comment by cgl** [comment]
Looking more into the code its throwing `stripe.error.InvalidRequestError` and it is only happening on monthly donations.

This might be the cause of the problem:
https://support.stripe.com/questions/how-do-i-upgrade-my-stripe-integration-from-tls-1-1-to-tls-1-2#content

Need the stripe logs to make sure what is the real cause of the problem.

**Comment by carltongibson** [comment]
Hi @cgl. Thanks for this, and for #906. It's not forgotten: we're just doing some behind-the-scenes work...

> Need the stripe logs to make sure what is the real cause of the problem.

This. We need to line up some bits to make working with contributors here feasible/safe/etc. 

Thank you for your input!

**Comment by frankwiles** [comment]
This should be fixed yes?

**Comment by carltongibson** [comment]
Hey @frankwiles. Yes. 

The question is **exactly** what's broken? Payments in general seem to be going through...

> ...it is only happening on monthly donations.

@cgl Can you point to the code-branch you pinned this down to? 

Some work occurred to make the Stripe logs more accessible. Will try to establish what the state of play is there. 

In general, a review of the donations flow is probably worthwhile. But bandwidth... 😬

**Comment by frankwiles** [comment]
Yeah I'm going to have to dive into soon as Stripe is holding back the deposits until we implement a captcha because apparently people have been using our site to test if cards are active or not. 

There was an issue awhile back around when this ticket was opened which ops resolved soon after, which is why I suggested we close this.

**Comment by carltongibson** [comment]
Oh, I totally misunderstood the import of your “should”. 🙂

It looks like it’s working. I’ll close. If it comes up again we can review.

**Comment by cgl** [comment]
Hi @carltongibson , I don't know if this is fixed or not. The problem was Stripe plans was missing for yearly, montly and quarterly payments. Because of this even tough one time payments/donations were working fine, it was throwing an error when you want to make recurring payments such as a montly donation.

As @frankwiles said it is more of a ops issue then a bug, and the reason can be a upgrade or change in Stripe account resulting in the deletion of Stripe plans. I assume it was working fine previously.

Last time (at DjangoCon sprint), I used my personal credit card to spot the issue, achived to do a succesfull one time donation but when I tried to setup a montly, quarterly or yearly donation it was throwing an error, which I am sure is visible in stripe logs. Testing (reproducing) the problem on development environment was impossible w/o deleting the plans because the plans was missing only from production on Stripe and was available in Stripe sandbox.

In #906 I submitted a management command that could be used to create required plans whenever they are missing. It can be used for ops later too even if it is fixed manually this time. I am happy to improve it, if you are willing to merge it. 

@frankwiles would be nice to hear if you fixed the issue.

**Comment by carltongibson** [comment]
Thanks @cgl. I’m on holiday this week but will try to establish the state of play when I get back.

**Comment by frankwiles** [comment]
Ok so this WAS actually broken. Someone, somehow, removed the subscription plan 'Monthly' pricing plan so it was on the Stripe end of things.  I just fixed and verified this @carltongibson

**Comment by carltongibson** [comment]
OK, well done @frankwiles. (Can you look at #906? That should be worth merging then no?) 

I have thoughts here. We have Fellows and we have the Ops Team, but there's more to manage than there's time for there. 

We also have a load of potential community contributors, including @cgl here, for whom there's a barrier between wanting to do it and being able to.

A quick list of targets: 

* The fundraising flows on djangoproject.com. 
* General pushing forward of the design and IA side of djangoproject.com and the docs site. 
* Django People
* Django Packages
* Django Snippets
* ... 

And none of these are the open source project itself, or supporting packages. 

It would be nice if we could set up teams for these areas, and then make sure they're properly supported by Ops and the Fellows where needed. 

"It would be nice" obviously involves effort. :) I shall put some thought there, since it's been on my mind for a while. 

(@cgl Did you join the DSF, like we talked about in Copenhagen? Do! 🙂)

**Comment by frankwiles** [comment]
Yep #906 is great, put a comment on it.  

I like the idea of another "team" perhaps, but the hard part is of the things listed they are 80% deeper on the technical side (or sensitive).  For example, no one without the production Stripe credentials would have been able to diagnose this.  

And then the remaining 20% is softer skills (copy writing, "customer service", etc) and it might be hard to find some folks that are interested in both sides.

**Comment by carltongibson** [comment]
Let me see what I can draft. 🙂 (bit by bit maybe)

**Comment by cgl** [comment]
Great to hear that the issue is fixed. Thanks @frankwiles 

Also happy to hear #906 is merged. @carltongibson I can built more tools and tests around donation flow, if it is going to be any use. I kept #906 short and focused as I did not know who would discuss, approve and merge it. 

Also @frankwiles please let me know if you want help with captcha, I recently implemented ReCaptcha V3 (invisible) with Django. It would not be too time consuming for me to do it once more for this project. Same goes with Stripe stuff.

(@carltongibson  I joined the DSF, like we talked about in Copenhagen : )

**Comment by carltongibson** [comment]
Hi @cgl. These things go slow but, yes, I think that would be useful. (There were general design ideas that we talked about around this too...) 

I'll sketch my thoughts together and approach the DSF list but, roughly, if we could get a small group together around this (and I'm pretty sure that wouldn't be the hardest bit), and if we could make sure that that group had the right support from Ops (where it was needed) then we could do something better than we have now, sharing some responsibility more widely, whilst making sure an important area was properly covered, where currently maybe it isn't. This last not being a matter of Will, just bandwidth...

As Frank says, there will be sensitive areas, but we're engineers. I'm sure we can solve that. 🙂

> These things go slow but...

As I say, I'll draw up my thoughts. 

Thanks for being involved @cgl!

**Comment by frankwiles** [comment]
@cgl I would love some help with reCaptcha v3 I got started on the process, but didn't have time to finish last weekend.

**Comment by carltongibson** [comment]
Hi @cgl. 

>… let me know if you want help with captcha, I recently implemented ReCaptcha V3 (invisible) with Django. It would not be too time consuming for me to do it once more for this project.

Are you able to put together a PR for this? Or perhaps share an example, or other pointers, if you don't have the bandwidth right now? (We need to get something done, so if you are able to help that would be awesome!) Thanks. 🏅

**Comment by cgl** [comment]
I prepared something, it is WIP. Let me share it as a PR tomorrow.

**Comment by cgl** [comment]
Hi @carltongibson ,
So I could not push it on the weekend but here it is https://github.com/django/djangoproject.com/pull/928 
It is a conceptual PR but it is working end-to-end locally, please take a look and see if that fits into  requirements.
