### ISSUE TITLE
Django 3.0

### ISSUE THREAD

**Issue by mechelement** [django/djangoproject.com#908]
I noticed that the "Writing your first Django app, part 1" webpage of the Django documentation says that Django 3 is being used, but the latest version is 2.2, and 3 is unreleased. Is this a typing error?

**Comment by shaib** [comment]
Hi,

You are looking at https://docs.djangoproject.com/en/dev/intro/tutorial01/ -- where there's also a yellow banner saying this is the documentation for Django's development version. The next version to be released is supposed to be 3.0, so this is correct. You can find the documentation for the last released version in https://docs.djangoproject.com/en/2.2/intro/tutorial01/
