### ISSUE TITLE
Last part of tutorial (7) is confusing and difficult for new users

### ISSUE THREAD

**Issue by roostercrab** [django/djangoproject.com#911]
https://docs.djangoproject.com/en/2.2/intro/tutorial07/

It does not seem functional in a beginner tutorial to tell someone to go find the source files for the django project. The code is simple enough that it could just be posted, even if you want to keep the reference as to where it is coming from.

Currently:
> Where are the Django source files?
> 
> If you have difficulty finding where the Django source files are located on your system, run the following command:
> 
> `$ python -c "import django; print(django.__path__)"`
> 
> Then, just edit the file and replace {{ site_header|default:_('Django administration') }} (including the curly braces) with your own site’s name as you see fit. You should end up with a section of code like:

{% block branding %}
<h1 id="site-name"><a href="{% url 'admin:index' %}">Polls Administration</a></h1>
{% endblock %}

Suggested:
> Create a file admin.html in polls/templates/admin and paste the following into the file:

```
{% extends "admin/base.html" %}
{% block title %}{{ title }} | {{ site_title|default:_('Django site admin') }}{% endblock %}

{% block branding %}
<h1 id="site-name"><a href="{% url 'admin:index' %}">{{ site_header|default:_('Fucking Django Motherfucker') }}</a></h1>
{% endblock %}

{% block nav-global %}

{% endblock %}
```

> You can replace 'Django administration' in the line {{ site_header|default:_('Django administration') }} with your own site’s name as you see fit. You should end up with a section of code like:

> If you would like to see where this code came from you can run this command:
> 
> `$ python -c "import django; print(django.__path__)"`
>

**Comment by felixxm** [comment]
This is the issue tracker for the djangoproject.com website. Documentation bugs should be reported on [Trac](https://code.djangoproject.com/).

**Comment by roostercrab** [comment]
It doesn't help if you can't link to it. Would I also put in a request to
clarify the help page on Trac...whatever that is?
