### ISSUE TITLE
Change link for mysql's charset and collation

### ISSUE THREAD

**Issue by NickCoolii** [django/djangoproject.com#919]
Hi!
@claudep @felixxm 

I suggest change links for MySQL at anchors https://docs.djangoproject.com/en/2.2/ref/settings/#charset and https://docs.djangoproject.com/en/2.2/ref/settings/#collation from `https://dev.mysql.com/doc/refman/en/charset-database.html` to `https://dev.mysql.com/doc/refman/en/charset-charsets.html` because second one contains "Supported Character Sets and Collations" for MySQL instead of previous.

Kind regards.

**Comment by felixxm** [comment]
Thanks, I agree with your proposition. Do you want to provide a patch to [Django](https://github.com/django/django)? If not I can fix this.

PS. This is the issue tracker for the djangoproject.com website.
