### ISSUE TITLE
Custom authentication backend does not get credentials

### ISSUE THREAD

**Issue by ckristhoff** [django/djangoproject.com#925]
Hi everyone

My project uses two authentications ways for different users. Administrator users authenticate themselves with username and password (ModelBackend). Customers authenticate themselves with phonenumber and token (custom authentication backend).
My custom backend authentication backend never gets the credentials. It only works if I use username and password.

```python
class CustomerBackend:
    def authenticate(self, request, phonenumber=None, token=None, **kwargs):
        print(phone_number)
        print(token)
        print(kwargs)
        return None
```

It shows:
```
None
None
{phonenumber: '+17786432446', token: 'abc'}

**Comment by MarkusH** [comment]
Hi @ckristhoff, this issue tracker is not for support requests on using Django. Please use the [django-users](https://docs.djangoproject.com/en/dev/internals/mailing-lists/#django-users) mailing list or the [IRC #django freenode.net channel](irc://irc.freenode.net/django). Please check out https://www.djangoproject.com/community/ for support channels. Thanks.
