### ISSUE TITLE
How to iuse the if to verify a self define filter value

### ISSUE THREAD

**Issue by xauthulei** [django/djangoproject.com#927]
Hi, Team,
  I an newer to this, I want to to verify myself define filter value`{%  if compOsMap|hash:key %}` in the teamplate. it will get this error: 

`Could not parse the remainder: '|' from 'compMap|`

Am I right here, or could you give me some suggestions, Many Thanks

**Comment by felixxm** [comment]
This is the issue tracker for the djangoproject.com website. Please see [UseSupportChannels](https://code.djangoproject.com/wiki/TicketClosingReasons/UseSupportChannels) for ways to get help with Django usage.

**Comment by xauthulei** [comment]
@felixxm , sorry for  that.
