### ISSUE TITLE
Remove django packages RSS feed

### ISSUE THREAD

**Issue by rixx** [django/djangoproject.com#930]
Generally the djangoproject.com refers to djangopackages for any access to packages. But if you go to the main [community page](https://www.djangoproject.com/community/), the last of the RSS feeds links is titled "New/updated Django packages". It also links to [view more](https://www.djangoproject.com/community/packages/) and [Add your feed](https://www.djangoproject.com/community/add/packages/).

All of the feeds in there are from 2017 or older. Since we have djangopackages, I'd argue all of this should be dropped. I guess as a fallback, the RSS feed retrieval could be fixed? But as things stand, this just looks very bad, as it implies that the latest updates in dependencies were 2017 (or the last time somebody cared to look after our main community page).

**Comment by charettes** [comment]
I wonder if we should simply link/retrieve a feed from pypy.org with the Django classifier

https://pypi.org/search/?q=&o=&c=Framework+%3A%3A+Django

**Comment by rixx** [comment]
That might work very well. I'm not sure if there is an RSS version of that, apart from the [unfiltered global one](https://pypi.org/rss/updates.xml). We might request/add that to warehouse, though …
