### ISSUE TITLE
Cannot open ContentFile containing BytesIO content again once it is closed

### ISSUE THREAD

**Issue by alec-implicitdesign** [django/djangoproject.com#931]
Once a ContentFile object containing binary data is closed, it isn't possible to open it again:

```
>>> content = ContentFile(b'\x00\x01\x00\x02\x00\x00\x00\x03')             
>>> content.closed
False
>>> content.file
<_io.BytesIO object at 0x7fa0cd33c8e0>
>>> content.file.closed
False
>>> content.file.close()
>>> content.file.closed
True
>>> content.closed
True
>>> content.read()
*** ValueError: I/O operation on closed file.
>>> content.file.read()
*** ValueError: I/O operation on closed file.
>>> content.open()
*** ValueError: I/O operation on closed file.
```

This process naturally occurs when a serializer writes a content file to a field, making it impossible to open the file later on during another process.

Versions:
Python 3.6
Django 1.11

**Comment by carltongibson** [comment]
This would be an issue with Django, rather than the website... but you’re not meant to use the `file` attribute with `ContentFile`. [See the `File` docs](https://docs.djangoproject.com/en/2.2/ref/files/file/).
