### ISSUE TITLE
Donation

### ISSUE THREAD

**Issue by umocyber** [django/djangoproject.com#938]
Few minutes ago I made  unwittingly donation for 25$, I would like to cancel it and get refund. My email: umocyber@gmail.com Thanks

**Comment by carltongibson** [comment]
Hi @umocyber. Sorry you made the donation in error. Sure you don't want to stick with it? :) 

We'll try and get this processed.

**Comment by carltongibson** [comment]
Ok, this should be done. I presume it takes a few days to appear on your card. Let me know if it doesn’t turn up.
