### ISSUE TITLE
Django + Oracle 18c

### ISSUE THREAD

**Issue by jefflindholm** [django/djangoproject.com#939]
For some reason, it is trying to create the migration table every time.
After it errors
DJANGO_CONTENT_TYPE
DJANGO_MIGRATIONS
are the only tables that exist in the schema

1. New schema 
2. Existing project
3. No migrations make with makemigrations yet

python .\manage.py migrate
Operations to perform:
  Apply all migrations: admin, auth, authtoken, contenttypes, sessions
...
django.db.migrations.exceptions.MigrationSchemaMissing: Unable to create the django_migrations table (ORA-00955: name is already used by an existing object)

Migrations work with Sqlite

Looks like it is not finding the DJANGO_MIGRATIONS table.
I had code that was changing the table name from <table> to SCHEMA.<table>  when I removed this code the error changed to 
Running migrations:
  Applying contenttypes.0001_initial...
 OK
  Applying admin.0001_initial...
...
django.db.utils.DatabaseError: ORA-00942: table or view does not exist

**Comment by felixxm** [comment]
This is the issue tracker for the djangoproject.com website. Please see [TicketClosingReasons/UseSupportChannels](https://code.djangoproject.com/wiki/TicketClosingReasons/UseSupportChannels) for ways to get help with Django usage, you can also add [a new ticket](https://code.djangoproject.com/newticket) if you believe that there is an issue in Django itself. Please be also aware that the above description is not enough to check/reproduce your issue, e.g.
```
I had code that was changing the table name from
to SCHEMA.
```
it is not clear to me what you have done.
