### ISSUE TITLE
deploy problem

### ISSUE THREAD

**Issue by sunxa** [django/djangoproject.com#947]
I encountered the following problems in implementing Step 6, when I was deploying the project.
How can I solve this problem?
     Thanks！

![image](https://user-images.githubusercontent.com/44887620/65117341-7053f280-da1c-11e9-8539-a177db92910a.png)

**Comment by carltongibson** [comment]
This isn't the correct place for support questions. Please use either [Django users](https://groups.google.com/forum/#!forum/django-users) or the [new forum](https://forum.djangoproject.com). 

(IIRC jsonb needs Postgres 9.4. I'd check your version and update if needed.)
