### ISSUE TITLE
Wallpapers are outdated  [new designs attached]

### ISSUE THREAD

**Issue by nemecek-filip** [django/djangoproject.com#952]
Hello,

I was browsing around and noticed [Wallpapers section](https://www.djangoproject.com/community/desktops/) where the biggest available wallpaper is 1680x1050 so I tried creating refreshed ones - see below. If you happen to like them I can provide other resolution variants or source files for Affinity Designer. 

<img width="960" alt="django-wallpaper-gradient" src="https://user-images.githubusercontent.com/49204469/65386034-c4214d00-dd36-11e9-9d72-48b929e99be2.png">
<img width="960" alt="django-wallpaper-solid" src="https://user-images.githubusercontent.com/49204469/65386035-c4b9e380-dd36-11e9-8e84-78d2a8c01a16.png">

**Comment by carltongibson** [comment]
Hey @nemecek-filip — sorry you never got a follow up here. Are you still up for this? Yes, please I think.  😅

Fancy making a PR for it?

**Comment by nemecek-filip** [comment]
Hi @carltongibson damn! Had no idea I opened this three years ago :D 

I think I can look into this! I opened Issue to first discuss the new "design", I assume by PR you mean to also edit the site to surface the wallpapers there?

**Comment by carltongibson** [comment]
Presumably we have the wallpapers in the static folder somewhere, so updating those... (It's Friday... 🥳)

Also, see the related Badges ticket. A refresh there at the same time would be phenomenal. 

I don't think we'll muster a conclusion on a committee for designs, so better to proposed something concrete; we can always adjust later. 

Thanks @nemecek-filip! 🎁

**Comment by GitRon** [comment]
Sorry to resurrect this ticket, but did this ever went to prod?

[Here](https://www.djangoproject.com/community/desktops/) I still see the tiny ones...
