### ISSUE TITLE
intcomma not working in shell 

### ISSUE THREAD

**Issue by engabodaLenmo** [django/djangoproject.com#953]
in django shell
In [1]: from django.contrib.humanize.templatetags.humanize import ( 
   ...:    intcomma, 
   ...: )                                                                                                                                             

In [2]: import django                                                                                                                                 

In [3]: print(intcomma('1235'))
1235
 ------
but it work in file as expected.

**Comment by felixxm** [comment]
This is the issue tracker for the djangoproject.com website, **not** for Django itself. Please  [UseSupportChannels](https://code.djangoproject.com/wiki/TicketClosingReasons/UseSupportChannels) for ways to get help with Django usage.
