### ISSUE TITLE
FAQ about NoSQL outdated

### ISSUE THREAD

**Issue by guettli** [django/djangoproject.com#959]
### Please read this first:

This FAQ is outdated:

https://docs.djangoproject.com/en/2.2/faq/models/#does-django-support-nosql-databases

> Does Django support NoSQL databases?
> NoSQL databases are not officially supported by Django itself. There are, however, a number of > side project and forks which allow NoSQL functionality in Django, like Django non-rel.

The django-no-rel project is outdated. The last commits are several years old.

**Comment by felixxm** [comment]
This is the issue tracker for the djangoproject.com website. Documentation issues should be reported on [Trac](https://code.djangoproject.com/).

**Comment by guettli** [comment]
Thank you for this hint. I created a new issue here:  https://code.djangoproject.com/ticket/31018
