### ISSUE TITLE
Online Search is not working for 2.2 and above

### ISSUE THREAD

**Issue by RamezIssac** [django/djangoproject.com#961]
As title suggests

Searching django documentation online for 2.2 / 3 and dev gives 0 results.
Searching in lesser version is Ok.

**Comment by felixxm** [comment]
I updated indexed it works fine now.

**Comment by carltongibson** [comment]
@felixxm Is there a job for the Release Checklist hidden in there?

**Comment by shaib** [comment]
I was thinking more along the lines of a cron job...

**Comment by carltongibson** [comment]
@shaib "I take your manual job and raise you automation" 😀

**Comment by felixxm** [comment]
It shouldn't be necessary, see [documentation-search](https://github.com/django/djangoproject.com#documentation-search) :man_shrugging:.

**Comment by pauloxnet** [comment]
Actually, to update the documentation and the indexes should be used the `update_docs_and_index` instruction.
I've created a PR #962 to update the file `README.rst`

**Comment by pauloxnet** [comment]
Actually, to update the documentation and the indexes at the same time, the `--update-index` attribute should be used in the `update_docs` command.

To update the documentation and update the indexes there has always been the command `update_docs_and_index` that was removed in commit https://github.com/django/djangoproject.com/commit/0a6cf5cc7e1d8a0a6b5634ade5524ccc5b1f2da6 without an explicit reason.

I created the PR #963 to restored the command and to upda the `README.rst`
