### ISSUE TITLE
Search in documentation is not working for 2.2 and above

### ISSUE THREAD

**Issue by pauloxnet** [django/djangoproject.com#964]
# Issue

As title suggests, searching Django documentation online for 2.2 / 3 and dev gives 0 results.

# Steps

Try to search something in the online documentation for version >= 2.2:
- https://docs.djangoproject.com/en/2.2/search/?q=field

# Solution

To update indexes use the command:

```
python manage.py update_index
```

# Main Problem

It's the second issue related to not-indexed documentation in few days (e.g. #961 )

I think official documentation about [indexing](https://github.com/django/djangoproject.com#documentation-search) need to be updated because to update the documentation and the indexes at the same time should be used in the command:

```
python manage.py update_docs --update-index
```

# Pull Request

In the past there has always been the command `update_docs_and_index` that was removed in commit [`0a6cf5c`](https://github.com/django/djangoproject.com/commit/0a6cf5cc7e1d8a0a6b5634ade5524ccc5b1f2da6#diff-b478d680c67b1b838b7c6568fe8a2129) without an explicit reason.

I created the PR #963 to restored the command and to re-add the `update_docs_and_index` command in the `README.rst`.

**Comment by felixxm** [comment]
![obraz](https://user-images.githubusercontent.com/2865885/69707381-eac68000-10f9-11ea-97e4-5c097ab83a8e.png)

Searching works completely fine for me in 2.2, 3.0 and dev, maybe it's not only about updating indexes (which I did a week ago).

**Comment by pauloxnet** [comment]
Now it's working for me too :thinking: , but when I opened the issue the search was not working for django >= 2 but unfortunately I didn't take a screeshot.

Maybe is something related with cache ?

The "main problem" I reported in this issue is still there and I think the PR #963 is a solution.

**Comment by claudep** [comment]
Search is not working for me right now.

**Comment by pauloxnet** [comment]
Same here. I tried the same search with no results, with different browser sessions and also after I emptied the cache.

https://docs.djangoproject.com/en/2.2/search/?q=field

This time I took a screenshot:
![Screen Shot 2019-12-02 at 08 51 36](https://user-images.githubusercontent.com/521097/69939947-55543300-14e1-11ea-9ced-93008cb6d2e3.png)

**Comment by sanjioh** [comment]
Search is not working for me as well.

**Comment by jnns** [comment]
@sanjioh can you check again now that Django 2.2.8 and Django 3.0 have been released? It wasn't working for me prior to the release, now it is working again.

**Comment by pauloxnet** [comment]
@jnns now is working for me too

**Comment by claudep** [comment]
I guess there might be a gap during docs rebuilding, the search index may be deleted before the refreshed one is available.

**Comment by pauloxnet** [comment]
@claudep actually I rewrote the reindex method
https://github.com/django/djangoproject.com/pull/797/files#diff-b9fd6cf5c87cecdd32b151fb321b5512

The reindex is in a transaction and there's no gap to wait for because it is performed by PostgreSQL.

I think, as I reported ion the issue that in some point the documentation is updated without rebuild the index.

**Comment by sanjioh** [comment]
> @sanjioh can you check again now that Django 2.2.8 and Django 3.0 have been released? It wasn't working for me prior to the release, now it is working again.

Yes, it's working properly now, thanks.

**Comment by jnns** [comment]
Currently, the search index is broken for 3.0 and dev documentation (again). 

![grafik](https://user-images.githubusercontent.com/206281/71976720-4c106180-3217-11ea-8213-9c0f3cb5faa3.png)

**Comment by jnns** [comment]
Sorry to bother again with just another report but no solution: right now, documentation for **3.1** and **dev** is lacking indexing and a search doesn't provide results. All other versions below are working fine.

**Comment by felixxm** [comment]
@jnns It works now.

**Comment by adamchainz** [comment]
Same right now, zero results for 3.1:

![Screenshot_2021-01-12 Search Django documentation Django(4)](https://user-images.githubusercontent.com/857609/104305999-4f42cb00-54c5-11eb-8b8a-194cdc8d7b85.png)

3.0 has results though:

![Screenshot_2021-01-12 Search Django documentation Django(3)](https://user-images.githubusercontent.com/857609/104306029-5a95f680-54c5-11eb-8384-dcae7df20d51.png)

**Comment by dracos** [comment]
"auth" on 3.1 works, but just to note that the issue has bumped up another release and there's nothing on 3.2 or dev currently e.g. https://docs.djangoproject.com/en/3.2/search/?q=logout
![image](https://user-images.githubusercontent.com/154364/144999418-17251d2b-6fdb-4f57-9059-4cbf2b1ada4b.png)

**Comment by adamchainz** [comment]
The search index has refreshed and is working again. There might be a problem around new releases: both Django 4.0 and some security releases were just released.

**Comment by pauloxnet** [comment]
I close this issue because it seems a problem that occurs only temporarily in the update of the documentation

**Comment by adamchainz** [comment]
@pauloxnet I don't think this should be closed. The window of time for which search can fail is non-negligible. I don't have exact timings but from memory it's felt broken for at least an hour. If this occurs relatively frequently, e.g. for every release, that's quite a lot of downtime per year...

**Comment by pauloxnet** [comment]
@adamchainz If you think so feel free to reopen this issue.
I opened the PR #963 to re-add the `update_docs_and_index` to contextually index the documentation index search when update the docs.
If some of you can review that PR we can solve this issue I think.
