### ISSUE TITLE
Creating a user in django

### ISSUE THREAD

**Issue by makutamatey** [django/djangoproject.com#967]
Why won't django make it stress-free for us to add any detail about a user using the user model?
I have been trying to add username, password, email, first_name, last_name to my db, but I keep getting the error below.

**create_user() takes from 2 to 4 positional arguments but 6 were given**.

I also want to add extra fields like location, age to my user model, but it seems it is not easy to do that. 
Can someone help me?

**Comment by felixxm** [comment]
This is the issue tracker for the djangoproject.com website. Please see [TicketClosingReasons/UseSupportChannels](https://code.djangoproject.com/wiki/TicketClosingReasons/UseSupportChannels) for ways to get help with Django usage.
