### ISSUE TITLE
Keep https://code.djangoproject.com/ login

### ISSUE THREAD

**Issue by uri-rodberg** [django/djangoproject.com#972]
https://code.djangoproject.com/ logs me out after about 24 hours, and each time I have to login again (with GitHub). Why doesn't it keep me logged in as long as I'm logged in with GitHub? This is a harass and I think this week I already logged in a few times.

**Comment by carltongibson** [comment]
Hi @uri-rodberg. We’ve had DDOS issues this week to contend with. I think it’s that which is likely causing your issues. (I don’t think you have to login in quite so often in general.)

**Comment by uri-rodberg** [comment]
> Hi @uri-rodberg. We’ve had DDOS issues this week to contend with. I think it’s that which is likely causing your issues. (I don’t think you have to login in quite so often in general.)

I understand. Anyway if possible I think login to https://code.djangoproject.com/ should be for as long as one is logged in with GitHub. On GitHub I'm logged in and I think at least a few months I didn't have to login again.

**Comment by carltongibson** [comment]
Hmmm. OAuth isn’t the same as your GitHub login. Tokens expire. Do you fancy having a dig around to see what it would take?

**Comment by uri-rodberg** [comment]
> Hmmm. OAuth isn’t the same as your GitHub login. Tokens expire. Do you fancy having a dig around to see what it would take?

Yes, this issue is about the token expiring too soon. I think this login token doesn't have to expire. Do you agree that it will not expire? If you do, and you want me to handle the technical issues, show me where is the code of this login and cookie and token and I will check it.

**Comment by carltongibson** [comment]
The Trac conf is here: https://github.com/django/code.djangoproject.com — I think you need to set up this repo and the trac env to test. 

Checking my cookies, TRAC looks to have login of about 2 weeks, which I'd say matches my experience, before this week.

I'd be inclined to say that's a reasonable period. Re-logging in involves just clicking the Login with GitHub link again, which isn't hard. 

So I'd be inclined to suggest holding off on doing too much work, and keep an eye on how often you have to login under _normal conditions_.

**Comment by uri-rodberg** [comment]
> The Trac conf is here: https://github.com/django/code.djangoproject.com — I think you need to set up this repo and the trac env to test.

It looks to me just a setting which the Django team can change, or can keep as it is:

https://github.com/django/code.djangoproject.com/blob/master/trac-env/conf/trac.ini#L279

Anyway as far as I remember, I logged in recently more than once in every 14 days. And anyway, personally I would prefer this number to be bigger. I even don't mind if it will be 30 years (it's not a typo, I wrote **years**).

**Comment by uri-rodberg** [comment]
By the way, maybe this issue belongs to https://github.com/django/code.djangoproject.com/issues ? I was referred here from the developers mailing list.

**Comment by carltongibson** [comment]
Yeah.. OK. I don't think we'd extend the cookie lifetime definitely like that. I don't think it's a GitHub OAuth issue, but I'll keep a mental eye on how often I have to log back in. If it's too often we can look at it.

**Comment by uri-rodberg** [comment]
It's a session cookie. I had a power (electricity) failure (for the third time today), and now I'm logged out again. Last time I logged in was today.

![2020-01-24_1855](https://user-images.githubusercontent.com/12808124/73087412-2653af80-3edb-11ea-8c1b-4fe309c1d1c1.png)

**Comment by uri-rodberg** [comment]
On GitHub I'm still logged in without having to login again.

![2020-01-24_1900](https://user-images.githubusercontent.com/12808124/73087824-c90c2e00-3edb-11ea-8f83-25651a0f4f95.png)

**Comment by uri-rodberg** [comment]
@carltongibson 

Maybe this issue belongs to https://github.com/django/code.djangoproject.com/issues and not here?

Do you want to transfer this issue to https://github.com/django/code.djangoproject.com/issues?

**Comment by uri-rodberg** [comment]
@felixxm 
@carltongibson

**Comment by carltongibson** [comment]
@uri-rodberg Please don't do that.

**Comment by uri-rodberg** [comment]
I checked and after 3 or 4 days I'm already logged out, even with the same browser session. The login expires after about 1 to 3 days.

**Comment by carltongibson** [comment]
This doesn't seem a real problem to me in my day-to-day usage. (Worst case: I click the login button to refresh the session.) 
Short of an actual PR with a proposed change I don't this this is worth effort to address.
