### ISSUE TITLE
Wrong Django Version Geting Installed.

### ISSUE THREAD

**Issue by ankur29mac** [django/djangoproject.com#973]
Hi, I tried installing Django's latest version using pipenv on my linux mint system.
command used :  **pipenv python 3.7 install django==3.0.2**

Wrong django version getting installed even after specfying the '3.0.2' version.
$python
Python 3.7.4 (default, Aug  5 2019, 20:10:18) 
[GCC 7.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import django
>>> django.VERSION
(2, 2, 7, 'final', 0)

**Pipfile:**
[[source]]
name = "pypi"
url = "https://pypi.org/simple"
verify_ssl = true

[dev-packages]

[packages]
django = "==3.0.2"

[requires]
python_version = "3.7"

**Comment by felixxm** [comment]
This is the issue tracker for the website at djangoproject.com.

For getting support with using Django, please follow the links in [our documentation](https://docs.djangoproject.com/en/stable/faq/help/).
