### ISSUE TITLE
Dynamic fieldset is not showing as per intended 

### ISSUE THREAD

**Issue by vishalrawat123** [django/djangoproject.com#976]
When i wants to show dynamic fieldset in admin panel according the user type of current admin panel user (staff or superuser)
Sometime (on refreshing the page) It is not showing the field dynamic like in case of staff it shows the both approved_by_staff and approved_by_admin fields

![Screenshot from 2020-02-04 11-11-44](https://user-images.githubusercontent.com/58972615/73717229-2f484a80-473f-11ea-9191-0157897e14d9.png)

here the output for the same with staff user

![Screenshot from 2020-02-04 11-17-32](https://user-images.githubusercontent.com/58972615/73717509-070d1b80-4740-11ea-9376-f1ae2a78170a.png)

**Comment by felixxm** [comment]
This is the issue tracker for the djangoproject.com website. Please see [TicketClosingReasons/UseSupportChannels](https://code.djangoproject.com/wiki/TicketClosingReasons/UseSupportChannels) for ways to get help with Django usage.
