### ISSUE TITLE
add keyword suggestions to the documentation search bar

### ISSUE THREAD

**Issue by pasraj** [django/djangoproject.com#977]
https://docs.djangoproject.com/en/3.0/ 
In the suggestion bar there is no showing suggestion to user to getting easily information

**Comment by pasraj** [comment]
https://docs.djangoproject.com/en/3.0/ 
In the suggestion bar there is no showing suggestion to user to getting easily information

**Comment by nanlliu** [comment]
can I work on this? i guess we probably need to add js for that?

**Comment by anujpatel224** [comment]
is anyone working on this issue?

**Comment by carltongibson** [comment]
@anujpatel224 — not that I know of. We're open to improvements.

**Comment by timgraham** [comment]
I guess Google works fine for search bar suggestions.
