### ISSUE TITLE
Forms Example has a Form that is Out of Scope

### ISSUE THREAD

**Issue by largeDachshund** [django/djangoproject.com#980]
The example is on this page: [https://docs.djangoproject.com/en/3.0/topics/forms/](url)

Here's the bug:
from django.http import HttpResponseRedirect
from django.shortcuts import render

from .forms import NameForm
`
def get_name(request):
       # if this is a POST request we need to process the form data
       if request.method == 'POST':
        # create a form instance and populate it with data from the request:
           **form** = NameForm(request.POST)
        # check whether it's valid:
           if form.is_valid():
               # process the data in form.cleaned_data as required
               # ...
               # redirect to a new URL:
               return HttpResponseRedirect('/thanks/')

    # if a GET (or any other method) we'll create a blank form
    else:
        **form** = NameForm()

    return render(request, 'name.html', {'form': **form**})
`

If you look at the instance of **form**, you'll notice the render function will err out with a "reference before definition" exception.

**Comment by largeDachshund** [comment]
No error.  Another look at the indents and I realized I was out of order.

Have a great day!

**Comment by ubernostrum** [comment]
In the future, please be aware that this repository is just the code that runs the djangoproject.com site -- Django itself, including the documentation, uses [Trac](https://code.djangoproject.com/) for reporting and tracking issues.
