### ISSUE TITLE
Code snippets header selection is not visible on Firefox

### ISSUE THREAD

**Issue by mdamien** [django/djangoproject.com#987]
When selection the text of the header of the snippet, it works well under Chrome:

![image](https://user-images.githubusercontent.com/1469823/78601479-22d29200-7855-11ea-9d57-5a1aa7364b44.png)

But under Firefox, the selection is not visible.

This is a bit problematic since the user often wants to copy-paste the filename in the header.

Example of a page where the bug can be reproduced: https://docs.djangoproject.com/en/3.0/intro/tutorial02/#id2

**Comment by shaib** [comment]
Just to clarify: The filename in the header is visible. But when you select it with the mouse, you can't see what's selected.

**Comment by kunals131** [comment]
I want to work on this issue if its still open
