### ISSUE TITLE
Misspelling in documentation

### ISSUE THREAD

**Issue by durey** [django/djangoproject.com#988]
The original English version of [this documentation page](https://docs.djangoproject.com/en/3.0/topics/i18n/translation/#standard-translation) contains an example in Spanish with a misspelling: "Hoy es 26 de Noviembre", since month names in Spanish always start with lowercase (except when starting a sentence, as obvious). It should be "Hoy es 26 de noviembre".

Of course, every single translation of that original text has the misspelling too.

**Comment by felixxm** [comment]
This is the issue tracker for the djangoproject.com website, so for the future if you want to submit a bug report or a feature request to Django, you can find instructions [here](https://docs.djangoproject.com/en/stable/internals/contributing/bugs-and-features/).

I fixed this typo in https://github.com/django/django/pull/12805.

**Comment by durey** [comment]
Thanks, @felixxm! 

Just to notice it, in case someone decides to improve guidelines: I read that piece of info you just copied, but I still had no clue where the contents of the website were stored. I saw no info stating that the texts are stored in a database, or in a Github repo, or in which one. So, I assumed the Django repo is for the python library itself, and the Djangoproject.com repo is for the website with its contents (doesn't it make sense if no info about that in the issue tracker?).

**Comment by felixxm** [comment]
Typo is in the Django documentation (docs.djangoproject.com), which is hosted by djangoproject.com. Documentation is a part of Django repository. We could probably clarify this, e.g.:

_"If you want to submit a bug report or a feature request to Django **(including [documentation](https://docs.djangoproject.com))**, you can find instructions here."_

What do you think?

**Comment by durey** [comment]
Oh, that would be perfect!
