### ISSUE TITLE
Updated Fundraising page

### ISSUE THREAD

**Issue by wsvincent** [django/djangoproject.com#994]
Hi all,

Our [fundraising page](https://github.com/django/djangoproject.com/blob/master/djangoproject/templates/fundraising/index.html#L141) could use a refresh to reflect the addition of Github Sponsors as well as our [official merchandise store](https://django.threadless.com) which has modest sales given it is not well represented.

Absent a redesign of the page, which probably is warranted at some point, adding both near the top of the page is the simplest implementation. We should also look at whether continuing to link to Amazon Smile and Benevity (linked lower down) continues to make sense.

As inspiration, [VueJS](https://vuejs.org) makes the 3 ways to contribute clear in the nav bar under "Support Vue" for One-Time Donations, Recurring, and T-Shirt Shop. We have all 3; we're just not making them visible.

**Comment by carltongibson** [comment]
Hi @wsvincent. Is this something you've worked on, or is it still at the ideas phase? 

More or less, _Yes, super_ but what needs to happen to resolve this?

**Comment by jefftriplett** [comment]
Can we throw some community at this issue to make it happen? I tweeted out a reminder about the store yesterday and I think we had three sales from it. If one of my tweets is three sales, then I bet adding this feature will be hundreds of sales.

**Comment by wsvincent** [comment]
Confirm we have several sales from @jefftriplett 's tweet. I'd love if someone would update the text to make merch store and Github Sponsor links more prominent on this page but can't myself right now.

**Comment by carltongibson** [comment]
> Can we throw some community at this issue to make it happen?

Perhaps an email to the DSF Members list? — it needs someone with a few hours of bandwidth to get it going.

**Comment by imkaka** [comment]
@wsvincent I will be happy to work on it, please guide me in this.

**Comment by marksweb** [comment]
Hello,

I saw a tweet from @jefftriplett & thought this sounded like something I could help out with.

Is this the kind of thing you had in mind?

![Screenshot 2020-08-05 at 22 40 34](https://user-images.githubusercontent.com/1461191/89466969-b0bf7a80-d76c-11ea-9935-b6fe2f5f0799.png)

**Comment by jefftriplett** [comment]
@marksweb thank you, I think that's a great start. 

@carljm @wsvincent thoughts? 

would we want to do a follow-up ticket to pull in / list sponsors since that's a much larger project? We can automate it, but that takes more coordination.

**Comment by wsvincent** [comment]
Hi @marksweb,

I think the simplest thing is to move the "Other ways to give" section to the top spot, so right above where "Why give to the Django Software Foundation" is now but under the "Support" section.

Within it, probably having the Github and merch links first makes sense given they account for far more $ to the DSF than the other two.

So, similar to what you suggested:

* [GitHub Sponsors](https://github.com/sponsors/django) - Become a Django Sponsor via Github, starting at $5 a month.
* [Official Merchandise Store](https://django.threadless.com/) - Buy official t-shirts and more to support Django.
* Amazon...
* Benevity...

That's my 2 cents! As long as the Github/Merch links are near the top of the page though I'm very happy.

**Comment by marksweb** [comment]
Thanks @wsvincent - I'll shuffle things around & put together another screenshot.

**Comment by marksweb** [comment]
@wsvincent @jefftriplett 

Ok this makes so much more sense at the top there having moved it & read the page through.

I've also put it in the footer - not sure how you'd feel about that but the focus seems to be on making sure people see this, so worth looking at I think.

![screencapture-djangoproject-localhost-8000-fundraising-2020-08-06-15_21_30](https://user-images.githubusercontent.com/1461191/89543389-c4182780-d7f8-11ea-91b3-c68e33b70f04.png)

**Comment by wsvincent** [comment]
That looks pretty awesome to me. Others?

**Comment by carltongibson** [comment]
This looks great. 

I have one query: we have the **Donate** button, then right below it, we have _Go to GitHub sponsors, and pay from $5/month_.

GitHub Sponsors is great, but do we want that link there? It seems to me a distraction from the **Donate** button.

**Comment by jefftriplett** [comment]
Looks great to me. 

Re: "Go to GitHub sponsors, and pay from $5/month." -- Unless the text changed, I see "Become..." which looks fine to me.

**Comment by carltongibson** [comment]
My point isn't the text, I was paraphrasing. 🙂

Rather, is this the place to mention GitHub Sponsors at all?

The analogy is the e-commerce checkout: vendors systematically remove distractions/options so as the guide users better to the desired action. 

Our desired action is the **Donate** button no? 

So should we not avoid mentioning alternatives, especially priming a low value like $5, when if the click the button we'd like them to go for more (if possible)

I'm not sure why we're mentioning GHS at all here?

🤔

**Comment by wsvincent** [comment]
I see Carlton’s point. I think he’s correct to leave it off actually. Keep the rest—especially merch—but GH sponsors makes more sense in the GH world vs here for a number of reasons.

**Comment by marksweb** [comment]
Thanks @carltongibson 

I've removed the github donate links & pushed the changes (ref above this comment).

If you're happy I'll open a PR.

FYI @wsvincent @jefftriplett

**Comment by jefftriplett** [comment]
@marksweb this is great. thank you! (sorry, to keep dragging this out) 

@carltongibson @wsvincent I disagree. Who cares if they use one over the other? 

By removing GitHub sponsors from the webpage, we are back to not promoting the option at all. When I visit the page, I want to know how to support the DSF.

GitHub Sponsors brings in a healthy amount of money to the DSF each month, and it's one of the easiest ways for employees to give the DSF through their monthly GitHub bill without having to ask to justify a direct donation through our Donate button. Many companies won't approve a donation, but they don't look twice at their monthly GitHub bill. 

The same goes for people like myself who pay my GitHub bill and donate to several orgs/maintainers. I just want one bill and I'd rather pay each month vs. once a year. 

My worry about not listing it on this page is that it's not as obvious on GitHub unless you know where to look for it. 

If someone doesn't want to use GitHub, then great, click the donate button, but historically this is a harder process to manage as you both know.

**Comment by carltongibson** [comment]
Hey @jefftriplett. 

The concern is distracting people. I'm not at all convinced that pointing people to an alternate option at the point of action is good interaction design. 

I'm not seeing that GHS is such a good option that we should **point away** from the payment form. 

(I thought the goal here was to point to the merch store?)

@marksweb Thanks for your work here. Can you open a PR from you branch, we'll get this in likely early next week. 🏅

**Comment by marksweb** [comment]
PR opened.

I think you should have the Github sponsors link, at least in the footer. Your donation form is the focus, it's big & interesting so catches the eye. But then under it people have to read & understand what those links are before they'll click them.

If someone wants to support via GH then great, they already know about the project - they came to the website, so they may come back, or they may just start supporting. If you don't have the link they might not use the donation form & they may not ever know that github sponsors exists.

I think I have this option a negative connotation because I used "from $5", but in my experience that's how you get people interested, then once they've got to that page they might see the various tiers & chose to give more, but you've got to get them there in the first place.

**Comment by carltongibson** [comment]
Hi @marksweb Thanks for the PR. Super. I'll get it in next week!

**Comment by marksweb** [comment]
You're welcome. If there's anything else that you are looking for contributions on ping me. I've been using django nearly 10 years, it's about time I contributed!!

**Comment by carltongibson** [comment]
Hi all.  

I’ve taken it that #1015 closes this, but original scope seems somewhat bigger. `As inspiration...`A full redesign is not really actionable as such: it’s the sort of thing that could live on the issue tracker forever. Happy to see input in that direction but I think it needs a concrete suggestion — _We’re going to do this!_ — to move it forwards. 

I suspect a group from (say) the DSF members list might be convinced to work on it together. (We are web professionals, last time I looked at least, surely we can do something... 😃)

I'll update https://www.djangoproject.com/foundation/donate/ to match. This is a flatpage. 🎩 to @felixxm for noticing.

**Comment by carltongibson** [comment]
And that's updated.
