### ISSUE TITLE
Community blog missed for Approved Feed

### ISSUE THREAD

**Issue by gauravvjn** [django/djangoproject.com#999]
I submitted a post a few days ago https://www.pyscoop.com/security-in-the-django-application/
and it's been more than 10 days, I don't see the post appearing on the page(https://www.djangoproject.com/community/blogs/) yet. However, there is another post from the same RSS Feed from my blog is appearing here. So the issue is, 1 post is appearing and another one is not from the same Feed? 

There is no way for us to know what happened to that specific post whether accepted or rejected if so what was the reason.

EDIT(30 May): I updated the date for this specific post in my RSS feed just to verify if that can be processed again, but, again, the same story. I've no clue why this can happen?

**Comment by MarkusH** [comment]
How/where did you submit the post? The second link (https://www.djangoproject.com/community/blogs/) is a "planet", collecting blog posts from several blogs out there, automatically.

**Comment by gjain0** [comment]
@MarkusH, I added it here https://www.djangoproject.com/community/add/blogs/.
I hope anyone can add here or is it limited to specific blogs?

On a similar note, I have two questions. 

1) How do you collect blogs automatically from several blogs? Is there a list you maintain at your end? If so, what is the procedure/criteria to include my blog there?

2) There is another section called **Links**: https://www.djangoproject.com/community/add/links/
I'm not quite sure how it is different from the above blogs.

**Comment by carltongibson** [comment]
This is a duplicate of #1137
